# frozen_string_literal: true

puts 'Seeding villages of Bumthang...'
[
  # Chhoekhor geog
  { id: '1', name: 'Chagkhar', user_id: User.first.id, extension_id: 1 },
  { id: '2', name: 'Chamkhar', user_id: User.first.id, extension_id: 1 },
  { id: '3', name: 'Chamkhar Throm', user_id: User.first.id, extension_id: 1 },
  { id: '4', name: 'Changwa', user_id: User.first.id, extension_id: 1 },
  { id: '5', name: 'Damphel', user_id: User.first.id, extension_id: 1 },
  { id: '6', name: 'Dawathang', user_id: User.first.id, extension_id: 1 },
  { id: '7', name: 'Dur Dok', user_id: User.first.id, extension_id: 1 },
  { id: '8', name: 'Dhur Lusibee', user_id: User.first.id, extension_id: 1 },
  { id: '9', name: 'Dhur Moen', user_id: User.first.id, extension_id: 1 },
  { id: '10', name: 'Dorong', user_id: User.first.id, extension_id: 1 },
  { id: '11', name: 'Dorjibi', user_id: User.first.id, extension_id: 1 },
  { id: '12', name: 'Goling', user_id: User.first.id, extension_id: 1 },
  { id: '13', name: 'Gongkhar', user_id: User.first.id, extension_id: 1 },
  { id: '14', name: 'Gyelkhar', user_id: User.first.id, extension_id: 1 },
  { id: '15', name: 'Jakar', user_id: User.first.id, extension_id: 1 },
  { id: '16', name: 'Jakar Lhakhang', user_id: User.first.id, extension_id: 1 },
  { id: '17', name: 'Jamba Lhakhang', user_id: User.first.id, extension_id: 1 },
  { id: '18', name: 'Koenchhogsum', user_id: User.first.id, extension_id: 1 },
  { id: '19', name: 'Khangdrok', user_id: User.first.id, extension_id: 1 },
  { id: '20', name: 'Kharsa', user_id: User.first.id, extension_id: 1 },
  { id: '21', name: 'Kharsoom', user_id: User.first.id, extension_id: 1 },
  { id: '22', name: 'Lamagonpa', user_id: User.first.id, extension_id: 1 },
  { id: '23', name: 'Ngang Lhakhang', user_id: User.first.id, extension_id: 1 },
  { id: '24', name: 'Nangsephel/Tendok', user_id: User.first.id, extension_id: 1 },
  { id: '25', name: 'Nangsiphel', user_id: User.first.id, extension_id: 1 },
  { id: '26', name: 'Norbugang', user_id: User.first.id, extension_id: 1 },
  { id: '27', name: 'Pangri', user_id: User.first.id, extension_id: 1 },
  { id: '28', name: 'Pedtsheling', user_id: User.first.id, extension_id: 1 },
  { id: '29', name: 'Poengar', user_id: User.first.id, extension_id: 1 },
  { id: '30', name: 'Potola', user_id: User.first.id, extension_id: 1 },
  { id: '31', name: 'Samthang', user_id: User.first.id, extension_id: 1 },
  { id: '32', name: 'Saram', user_id: User.first.id, extension_id: 1 },
  { id: '33', name: 'Shoogdak', user_id: User.first.id, extension_id: 1 },
  { id: '34', name: 'Tamshing', user_id: User.first.id, extension_id: 1 },
  { id: '35', name: 'Tashiling (Chhoekhor)', user_id: User.first.id, extension_id: 1 },
  { id: '36', name: 'Toendok', user_id: User.first.id, extension_id: 1 },
  { id: '37', name: 'Thangbi', user_id: User.first.id, extension_id: 1 },
  { id: '38', name: 'Tengkarzhong', user_id: User.first.id, extension_id: 1 },
  { id: '39', name: 'Wangdicholing', user_id: User.first.id, extension_id: 1 },
  { id: '40', name: 'Zangling', user_id: User.first.id, extension_id: 1 },
  { id: '41', name: 'Zhabjethang', user_id: User.first.id, extension_id: 1 },
  { id: '42', name: 'Sangsangma', user_id: User.first.id, extension_id: 1 },
  { id: '43', name: 'Tashigatshel', user_id: User.first.id, extension_id: 1 },
  { id: '44', name: 'Dekiling', user_id: User.first.id, extension_id: 1 },

  # Chumey geog
  { id: '46', name: 'Bim', user_id: User.first.id, extension_id: 2 },
  { id: '47', name: 'Bjuli', user_id: User.first.id, extension_id: 2 },
  { id: '48', name: 'Buli/Uru', user_id: User.first.id, extension_id: 2 },
  { id: '49', name: 'Chhoedeypang', user_id: User.first.id, extension_id: 2 },
  { id: '50', name: 'Chhoedraag', user_id: User.first.id, extension_id: 2 },
  { id: '51', name: 'Choongphel', user_id: User.first.id, extension_id: 2 },
  { id: '52', name: 'Domkhar', user_id: User.first.id, extension_id: 2 },
  { id: '53', name: 'Gyaltsa', user_id: User.first.id, extension_id: 2 },
  { id: '54', name: 'Nangar', user_id: User.first.id, extension_id: 2 },
  { id: '55', name: 'Nga-ngey(Chorten Nyingpo)', user_id: User.first.id, extension_id: 2 },
  { id: '56', name: 'Pangtoed Goenpa', user_id: User.first.id, extension_id: 2 },
  { id: '57', name: 'Phurjoen', user_id: User.first.id, extension_id: 2 },
  { id: '58', name: 'Samtenling', user_id: User.first.id, extension_id: 2 },
  { id: '59', name: 'Terzoed', user_id: User.first.id, extension_id: 2 },
  { id: '60', name: 'Tharpaling', user_id: User.first.id, extension_id: 2 },
  { id: '61', name: 'Thomed', user_id: User.first.id, extension_id: 2 },
  { id: '62', name: 'Thometh(Samlling)', user_id: User.first.id, extension_id: 2 },
  { id: '63', name: 'Trakar', user_id: User.first.id, extension_id: 2 },
  { id: '64', name: 'Oongsang', user_id: User.first.id, extension_id: 2 },
  { id: '65', name: 'Uru', user_id: User.first.id, extension_id: 2 },
  { id: '66', name: 'Urudrangbi', user_id: User.first.id, extension_id: 2 },
  { id: '67', name: 'Yamthrag', user_id: User.first.id, extension_id: 2 },
  { id: '68', name: 'Yid-Rangbi', user_id: User.first.id, extension_id: 2 },
  { id: '69', name: 'Zhichhag', user_id: User.first.id, extension_id: 2 },
  { id: '70', name: 'Zhurey', user_id: User.first.id, extension_id: 2 },
  { id: '71', name: 'Zurgney/Choten Nengpa', user_id: User.first.id, extension_id: 2 },
  { id: '72', name: 'Zung-Ngae', user_id: User.first.id, extension_id: 2 },

  # Tang geog
  { id: '74', name: 'Beinzaibi', user_id: User.first.id, extension_id: 3 },
  { id: '75', name: 'Bepzur', user_id: User.first.id, extension_id: 3 },
  { id: '76', name: 'Choejam', user_id: User.first.id, extension_id: 3 },
  { id: '77', name: 'Chhutoed', user_id: User.first.id, extension_id: 3 },
  { id: '78', name: 'Dazur', user_id: User.first.id, extension_id: 3 },
  { id: '79', name: 'Gaamling', user_id: User.first.id, extension_id: 3 },
  { id: '80', name: 'Gangjued', user_id: User.first.id, extension_id: 3 },
  { id: '81', name: 'Gemzhong', user_id: User.first.id, extension_id: 3 },
  { id: '82', name: 'Jog', user_id: User.first.id, extension_id: 3 },
  { id: '83', name: 'Khangrab', user_id: User.first.id, extension_id: 3 },
  { id: '84', name: 'Khoedyar', user_id: User.first.id, extension_id: 3 },
  { id: '85', name: 'Kidzom', user_id: User.first.id, extension_id: 3 },
  { id: '86', name: 'Kuenzangdrag', user_id: User.first.id, extension_id: 3 },
  { id: '87', name: 'Langmalung', user_id: User.first.id, extension_id: 3 },
  { id: '88', name: 'Mi-sed-thang', user_id: User.first.id, extension_id: 3 },
  { id: '89', name: 'Namkha', user_id: User.first.id, extension_id: 3 },
  { id: '90', name: 'Nangnang', user_id: User.first.id, extension_id: 3 },
  { id: '91', name: 'Nyimalung', user_id: User.first.id, extension_id: 3 },
  { id: '92', name: 'Pangshing', user_id: User.first.id, extension_id: 3 },
  { id: '93', name: 'Phom Drong', user_id: User.first.id, extension_id: 3 },
  { id: '94', name: 'Rimochen', user_id: User.first.id, extension_id: 3 },
  { id: '95', name: 'Sarmaed', user_id: User.first.id, extension_id: 3 },
  { id: '96', name: 'Shoboong-goenpa', user_id: User.first.id, extension_id: 3 },
  { id: '97', name: 'Tandingang', user_id: User.first.id, extension_id: 3 },
  { id: '98', name: 'Tashiling (Tang)', user_id: User.first.id, extension_id: 3 },
  { id: '99', name: 'Tralang', user_id: User.first.id, extension_id: 3 },
  { id: '100', name: 'Ugyenchhoeling', user_id: User.first.id, extension_id: 3 },

  # Ura geog
  { id: '102', name: 'Belteng', user_id: User.first.id, extension_id: 4 },
  { id: '103', name: 'Pangkhar', user_id: User.first.id, extension_id: 4 },
  { id: '104', name: 'Shingkhar', user_id: User.first.id, extension_id: 4 },
  { id: '105', name: 'Shing-Nyer', user_id: User.first.id, extension_id: 4 },
  { id: '106', name: 'Somthrang', user_id: User.first.id, extension_id: 4 },
  { id: '107', name: 'Tangsibi', user_id: User.first.id, extension_id: 4 },
  { id: '108', name: 'Ura-Chari', user_id: User.first.id, extension_id: 4 },
  { id: '109', name: 'Ura-Tarshong', user_id: User.first.id, extension_id: 4 },
  { id: '110', name: 'Ura-Toepda', user_id: User.first.id, extension_id: 4 },
  { id: '111', name: 'Ura-Trabee (Krispa)', user_id: User.first.id, extension_id: 4 },

  # Bumthang thromde
  { id: '112', name: 'Bumthang Thromde', user_id: User.first.id, extension_id: 5 }
].each do |v|
  vl = Village.find_or_initialize_by(id: v[:id])
  vl.update!(v)
end
