# frozen_string_literal: true

puts 'Seeding villages of Chhukha...'
[
  # Bjagchhog geog
  { id: '132', name: 'Bjagchhog', user_id: User.first.id, extension_id: 6 },
  { id: '133', name: 'Mebisa', user_id: User.first.id, extension_id: 6 },
  { id: '134', name: 'Tsimalakha', user_id: User.first.id, extension_id: 6 },
  { id: '135', name: 'Tsimakothi', user_id: User.first.id, extension_id: 6 },
  { id: '136', name: 'Wangkha', user_id: User.first.id, extension_id: 6 },

  # Bongo geog
  { id: '138', name: 'Baeyuel Kunzang', user_id: User.first.id, extension_id: 7 },
  { id: '139', name: 'Boeri', user_id: User.first.id, extension_id: 7 },
  { id: '140', name: 'Bongo', user_id: User.first.id, extension_id: 7 },
  { id: '141', name: 'Chhasilakha', user_id: User.first.id, extension_id: 7 },
  { id: '142', name: 'Choongkha', user_id: User.first.id, extension_id: 7 },
  { id: '143', name: 'Damji', user_id: User.first.id, extension_id: 7 },
  { id: '144', name: 'Gedu', user_id: User.first.id, extension_id: 7 },
  { id: '145', name: 'Jumjag', user_id: User.first.id, extension_id: 7 },
  { id: '146', name: 'Joonglay', user_id: User.first.id, extension_id: 7 },
  { id: '147', name: 'Ketogkha', user_id: User.first.id, extension_id: 7 },
  { id: '148', name: 'Miritsemo', user_id: User.first.id, extension_id: 7 },
  { id: '149', name: 'Pakshikha', user_id: User.first.id, extension_id: 7 },
  { id: '150', name: 'Phashooma', user_id: User.first.id, extension_id: 7 },
  { id: '151', name: 'Togtokha', user_id: User.first.id, extension_id: 7 },
  { id: '152', name: 'Zamsa', user_id: User.first.id, extension_id: 7 },

  # Chapchha geog
  { id: '154', name: 'Bunakha', user_id: User.first.id, extension_id: 8 },
  { id: '156', name: 'Gangkha', user_id: User.first.id, extension_id: 8 },
  { id: '155', name: 'Dorgoen', user_id: User.first.id, extension_id: 8 },
  { id: '157', name: 'Jongzhi', user_id: User.first.id, extension_id: 8 },
  { id: '158', name: 'Lobneykha', user_id: User.first.id, extension_id: 8 },
  { id: '159', name: 'Metep', user_id: User.first.id, extension_id: 8 },
  { id: '160', name: 'Paggar', user_id: User.first.id, extension_id: 8 },
  { id: '161', name: 'Rimtekha', user_id: User.first.id, extension_id: 8 },
  { id: '162', name: 'Shelgoan', user_id: User.first.id, extension_id: 8 },
  { id: '163', name: 'Shelyuel', user_id: User.first.id, extension_id: 8 },
  { id: '164', name: 'Tshamdrag', user_id: User.first.id, extension_id: 8 },
  { id: '165', name: 'Paggar Goenpa', user_id: User.first.id, extension_id: 8 },

  # Darla geog
  { id: '167', name: 'Chhumaedlakha (Barkhey)', user_id: User.first.id, extension_id: 9 },
  { id: '168', name: 'Dangreybu (Bich Darla)', user_id: User.first.id, extension_id: 9 },
  { id: '169', name: 'Tagp-Thang-Bu (Bich Saureni)', user_id: User.first.id, extension_id: 9 },
  { id: '170', name: 'Dojangchhey (Dojangchey)', user_id: User.first.id, extension_id: 9 },
  { id: '171', name: 'Gamanang', user_id: User.first.id, extension_id: 9 },
  { id: '172', name: 'Gengu', user_id: User.first.id, extension_id: 9 },
  { id: '173', name: 'Nyimgang(Ghamdara)', user_id: User.first.id, extension_id: 9 },
  { id: '174', name: 'Rinchhentse(GurungGoan)', user_id: User.first.id, extension_id: 9 },
  { id: '175', name: 'Kimalakha', user_id: User.first.id, extension_id: 9 },
  { id: '176', name: 'Khamaedtapthang (Lower Saureni)', user_id: User.first.id, extension_id: 9 },
  { id: '177', name: 'Pagshinggang (Pakshina)', user_id: User.first.id, extension_id: 9 },
  { id: '178', name: 'Samarchen (Samachin)', user_id: User.first.id, extension_id: 9 },
  { id: '179', name: 'Sillangsa (Silley)', user_id: User.first.id, extension_id: 9 },
  { id: '180', name: 'Sinchula', user_id: User.first.id, extension_id: 9 },
  { id: '181', name: 'Tabji', user_id: User.first.id, extension_id: 9 },
  { id: '182', name: 'Khateytapthang(Upper Saureni)', user_id: User.first.id, extension_id: 9 },
  { id: '183', name: 'Yagang', user_id: User.first.id, extension_id: 9 },
  { id: '184', name: 'Sharphug (Sangkhu)', user_id: User.first.id, extension_id: 9 },

  # Doongna geog
  { id: '186', name: 'Babana', user_id: User.first.id, extension_id: 10 },
  { id: '187', name: 'Doongma', user_id: User.first.id, extension_id: 10 },
  { id: '188', name: 'Uezhi', user_id: User.first.id, extension_id: 10 },
  { id: '189', name: 'Mangdokha', user_id: User.first.id, extension_id: 10 },
  { id: '190', name: 'Pangu', user_id: User.first.id, extension_id: 10 },
  { id: '191', name: 'Drukdingsa', user_id: User.first.id, extension_id: 10 },

  # Geling geog
  { id: '193', name: 'Chang-nyeykha', user_id: User.first.id, extension_id: 11 },
  { id: '194', name: 'Dagpa', user_id: User.first.id, extension_id: 11 },
  { id: '195', name: 'Dilib', user_id: User.first.id, extension_id: 11 },
  { id: '196', name: 'Geygoen', user_id: User.first.id, extension_id: 11 },
  { id: '197', name: 'Na-yekha', user_id: User.first.id, extension_id: 11 },
  { id: '198', name: 'Omchhu', user_id: User.first.id, extension_id: 11 },
  { id: '199', name: 'Tsanglingna', user_id: User.first.id, extension_id: 11 },
  { id: '200', name: 'Kamji', user_id: User.first.id, extension_id: 11 },

  # Getana geog
  { id: '202', name: 'Bachhu', user_id: User.first.id, extension_id: 12 },
  { id: '203', name: 'Chiyuel', user_id: User.first.id, extension_id: 12 },
  { id: '204', name: 'Darga', user_id: User.first.id, extension_id: 12 },
  { id: '205', name: 'Pangsila', user_id: User.first.id, extension_id: 12 },
  { id: '206', name: 'Phootsha', user_id: User.first.id, extension_id: 12 },
  { id: '207', name: 'Trashigang', user_id: User.first.id, extension_id: 12 },
  { id: '208', name: 'Tshebji', user_id: User.first.id, extension_id: 12 },

  # Loggchina geog
  { id: '210', name: 'Aamleg', user_id: User.first.id, extension_id: 13 },
  { id: '211', name: 'Chagdokha ', user_id: User.first.id, extension_id: 13 },
  { id: '212', name: 'Chimongnatoed', user_id: User.first.id, extension_id: 13 },
  { id: '213', name: 'Chimongnamaed', user_id: User.first.id, extension_id: 13 },
  { id: '214', name: 'Damchhekha', user_id: User.first.id, extension_id: 13 },
  { id: '215', name: 'Dofam', user_id: User.first.id, extension_id: 13 },
  { id: '216', name: 'Dolepchen', user_id: User.first.id, extension_id: 13 },
  { id: '217', name: 'Dupanang ', user_id: User.first.id, extension_id: 13 },
  { id: '218', name: 'Bjagchhu', user_id: User.first.id, extension_id: 13 },
  { id: '219', name: 'Jedokha', user_id: User.first.id, extension_id: 13 },
  { id: '220', name: 'Pamji', user_id: User.first.id, extension_id: 13 },
  { id: '221', name: 'Rudingkha', user_id: User.first.id, extension_id: 13 },
  { id: '222', name: 'Lotokha', user_id: User.first.id, extension_id: 13 },
  { id: '223', name: 'Uezhi', user_id: User.first.id, extension_id: 13 },

  # Maedtabkha geog
  { id: '225', name: 'Uekha', user_id: User.first.id, extension_id: 14 },
  { id: '226', name: 'Gumina', user_id: User.first.id, extension_id: 14 },
  { id: '227', name: 'Lotokha', user_id: User.first.id, extension_id: 14 },
  { id: '228', name: 'Maedtap Gonpa', user_id: User.first.id, extension_id: 14 },
  { id: '229', name: 'Pangu', user_id: User.first.id, extension_id: 14 },
  { id: '230', name: 'Papaling', user_id: User.first.id, extension_id: 14 },

  # Samphelling (Bhalujora) geog
  { id: '114', name: 'Tsho-Chhoongna(Ahalay)', user_id: User.first.id, extension_id: 15 },
  { id: '115', name: 'Rigzinling(Behitar)', user_id: User.first.id, extension_id: 15 },
  { id: '116', name: 'Khatoedb(Burkey)', user_id: User.first.id, extension_id: 15 },
  { id: '117', name: 'Thongling (Daragoan)', user_id: User.first.id, extension_id: 15 },
  { id: '118', name: 'Dorophu(Dhungayna)', user_id: User.first.id, extension_id: 15 },
  { id: '119', name: 'Dungkarling (Ghumauney)', user_id: User.first.id, extension_id: 15 },
  { id: '120', name: 'Phurpaling(Gurung Dara)', user_id: User.first.id, extension_id: 15 },
  { id: '121', name: 'Khenpaithang (Khaibatar)', user_id: User.first.id, extension_id: 15 },
  { id: '122', name: 'Sonamthang (Kothiline)', user_id: User.first.id, extension_id: 15 },
  { id: '123', name: 'Karmaling (Malbasay)', user_id: User.first.id, extension_id: 15 },
  { id: '124', name: 'Pedtshel-Nang(Pakchin)', user_id: User.first.id, extension_id: 15 },
  { id: '125', name: 'Pangnatoed (Pana A', user_id: User.first.id, extension_id: 15 },
  { id: '126', name: 'Pangna Maed(Pana B)', user_id: User.first.id, extension_id: 15 },
  { id: '127', name: 'Pangnabar (Pana C)', user_id: User.first.id, extension_id: 15 },
  { id: '128', name: 'Pekarling (Pekasey)', user_id: User.first.id, extension_id: 15 },
  { id: '129', name: 'Bamenmo(Ragaytung)', user_id: User.first.id, extension_id: 15 },
  { id: '130', name: 'Sengyegang(Singi)', user_id: User.first.id, extension_id: 15 },

  # Phuentsholing Gewog
  { id: '232', name: 'Dophuchen(Ahalay)', user_id: User.first.id, extension_id: 16 },
  { id: '233', name: 'Pachhuthang (Pachu Tar)', user_id: User.first.id, extension_id: 16 },
  { id: '234', name: 'Bosokha', user_id: User.first.id, extension_id: 16 },
  { id: '235', name: 'Marpji (Chilauney)', user_id: User.first.id, extension_id: 16 },
  { id: '236', name: 'Deling ', user_id: User.first.id, extension_id: 16 },
  { id: '237', name: 'Chong-Geykha', user_id: User.first.id, extension_id: 16 },
  { id: '238', name: 'Chong- Geykha Toed', user_id: User.first.id, extension_id: 16 },
  { id: '239', name: 'Chong- Geykha Maed', user_id: User.first.id, extension_id: 16 },
  { id: '240', name: 'Darjaygang', user_id: User.first.id, extension_id: 16 },
  { id: '241', name: 'Nyedrag(Dhamdara)', user_id: User.first.id, extension_id: 16 },
  { id: '242', name: 'Dophulakha', user_id: User.first.id, extension_id: 16 },
  { id: '243', name: 'Kungkha', user_id: User.first.id, extension_id: 16 },
  { id: '244', name: 'Lingdaen', user_id: User.first.id, extension_id: 16 },
  { id: '245', name: 'Pachhudrag (Pachu Dara)', user_id: User.first.id, extension_id: 16 },
  { id: '246', name: 'Pachhugang (Balden Dara)', user_id: User.first.id, extension_id: 16 },
  { id: '247', name: 'Phuntsholing', user_id: User.first.id, extension_id: 16 },
  { id: '248', name: 'Phuntsholing Town', user_id: User.first.id, extension_id: 16 },
  { id: '249', name: 'Wangdue Gatshel(Ramitay)', user_id: User.first.id, extension_id: 16 },
  { id: '250', name: 'Gangteng (Serina)', user_id: User.first.id, extension_id: 16 },
  { id: '251', name: 'Tashidingkha', user_id: User.first.id, extension_id: 16 },
  { id: '252', name: 'Pekarzhing (Toribari)', user_id: User.first.id, extension_id: 16 },

  # Phuentsholing Thromde
  { id: '254', name: 'Ahalay', user_id: User.first.id, extension_id: 222 },
  { id: '255', name: 'Damdara', user_id: User.first.id, extension_id: 222 },
  { id: '256', name: 'Gurung Dara', user_id: User.first.id, extension_id: 222 },
  { id: '257', name: 'Malbasay', user_id: User.first.id, extension_id: 222 },
  { id: '258', name: 'Singi', user_id: User.first.id, extension_id: 222 },
  { id: '259', name: 'Phuntsholing Throm', user_id: User.first.id, extension_id: 222 },
  { id: '260', name: 'Toribari', user_id: User.first.id, extension_id: 222 }
].each do |v|
  Village.find_or_create_by!(v)
end
