# frozen_string_literal: true

puts 'Seeding villages of Haa...'

[
  # Bji
  { id: '474', name: 'Tsenka', user_id: User.first.id, extension_id: 37 },
  { id: '475', name: 'Tsenkagoenpa', user_id: User.first.id, extension_id: 37 },
  { id: '476', name: 'Chenpa', user_id: User.first.id, extension_id: 37 },
  { id: '477', name: 'Chhubarna', user_id: User.first.id, extension_id: 37 },
  { id: '478', name: 'Choomgpa', user_id: User.first.id, extension_id: 37 },
  { id: '479', name: 'Dangsana', user_id: User.first.id, extension_id: 37 },
  { id: '480', name: 'Gangkha', user_id: User.first.id, extension_id: 37 },
  { id: '481', name: 'Geychhukha', user_id: User.first.id, extension_id: 37 },
  { id: '482', name: 'Gongkha', user_id: User.first.id, extension_id: 37 },
  { id: '483', name: 'Gensa', user_id: User.first.id, extension_id: 37 },
  { id: '484', name: 'Jamgoen', user_id: User.first.id, extension_id: 37 },
  { id: '485', name: 'Kajena', user_id: User.first.id, extension_id: 37 },
  { id: '486', name: 'Longlong', user_id: User.first.id, extension_id: 37 },
  { id: '487', name: 'Machena', user_id: User.first.id, extension_id: 37 },
  { id: '488', name: 'Makhana', user_id: User.first.id, extension_id: 37 },
  { id: '489', name: 'Naktshang', user_id: User.first.id, extension_id: 37 },
  { id: '490', name: 'Pangphu', user_id: User.first.id, extension_id: 37 },
  { id: '491', name: 'Tengchugoenpa', user_id: User.first.id, extension_id: 37 },
  { id: '492', name: 'Tokey', user_id: User.first.id, extension_id: 37 },
  { id: '493', name: 'Wogka', user_id: User.first.id, extension_id: 37 },
  { id: '494', name: 'Yangoen', user_id: User.first.id, extension_id: 37 },
  { id: '495', name: 'Yangthang', user_id: User.first.id, extension_id: 37 },
  { id: '496', name: 'Yetshephu', user_id: User.first.id, extension_id: 37 },
  { id: '497', name: 'Yulgang', user_id: User.first.id, extension_id: 37 },

  # Uesu
  { id: '499', name: 'Baltsha', user_id: User.first.id, extension_id: 38 },
  { id: '500', name: 'Bangyena', user_id: User.first.id, extension_id: 38 },
  { id: '501', name: 'Beltsha', user_id: User.first.id, extension_id: 38 },
  { id: '502', name: 'Dranggoen', user_id: User.first.id, extension_id: 38 },
  { id: '503', name: 'Doomchhog', user_id: User.first.id, extension_id: 38 },
  { id: '504', name: 'Gaydena', user_id: User.first.id, extension_id: 38 },
  { id: '505', name: 'Goensakha', user_id: User.first.id, extension_id: 38 },
  { id: '506', name: 'Hagoenpa', user_id: User.first.id, extension_id: 38 },
  { id: '507', name: 'Karnag', user_id: User.first.id, extension_id: 38 },
  { id: '508', name: 'Kipri', user_id: User.first.id, extension_id: 38 },
  { id: '509', name: 'Pagekha', user_id: User.first.id, extension_id: 38 },
  { id: '510', name: 'Sangkari', user_id: User.first.id, extension_id: 38 },
  { id: '511', name: 'Tagchhu', user_id: User.first.id, extension_id: 38 },
  { id: '512', name: 'Takchugoenpa', user_id: User.first.id, extension_id: 38 },
  { id: '513', name: 'Tshaphel', user_id: User.first.id, extension_id: 38 },
  { id: '514', name: 'Tshelungkha', user_id: User.first.id, extension_id: 38 },

  # Gakiling
  { id: '571', name: 'Rangtse', user_id: User.first.id, extension_id: 39 },
  { id: '572', name: 'Yokha', user_id: User.first.id, extension_id: 39 },
  { id: '573', name: 'Ta-nga/Chigo', user_id: User.first.id, extension_id: 39 },
  { id: '574', name: 'Phootsena', user_id: User.first.id, extension_id: 39 },
  { id: '575', name: 'Ngatse', user_id: User.first.id, extension_id: 39 },
  { id: '576', name: 'Thangdokha', user_id: User.first.id, extension_id: 39 },
  { id: '577', name: 'Sai-dzong', user_id: User.first.id, extension_id: 39 },
  { id: '578', name: 'Dorithasa', user_id: User.first.id, extension_id: 39 },
  { id: '579', name: 'Gorima', user_id: User.first.id, extension_id: 39 },
  { id: '580', name: 'Yangtse', user_id: User.first.id, extension_id: 39 },
  { id: '581', name: 'Kowkha', user_id: User.first.id, extension_id: 39 },
  { id: '582', name: 'Sertena', user_id: User.first.id, extension_id: 39 },
  { id: '583', name: 'Fetena', user_id: User.first.id, extension_id: 39 },

  # Kar-tshog
  { id: '516', name: 'Bali', user_id: User.first.id, extension_id: 40 },
  { id: '517', name: 'Dragding', user_id: User.first.id, extension_id: 40 },
  { id: '518', name: 'Gangkha', user_id: User.first.id, extension_id: 40 },
  { id: '519', name: 'Haa Throm', user_id: User.first.id, extension_id: 40 },
  { id: '520', name: 'In-go', user_id: User.first.id, extension_id: 40 },
  { id: '521', name: 'Junidra', user_id: User.first.id, extension_id: 40 },
  { id: '522', name: 'Karjena', user_id: User.first.id, extension_id: 40 },
  { id: '523', name: 'Kargoen', user_id: User.first.id, extension_id: 40 },
  { id: '524', name: 'Lhayulkha', user_id: User.first.id, extension_id: 40 },
  { id: '525', name: 'Mombitshokha', user_id: User.first.id, extension_id: 40 },
  { id: '526', name: 'Nagtshang', user_id: User.first.id, extension_id: 40 },
  { id: '527', name: 'Namchhu', user_id: User.first.id, extension_id: 40 },
  { id: '528', name: 'Pharikha', user_id: User.first.id, extension_id: 40 },
  { id: '529', name: 'Wangtsa', user_id: User.first.id, extension_id: 40 },
  { id: '530', name: 'Hatam', user_id: User.first.id, extension_id: 40 },

  # Samar
  { id: '532', name: 'Balamnang', user_id: User.first.id, extension_id: 41 },
  { id: '533', name: 'Barakha', user_id: User.first.id, extension_id: 41 },
  { id: '534', name: 'Barasham', user_id: User.first.id, extension_id: 41 },
  { id: '535', name: 'Borakha', user_id: User.first.id, extension_id: 41 },
  { id: '536', name: 'Pudunang', user_id: User.first.id, extension_id: 41 },
  { id: '537', name: 'Chhumeyding', user_id: User.first.id, extension_id: 41 },
  { id: '538', name: 'Dorikha', user_id: User.first.id, extension_id: 41 },
  { id: '539', name: 'Dorithasa', user_id: User.first.id, extension_id: 41 },
  { id: '540', name: 'Gangrim', user_id: User.first.id, extension_id: 41 },
  { id: '541', name: 'Jenkanang', user_id: User.first.id, extension_id: 41 },
  { id: '542', name: 'Kona', user_id: User.first.id, extension_id: 41 },
  { id: '543', name: 'Langjogang', user_id: User.first.id, extension_id: 41 },
  { id: '544', name: 'Langpa', user_id: User.first.id, extension_id: 41 },
  { id: '545', name: 'Lhakhangchen', user_id: User.first.id, extension_id: 41 },
  { id: '546', name: 'Medana', user_id: User.first.id, extension_id: 41 },
  { id: '547', name: 'Norbugang', user_id: User.first.id, extension_id: 41 },
  { id: '548', name: 'Puduna', user_id: User.first.id, extension_id: 41 },
  { id: '549', name: 'Shari', user_id: User.first.id, extension_id: 41 },

  # Sangbay
  { id: '551', name: 'Ama', user_id: User.first.id, extension_id: 42 },
  { id: '552', name: 'Tsanglingna', user_id: User.first.id, extension_id: 42 },
  { id: '553', name: 'Gyeldrakha', user_id: User.first.id, extension_id: 42 },
  { id: '554', name: 'Mochhu', user_id: User.first.id, extension_id: 42 },
  { id: '555', name: 'Mochu Wookha', user_id: User.first.id, extension_id: 42 },
  { id: '556', name: 'Nakha', user_id: User.first.id, extension_id: 42 },
  { id: '557', name: 'Nakhatshochhen', user_id: User.first.id, extension_id: 42 },
  { id: '558', name: 'Nakhekha', user_id: User.first.id, extension_id: 42 },
  { id: '559', name: 'Shaba', user_id: User.first.id, extension_id: 42 },
  { id: '560', name: 'Shepji', user_id: User.first.id, extension_id: 42 },
  { id: '561', name: 'Tingma', user_id: User.first.id, extension_id: 42 },
  { id: '562', name: 'Tashigang', user_id: User.first.id, extension_id: 42 },
  { id: '563', name: 'Tshochen', user_id: User.first.id, extension_id: 42 },
  { id: '564', name: 'Yangtse', user_id: User.first.id, extension_id: 42 },
  { id: '565', name: 'Yaba', user_id: User.first.id, extension_id: 42 },
  { id: '566', name: 'Shelma', user_id: User.first.id, extension_id: 42 },
  { id: '567', name: 'Bibi', user_id: User.first.id, extension_id: 42 },
  { id: '568', name: 'Dongtse', user_id: User.first.id, extension_id: 42 },
  { id: '569', name: 'Chinga', user_id: User.first.id, extension_id: 42 },
  { id: '4702', name: 'Darjaygang', user_id: User.first.id, extension_id: 42 },
  { id: '4703', name: 'Zomtokha', user_id: User.first.id, extension_id: 42 },
  { id: '4704', name: 'Kharkha', user_id: User.first.id, extension_id: 42 },
  { id: '4705', name: 'Debjay', user_id: User.first.id, extension_id: 42 },
  { id: '4706', name: 'Bebjay', user_id: User.first.id, extension_id: 42 },

  # Haa Thromde
  { id: '4724', name: 'Throm', user_id: User.first.id, extension_id: 43 }
].each do |v|
  Village.find_or_create_by!(v)
end
