# frozen_string_literal: true

[
  # Tsaenkhar
  { id: '893', name: 'Yangloong', user_id: User.first.id, extension_id: 51 },
  { id: '892', name: 'Yangla', user_id: User.first.id, extension_id: 51 },
  { id: '891', name: 'Wambur', user_id: User.first.id, extension_id: 51 },
  { id: '890', name: 'Umling', user_id: User.first.id, extension_id: 51 },
  { id: '889', name: 'Tsholadrang', user_id: User.first.id, extension_id: 51 },
  { id: '888', name: 'Tshochhim', user_id: User.first.id, extension_id: 51 },
  { id: '887', name: 'Tshochhen', user_id: User.first.id, extension_id: 51 },
  { id: '886', name: 'Tsaenkhar', user_id: User.first.id, extension_id: 51 },
  { id: '885', name: 'Tshangphu', user_id: User.first.id, extension_id: 51 },
  { id: '884', name: 'Trangka Shing', user_id: User.first.id, extension_id: 51 },
  { id: '883', name: 'Tongshelung', user_id: User.first.id, extension_id: 51 },
  { id: '882', name: 'Tongphugang', user_id: User.first.id, extension_id: 51 },
  { id: '881', name: 'Toedkhar', user_id: User.first.id, extension_id: 51 },
  { id: '880', name: 'Thongshinglung', user_id: User.first.id, extension_id: 51 },
  { id: '879', name: 'Tashiling', user_id: User.first.id, extension_id: 51 },
  { id: '878', name: 'Tarka Shing', user_id: User.first.id, extension_id: 51 },
  { id: '877', name: 'Takchhu', user_id: User.first.id, extension_id: 51 },
  { id: '876', name: 'Sogchen', user_id: User.first.id, extension_id: 51 },
  { id: '875', name: 'Sokarom', user_id: User.first.id, extension_id: 51 },
  { id: '874', name: 'Shermachhu Goenpa', user_id: User.first.id, extension_id: 51 },
  { id: '873', name: 'Shermachhu', user_id: User.first.id, extension_id: 51 },
  { id: '872', name: 'Sangphu', user_id: User.first.id, extension_id: 51 },
  { id: '871', name: 'Phoorshonggang', user_id: User.first.id, extension_id: 51 },
  { id: '870', name: 'Phuentshogchhoeling', user_id: User.first.id, extension_id: 51 },
  { id: '869', name: 'Phowantay', user_id: User.first.id, extension_id: 51 },
  { id: '868', name: 'Phomed-doong', user_id: User.first.id, extension_id: 51 },
  { id: '867', name: 'Peldraphu', user_id: User.first.id, extension_id: 51 },
  { id: '866', name: 'Ngathong', user_id: User.first.id, extension_id: 51 },
  { id: '865', name: 'Lawsa', user_id: User.first.id, extension_id: 51 },
  { id: '864', name: 'Langabi', user_id: User.first.id, extension_id: 51 },
  { id: '863', name: 'Lagael', user_id: User.first.id, extension_id: 51 },
  { id: '862', name: 'Kiphung', user_id: User.first.id, extension_id: 51 },
  { id: '861', name: 'Kharphu', user_id: User.first.id, extension_id: 51 },
  { id: '860', name: 'Khablang', user_id: User.first.id, extension_id: 51 },
  { id: '859', name: 'Kewachen', user_id: User.first.id, extension_id: 51 },
  { id: '858', name: 'Jarkhang', user_id: User.first.id, extension_id: 51 },
  { id: '857', name: 'Guengdrang', user_id: User.first.id, extension_id: 51 },
  { id: '856', name: 'Go-Nyid', user_id: User.first.id, extension_id: 51 },
  { id: '855', name: 'Godoong/Gordon', user_id: User.first.id, extension_id: 51 },
  { id: '854', name: 'Genchhungla', user_id: User.first.id, extension_id: 51 },
  { id: '853', name: 'Gamanang', user_id: User.first.id, extension_id: 51 },
  { id: '852', name: 'Dongthrom', user_id: User.first.id, extension_id: 51 },
  { id: '851', name: 'Dongling', user_id: User.first.id, extension_id: 51 },
  { id: '850', name: 'Domkhar', user_id: User.first.id, extension_id: 51 },
  { id: '849', name: 'Dekaling', user_id: User.first.id, extension_id: 51 },
  { id: '848', name: 'Dagarthang', user_id: User.first.id, extension_id: 51 },
  { id: '847', name: 'Chungkha', user_id: User.first.id, extension_id: 51 },
  { id: '846', name: 'Chhuloong', user_id: User.first.id, extension_id: 51 },
  { id: '845', name: 'Chhawa', user_id: User.first.id, extension_id: 51 },
  { id: '844', name: 'Chhimgong', user_id: User.first.id, extension_id: 51 },
  { id: '843', name: 'Changmadoong', user_id: User.first.id, extension_id: 51 },
  { id: '842', name: 'Chhangchhang Goenpa', user_id: User.first.id, extension_id: 51 },
  { id: '841', name: 'Chharbi', user_id: User.first.id, extension_id: 51 },
  { id: '840', name: 'Barchhu', user_id: User.first.id, extension_id: 51 },
  { id: '839', name: 'Bangtsho', user_id: User.first.id, extension_id: 51 },
  { id: '838', name: 'Autsho', user_id: User.first.id, extension_id: 51 },

  # Lhuentse Thromde
  { id: '894', name: 'Lhuentse Throm', user_id: User.first.id, extension_id: 52 }
].each do |v|
  Village.find_or_create_by!(v)
end
