# frozen_string_literal: true

[
  # Maenbi
  { id: '771', name: 'Zhungkhar', user_id: User.first.id, extension_id: 48 },
  { id: '770', name: 'DzarthangGoenpa', user_id: User.first.id, extension_id: 48 },
  { id: '769', name: 'Dzarthang', user_id: User.first.id, extension_id: 48 },
  { id: '768', name: 'Yoongshingphel', user_id: User.first.id, extension_id: 48 },
  { id: '766', name: 'Yomaed', user_id: User.first.id, extension_id: 48 },
  { id: '765', name: 'Yanglagoenpa', user_id: User.first.id, extension_id: 48 },
  { id: '764', name: 'Toongkhar', user_id: User.first.id, extension_id: 48 },
  { id: '763', name: 'Tshamdemo', user_id: User.first.id, extension_id: 48 },
  { id: '762', name: 'Tongmakhar', user_id: User.first.id, extension_id: 48 },
  { id: '761', name: 'Thongjaling', user_id: User.first.id, extension_id: 48 },
  { id: '760', name: 'Tekchhoeling', user_id: User.first.id, extension_id: 48 },
  { id: '759', name: 'Tashiling', user_id: User.first.id, extension_id: 48 },
  { id: '758', name: 'Tangpa', user_id: User.first.id, extension_id: 48 },
  { id: '757', name: 'Tagmochhu', user_id: User.first.id, extension_id: 48 },
  { id: '756', name: 'Takayla', user_id: User.first.id, extension_id: 48 },
  { id: '755', name: 'Shormaed', user_id: User.first.id, extension_id: 48 },
  { id: '754', name: 'Shangrabi', user_id: User.first.id, extension_id: 48 },
  { id: '753', name: 'Sershingbi', user_id: User.first.id, extension_id: 48 },
  { id: '752', name: 'Samling', user_id: User.first.id, extension_id: 48 },
  { id: '751', name: 'Samchhoeling', user_id: User.first.id, extension_id: 48 },
  { id: '750', name: 'Rewaling', user_id: User.first.id, extension_id: 48 },
  { id: '749', name: 'Rawabi Goenpa', user_id: User.first.id, extension_id: 48 },
  { id: '748', name: 'Rawabi', user_id: User.first.id, extension_id: 48 },
  { id: '747', name: 'Phoongshingang', user_id: User.first.id, extension_id: 48 },
  { id: '746', name: 'Phagidoong', user_id: User.first.id, extension_id: 48 },
  { id: '745', name: 'Petsezor', user_id: User.first.id, extension_id: 48 },
  { id: '744', name: 'Pelrigoenpa', user_id: User.first.id, extension_id: 48 },
  { id: '743', name: 'Pangsar', user_id: User.first.id, extension_id: 48 },
  { id: '742', name: 'Oumzor', user_id: User.first.id, extension_id: 48 },
  { id: '741', name: 'Neybi', user_id: User.first.id, extension_id: 48 },
  { id: '740', name: 'Ngamaling', user_id: User.first.id, extension_id: 48 },
  { id: '739', name: 'Namnangbi', user_id: User.first.id, extension_id: 48 },
  { id: '738', name: 'Namdang', user_id: User.first.id, extension_id: 48 },
  { id: '737', name: 'Nadrang', user_id: User.first.id, extension_id: 48 },
  { id: '736', name: 'Mormo', user_id: User.first.id, extension_id: 48 },
  { id: '735', name: 'Maenjabi', user_id: User.first.id, extension_id: 48 },
  { id: '734', name: 'Manigang', user_id: User.first.id, extension_id: 48 },
  { id: '733', name: 'Lugarpang', user_id: User.first.id, extension_id: 48 },
  { id: '732', name: 'Lekpagang', user_id: User.first.id, extension_id: 48 },
  { id: '731', name: 'Ledong', user_id: User.first.id, extension_id: 48 },
  { id: '730', name: 'Larjab', user_id: User.first.id, extension_id: 48 },
  { id: '729', name: 'Langphog', user_id: User.first.id, extension_id: 48 },
  { id: '728', name: 'Kusoompheb', user_id: User.first.id, extension_id: 48 },
  { id: '727', name: 'Kimphay', user_id: User.first.id, extension_id: 48 },
  { id: '726', name: 'Khochen', user_id: User.first.id, extension_id: 48 },
  { id: '725', name: 'Khashaling', user_id: User.first.id, extension_id: 48 },
  { id: '724', name: 'Kharsa', user_id: User.first.id, extension_id: 48 },
  { id: '723', name: 'Khampaling', user_id: User.first.id, extension_id: 48 },
  { id: '722', name: 'Kamdhar', user_id: User.first.id, extension_id: 48 },
  { id: '721', name: 'Katog', user_id: User.first.id, extension_id: 48 },
  { id: '720', name: 'Kasilthang', user_id: User.first.id, extension_id: 48 },
  { id: '719', name: 'Gorgan', user_id: User.first.id, extension_id: 48 },
  { id: '718', name: 'Garabphu', user_id: User.first.id, extension_id: 48 },
  { id: '717', name: 'Gangkhar', user_id: User.first.id, extension_id: 48 },
  { id: '716', name: 'Gamzhing', user_id: User.first.id, extension_id: 48 },
  { id: '715', name: 'Dungkardowa', user_id: User.first.id, extension_id: 48 },
  { id: '714', name: 'Dromzhong', user_id: User.first.id, extension_id: 48 },
  { id: '713', name: 'Dosagang', user_id: User.first.id, extension_id: 48 },
  { id: '712', name: 'Dzarthang Goenpa', user_id: User.first.id, extension_id: 48 },
  { id: '711', name: 'Dangsang Goenpa', user_id: User.first.id, extension_id: 48 },
  { id: '710 ', name: 'Daangling ', user_id: User.first.id, extension_id: 48 },
  { id: '709', name: 'Chhalibi', user_id: User.first.id, extension_id: 48 },
  { id: '708', name: 'Chengaling', user_id: User.first.id, extension_id: 48 },
  { id: '707', name: 'Boompazhing', user_id: User.first.id, extension_id: 48 },
  { id: '706', name: 'Boushong', user_id: User.first.id, extension_id: 48 },
  { id: '705', name: 'Bariphu', user_id: User.first.id, extension_id: 48 },
  { id: '704', name: 'Bamendrangsa', user_id: User.first.id, extension_id: 48 },
  { id: '767', name: 'Yongrab', user_id: User.first.id, extension_id: 48 },
  { id: '772', name: 'Zhungphu', user_id: User.first.id, extension_id: 48 },

  # Maedtsho
  { id: '836', name: 'Zhongmaed', user_id: User.first.id, extension_id: 49 },
  { id: '835', name: 'Yurung', user_id: User.first.id, extension_id: 49 },
  { id: '834', name: 'Yokpaling', user_id: User.first.id, extension_id: 49 },
  { id: '833', name: 'Yoezer Goenpa', user_id: User.first.id, extension_id: 49 },
  { id: '832', name: 'Yamaloong Goenpa', user_id: User.first.id, extension_id: 49 },
  { id: '831', name: 'Yamaloong', user_id: User.first.id, extension_id: 49 },
  { id: '830', name: 'Waney', user_id: User.first.id, extension_id: 49 },
  { id: '829', name: 'Tshogdrang', user_id: User.first.id, extension_id: 49 },
  { id: '828', name: 'Tshochen', user_id: User.first.id, extension_id: 49 },
  { id: '827', name: 'Tonzigbi', user_id: User.first.id, extension_id: 49 },
  { id: '826', name: 'Tongthrong', user_id: User.first.id, extension_id: 49 },
  { id: '825', name: 'Tongthrom', user_id: User.first.id, extension_id: 49 },
  { id: '824', name: 'Tagchhoong', user_id: User.first.id, extension_id: 49 },
  { id: '823', name: 'Singyebi', user_id: User.first.id, extension_id: 49 },
  { id: '822', name: 'Serbuchhuka', user_id: User.first.id, extension_id: 49 },
  { id: '821', name: 'Samdang', user_id: User.first.id, extension_id: 49 },
  { id: '820', name: 'Pholhadowa', user_id: User.first.id, extension_id: 49 },
  { id: '819', name: 'Pangzhingmaed', user_id: User.first.id, extension_id: 49 },
  { id: '818', name: 'Oong-gar', user_id: User.first.id, extension_id: 49 },
  { id: '817', name: 'Obi', user_id: User.first.id, extension_id: 49 },
  { id: '816', name: 'Moogpakhar', user_id: User.first.id, extension_id: 49 },
  { id: '815', name: 'Mangdhir', user_id: User.first.id, extension_id: 49 },
  { id: '814', name: 'Lhakhangtshawa', user_id: User.first.id, extension_id: 49 },
  { id: '813', name: 'Khi-nyel Lhakhang', user_id: User.first.id, extension_id: 49 },
  { id: '812', name: 'Kermademo', user_id: User.first.id, extension_id: 49 },
  { id: '811', name: 'Janagchen', user_id: User.first.id, extension_id: 49 },
  { id: '810', name: 'Goolipang', user_id: User.first.id, extension_id: 49 },
  { id: '809', name: 'Gortshom', user_id: User.first.id, extension_id: 49 },
  { id: '808', name: 'Gongdar', user_id: User.first.id, extension_id: 49 },
  { id: '807', name: 'Dulebi', user_id: User.first.id, extension_id: 49 },
  { id: '806', name: 'Drukla', user_id: User.first.id, extension_id: 49 },
  { id: '805', name: 'Dowalithang', user_id: User.first.id, extension_id: 49 },
  { id: '804', name: 'Tshangthrom Maed Goenpa', user_id: User.first.id, extension_id: 49 },
  { id: '803', name: 'Tshangthrom Maed', user_id: User.first.id, extension_id: 49 },
  { id: '802', name: 'Changshinpokpa', user_id: User.first.id, extension_id: 49 },
  { id: '801', name: 'Changchen', user_id: User.first.id, extension_id: 49 },
  { id: '800', name: 'Bamdhir', user_id: User.first.id, extension_id: 49 },
  { id: '799', name: 'Balam/Nyimalawa', user_id: User.first.id, extension_id: 49 },
  { id: '798', name: 'Balam', user_id: User.first.id, extension_id: 49 },

  # Minjey
  { id: '796', name: 'Zham', user_id: User.first.id, extension_id: 50 },
  { id: '795', name: 'Wangzhing', user_id: User.first.id, extension_id: 50 },
  { id: '794', name: 'Tongling', user_id: User.first.id, extension_id: 50 },
  { id: '793', name: 'Sershing', user_id: User.first.id, extension_id: 50 },
  { id: '792', name: 'Pumogang', user_id: User.first.id, extension_id: 50 },
  { id: '791', name: 'Phangchenbi', user_id: User.first.id, extension_id: 50 },
  { id: '790', name: 'Nyaka', user_id: User.first.id, extension_id: 50 },
  { id: '789', name: 'Menji', user_id: User.first.id, extension_id: 50 },
  { id: '788', name: 'Legshogang', user_id: User.first.id, extension_id: 50 },
  { id: '787', name: 'Legpachhu', user_id: User.first.id, extension_id: 50 },
  { id: '786', name: 'Legchhugang', user_id: User.first.id, extension_id: 50 },
  { id: '785', name: 'Kupi-nyalsa', user_id: User.first.id, extension_id: 50 },
  { id: '784', name: 'Kero', user_id: User.first.id, extension_id: 50 },
  { id: '783', name: 'Jalang', user_id: User.first.id, extension_id: 50 },
  { id: '782', name: 'Jaboom', user_id: User.first.id, extension_id: 50 },
  { id: '781', name: 'Draglidowa', user_id: User.first.id, extension_id: 50 },
  { id: '780', name: 'Draag-gong Goenpa', user_id: User.first.id, extension_id: 50 },
  { id: '779', name: 'Draag-gong', user_id: User.first.id, extension_id: 50 },
  { id: '778', name: 'Dokpabi', user_id: User.first.id, extension_id: 50 },
  { id: '777', name: 'Chusa', user_id: User.first.id, extension_id: 50 },
  { id: '776', name: 'Chengling', user_id: User.first.id, extension_id: 50 },
  { id: '775', name: 'Boo-dur', user_id: User.first.id, extension_id: 50 },
  { id: '774', name: 'Amdrangchhu', user_id: User.first.id, extension_id: 50 }
].each do |v|
  Village.find_or_create_by!(v)
end
