# frozen_string_literal: true

puts 'Seeding villages of Lhuentse...'

[
  # Gangzur
  { id: '586', name: 'Amchi', user_id: User.first.id, extension_id: 44 },
  { id: '587', name: 'Changray', user_id: User.first.id, extension_id: 44 },
  { id: '588', name: 'Chhesa', user_id: User.first.id, extension_id: 44 },
  { id: '589', name: 'Dengkaling', user_id: User.first.id, extension_id: 44 },
  { id: '590', name: 'Doorthroe', user_id: User.first.id, extension_id: 44 },
  { id: '591', name: 'Gangzur', user_id: User.first.id, extension_id: 44 },
  { id: '592', name: 'Jalamzur', user_id: User.first.id, extension_id: 44 },
  { id: '593', name: 'Jang', user_id: User.first.id, extension_id: 44 },
  { id: '594', name: 'Khamphu', user_id: User.first.id, extension_id: 44 },
  { id: '595', name: 'Kyidloong', user_id: User.first.id, extension_id: 44 },
  { id: '596', name: 'Khaujoong', user_id: User.first.id, extension_id: 44 },
  { id: '597', name: 'Lekpa', user_id: User.first.id, extension_id: 44 },
  { id: '598', name: 'Lingabi', user_id: User.first.id, extension_id: 44 },
  { id: '599', name: 'Magar', user_id: User.first.id, extension_id: 44 },
  { id: '600', name: 'Namseygang', user_id: User.first.id, extension_id: 44 },
  { id: '601', name: 'Naabzala', user_id: User.first.id, extension_id: 44 },
  { id: '602', name: 'Ney', user_id: User.first.id, extension_id: 44 },
  { id: '603', name: 'Ngar', user_id: User.first.id, extension_id: 44 },
  { id: '604', name: 'Nyimzhong', user_id: User.first.id, extension_id: 44 },
  { id: '605', name: 'Nyar', user_id: User.first.id, extension_id: 44 },
  { id: '606', name: 'Phatala', user_id: User.first.id, extension_id: 44 },
  { id: '607', name: 'Rothpa', user_id: User.first.id, extension_id: 44 },
  { id: '608', name: 'Samling', user_id: User.first.id, extension_id: 44 },
  { id: '609', name: 'Sapho', user_id: User.first.id, extension_id: 44 },
  { id: '610', name: 'Shawa', user_id: User.first.id, extension_id: 44 },
  { id: '611', name: 'Shomshing', user_id: User.first.id, extension_id: 44 },
  { id: '612', name: 'Tangsa', user_id: User.first.id, extension_id: 44 },
  { id: '613', name: 'Taushing', user_id: User.first.id, extension_id: 44 },
  { id: '614', name: 'Taushinggoenpa', user_id: User.first.id, extension_id: 44 },
  { id: '615', name: 'Tagzigbar', user_id: User.first.id, extension_id: 44 },
  { id: '616', name: 'Thimyul', user_id: User.first.id, extension_id: 44 },
  { id: '617', name: 'Thrima', user_id: User.first.id, extension_id: 44 },
  { id: '618', name: 'Tongling', user_id: User.first.id, extension_id: 44 },
  { id: '619', name: 'Tsholing', user_id: User.first.id, extension_id: 44 },
  { id: '620', name: 'Youngmaling', user_id: User.first.id, extension_id: 44 },
  { id: '621', name: 'Zhamling', user_id: User.first.id, extension_id: 44 },

  # Jarey
  { id: '623', name: 'Changkhala', user_id: User.first.id, extension_id: 45 },
  { id: '624', name: 'Jarey', user_id: User.first.id, extension_id: 45 },
  { id: '625', name: 'Kharchung/Pam', user_id: User.first.id, extension_id: 45 },
  { id: '626', name: 'Ladrong', user_id: User.first.id, extension_id: 45 },
  { id: '627', name: 'Ngang-Ngae', user_id: User.first.id, extension_id: 45 },
  { id: '628', name: 'Trapashing', user_id: User.first.id, extension_id: 45 },
  { id: '629', name: 'Wayang', user_id: User.first.id, extension_id: 45 },
  { id: '630', name: 'Yabi', user_id: User.first.id, extension_id: 45 },
  { id: '631', name: 'Yumchhe', user_id: User.first.id, extension_id: 45 },

  # Khoma
  { id: '633', name: 'Babtong', user_id: User.first.id, extension_id: 46 },
  { id: '634', name: 'Berpa', user_id: User.first.id, extension_id: 46 },
  { id: '635', name: 'Dragteng', user_id: User.first.id, extension_id: 46 },
  { id: '636', name: 'Gangla', user_id: User.first.id, extension_id: 46 },
  { id: '637', name: 'Goenkhar', user_id: User.first.id, extension_id: 46 },
  { id: '638', name: 'Kemo', user_id: User.first.id, extension_id: 46 },
  { id: '639', name: 'Kemtshong', user_id: User.first.id, extension_id: 46 },
  { id: '640', name: 'Karphu', user_id: User.first.id, extension_id: 46 },
  { id: '641', name: 'Khoema', user_id: User.first.id, extension_id: 46 },
  { id: '642', name: 'Khoma', user_id: User.first.id, extension_id: 46 },
  { id: '643', name: 'Labar', user_id: User.first.id, extension_id: 46 },
  { id: '644', name: 'Lawa', user_id: User.first.id, extension_id: 46 },
  { id: '645', name: 'Lukchhu', user_id: User.first.id, extension_id: 46 },
  { id: '646', name: 'Nyalamdung', user_id: User.first.id, extension_id: 46 },
  { id: '647', name: 'Pangkhar', user_id: User.first.id, extension_id: 46 },
  { id: '648', name: 'Pengtse', user_id: User.first.id, extension_id: 46 },
  { id: '649', name: 'Rolmateng', user_id: User.first.id, extension_id: 46 },
  { id: '650', name: 'Serphu', user_id: User.first.id, extension_id: 46 },
  { id: '651', name: 'Taya', user_id: User.first.id, extension_id: 46 },
  { id: '652', name: 'Tsang-Ngo', user_id: User.first.id, extension_id: 46 },
  { id: '653', name: 'Zangkhar', user_id: User.first.id, extension_id: 46 },

  # Kurtoed
  { id: '655', name: 'Arjaling', user_id: User.first.id, extension_id: 47 },
  { id: '656', name: 'Chaktamin', user_id: User.first.id, extension_id: 47 },
  { id: '657', name: 'Chagdzom', user_id: User.first.id, extension_id: 47 },
  { id: '658', name: 'Chhaen-Yalgang', user_id: User.first.id, extension_id: 47 },
  { id: '659', name: 'Chhusa', user_id: User.first.id, extension_id: 47 },
  { id: '660', name: 'Chhongsa', user_id: User.first.id, extension_id: 47 },
  { id: '661', name: 'Chhurchhuma', user_id: User.first.id, extension_id: 47 },
  { id: '662', name: 'Darjaygang', user_id: User.first.id, extension_id: 47 },
  { id: '663', name: 'Doongmaed', user_id: User.first.id, extension_id: 47 },
  { id: '664', name: 'Drabling', user_id: User.first.id, extension_id: 47 },
  { id: '665', name: 'Dungkar', user_id: User.first.id, extension_id: 47 },
  { id: '666', name: 'Gargong', user_id: User.first.id, extension_id: 47 },
  { id: '667', name: 'Goshingpang', user_id: User.first.id, extension_id: 47 },
  { id: '668', name: 'Gurta', user_id: User.first.id, extension_id: 47 },
  { id: '669', name: 'Jangtse', user_id: User.first.id, extension_id: 47 },
  { id: '670', name: 'Jasabi', user_id: User.first.id, extension_id: 47 },
  { id: '671', name: 'Lamsaykapa', user_id: User.first.id, extension_id: 47 },
  { id: '672', name: 'Lamsabi', user_id: User.first.id, extension_id: 47 },
  { id: '673', name: 'Maenbi', user_id: User.first.id, extension_id: 47 },
  { id: '674', name: 'Nagling', user_id: User.first.id, extension_id: 47 },
  { id: '675', name: 'Nyaray', user_id: User.first.id, extension_id: 47 },
  { id: '676', name: 'Pirbee', user_id: User.first.id, extension_id: 47 },
  { id: '677', name: 'Ruling', user_id: User.first.id, extension_id: 47 },
  { id: '678', name: 'Serphu', user_id: User.first.id, extension_id: 47 },
  { id: '679', name: 'Serzhong', user_id: User.first.id, extension_id: 47 },
  { id: '680', name: 'Serbel', user_id: User.first.id, extension_id: 47 },
  { id: '681', name: 'Shangthongling', user_id: User.first.id, extension_id: 47 },
  { id: '682', name: 'Shauzhong', user_id: User.first.id, extension_id: 47 },
  { id: '683', name: 'Signar', user_id: User.first.id, extension_id: 47 },
  { id: '684', name: 'Sugpey', user_id: User.first.id, extension_id: 47 },
  { id: '685', name: 'Sumdhang', user_id: User.first.id, extension_id: 47 },
  { id: '686', name: 'Tabi', user_id: User.first.id, extension_id: 47 },
  { id: '687', name: 'Tadzong', user_id: User.first.id, extension_id: 47 },
  { id: '688', name: 'Takharmaed', user_id: User.first.id, extension_id: 47 },
  { id: '689', name: 'Tagling', user_id: User.first.id, extension_id: 47 },
  { id: '690', name: 'Tang-Roong', user_id: User.first.id, extension_id: 47 },
  { id: '691', name: 'Tergang', user_id: User.first.id, extension_id: 47 },
  { id: '692', name: 'Thangbi', user_id: User.first.id, extension_id: 47 },
  { id: '693', name: 'Thongjaling', user_id: User.first.id, extension_id: 47 },
  { id: '694', name: 'Thowa', user_id: User.first.id, extension_id: 47 },
  { id: '695', name: 'Thuenpey', user_id: User.first.id, extension_id: 47 },
  { id: '696', name: 'Tongmay', user_id: User.first.id, extension_id: 47 },
  { id: '697', name: 'Tsholing', user_id: User.first.id, extension_id: 47 },
  { id: '698', name: 'Uygenphu', user_id: User.first.id, extension_id: 47 },
  { id: '699', name: 'Wamdrang', user_id: User.first.id, extension_id: 47 },
  { id: '700', name: 'Wawel', user_id: User.first.id, extension_id: 47 },
  { id: '701', name: 'Zimpong', user_id: User.first.id, extension_id: 47 },
  { id: '702', name: 'Dzongsar', user_id: User.first.id, extension_id: 47 }
].each do |v|
  Village.find_or_create_by!(v)
end
