# frozen_string_literal: true

[
  # Ngatshang
  { id: '1303', name: 'Yadi Throm', user_id: User.first.id, extension_id: 63 },
  { id: '1302', name: 'Zangdari', user_id: User.first.id, extension_id: 63 },
  { id: '1301', name: 'Yekhar', user_id: User.first.id, extension_id: 63 },
  { id: '1300', name: 'Thoombari', user_id: User.first.id, extension_id: 63 },
  { id: '1299', name: 'Phanasi', user_id: User.first.id, extension_id: 63 },
  { id: '1298', name: 'Pelshoob', user_id: User.first.id, extension_id: 63 },
  { id: '1297', name: 'Nyingala', user_id: User.first.id, extension_id: 63 },
  { id: '1296', name: 'Ngatshang', user_id: User.first.id, extension_id: 63 },
  { id: '1295', name: 'Goenpa', user_id: User.first.id, extension_id: 63 },
  { id: '1294', name: 'Boompazor', user_id: User.first.id, extension_id: 63 },

  # Saling
  { id: '1317', name: 'Lingmethang Throm', user_id: User.first.id, extension_id: 64 },
  { id: '1316', name: 'Tshenzabi', user_id: User.first.id, extension_id: 64 },
  { id: '1315', name: 'Thridangbi', user_id: User.first.id, extension_id: 64 },
  { id: '1314', name: 'Seng-Gor', user_id: User.first.id, extension_id: 64 },
  { id: '1313', name: 'Saling', user_id: User.first.id, extension_id: 64 },
  { id: '1312', name: 'Risa', user_id: User.first.id, extension_id: 64 },
  { id: '1311', name: 'Pangsibi', user_id: User.first.id, extension_id: 64 },
  { id: '1310', name: 'Masangdaza', user_id: User.first.id, extension_id: 64 },
  { id: '1309', name: 'Kalapang', user_id: User.first.id, extension_id: 64 },
  { id: '1308', name: 'Jangdoong', user_id: User.first.id, extension_id: 64 },
  { id: '1307', name: 'Maangling', user_id: User.first.id, extension_id: 64 },
  { id: '1306', name: 'Drogsar', user_id: User.first.id, extension_id: 64 },
  { id: '1305', name: 'Bongdeyma', user_id: User.first.id, extension_id: 64 },

  # Shermuhoong
  { id: '1325', name: 'Thiling', user_id: User.first.id, extension_id: 65 },
  { id: '1324', name: 'Soenakhar', user_id: User.first.id, extension_id: 65 },
  { id: '1323', name: 'Shiling', user_id: User.first.id, extension_id: 65 },
  { id: '1322', name: 'Serzhong', user_id: User.first.id, extension_id: 65 },
  { id: '1321', name: 'Muhoong', user_id: User.first.id, extension_id: 65 },
  { id: '1320', name: 'Jabgang', user_id: User.first.id, extension_id: 65 },
  { id: '1319', name: 'Gangmoong', user_id: User.first.id, extension_id: 65 },

  # Silambi
  { id: '1354', name: 'Chang Changma', user_id: User.first.id, extension_id: 66 },
  { id: '1353', name: 'Wama', user_id: User.first.id, extension_id: 66 },
  { id: '1352', name: 'Toomdraag', user_id: User.first.id, extension_id: 66 },
  { id: '1351', name: 'Silambi/Lemigoenpa', user_id: User.first.id, extension_id: 66 },
  { id: '1350', name: 'Silambi', user_id: User.first.id, extension_id: 66 },
  { id: '1349', name: 'Salipong', user_id: User.first.id, extension_id: 66 },
  { id: '1348', name: 'Gyerteng/Phoongling', user_id: User.first.id, extension_id: 66 },
  { id: '1347', name: 'Pang Gyerteng/Goenpa', user_id: User.first.id, extension_id: 66 },
  { id: '1346', name: 'Pang Gyerteng', user_id: User.first.id, extension_id: 66 },
  { id: '1345', name: 'Pam', user_id: User.first.id, extension_id: 66 },
  { id: '1344', name: 'Nagor/Pam', user_id: User.first.id, extension_id: 66 },
  { id: '1343', name: 'Nagor Pang', user_id: User.first.id, extension_id: 66 },
  { id: '1342', name: 'Nagor Goenpa', user_id: User.first.id, extension_id: 66 },
  { id: '1341', name: 'Nagor', user_id: User.first.id, extension_id: 66 },
  { id: '1340', name: 'Laijoog', user_id: User.first.id, extension_id: 66 },
  { id: '1339', name: 'Khatoe/Silambi', user_id: User.first.id, extension_id: 66 },
  { id: '1338', name: 'Khatoed/Baribang', user_id: User.first.id, extension_id: 66 },
  { id: '1337', name: 'Khatoed', user_id: User.first.id, extension_id: 66 },
  { id: '1336', name: 'Kangkari', user_id: User.first.id, extension_id: 66 },
  { id: '1335', name: 'Kangkangma', user_id: User.first.id, extension_id: 66 },
  { id: '1334', name: 'Kadak/Salipong', user_id: User.first.id, extension_id: 66 },
  { id: '1333', name: 'Kadag', user_id: User.first.id, extension_id: 66 },
  { id: '1332', name: 'Gyalgong', user_id: User.first.id, extension_id: 66 },
  { id: '1331', name: 'Goenpa', user_id: User.first.id, extension_id: 66 },
  { id: '1330', name: 'Degdongla', user_id: User.first.id, extension_id: 66 },
  { id: '1329', name: 'Yarig', user_id: User.first.id, extension_id: 66 },
  { id: '1328', name: 'Daag', user_id: User.first.id, extension_id: 66 },
  { id: '1327', name: 'Baribang', user_id: User.first.id, extension_id: 66 },

  # Thang-Rong
  { id: '1361', name: 'Panglen', user_id: User.first.id, extension_id: 67 },
  { id: '1360', name: 'Ngaru-Pongtang', user_id: User.first.id, extension_id: 67 },
  { id: '1359', name: 'Lingkhar', user_id: User.first.id, extension_id: 67 },
  { id: '1358', name: 'Changshing Goenpa', user_id: User.first.id, extension_id: 67 },
  { id: '1357', name: 'Bauchhoeling', user_id: User.first.id, extension_id: 67 },
  { id: '1356', name: 'Atola', user_id: User.first.id, extension_id: 67 },

  # Tsakaling
  { id: '1503', name: 'Angtonyelsa', user_id: User.first.id, extension_id: 68 },
  { id: '1504', name: 'Aringtengma', user_id: User.first.id, extension_id: 68 },
  { id: '1505', name: 'Artogang', user_id: User.first.id, extension_id: 68 },
  { id: '1506', name: 'Chalagang', user_id: User.first.id, extension_id: 68 },
  { id: '1507', name: 'Chalagang/Kaling', user_id: User.first.id, extension_id: 68 },
  { id: '1508', name: 'Chalagang/Thowala', user_id: User.first.id, extension_id: 68 },
  { id: '1509', name: 'Chubar', user_id: User.first.id, extension_id: 68 },
  { id: '1510', name: 'Churtsha', user_id: User.first.id, extension_id: 68 },
  { id: '1511', name: 'Churtsha/Dokarpo', user_id: User.first.id, extension_id: 68 },
  { id: '1512', name: 'Churtsha/Lungkang', user_id: User.first.id, extension_id: 68 },
  { id: '1513', name: 'Churtsha/Tshodrang', user_id: User.first.id, extension_id: 68 },
  { id: '1514', name: 'Churtung', user_id: User.first.id, extension_id: 68 },
  { id: '1515', name: 'Damtshang Pokpa', user_id: User.first.id, extension_id: 68 },
  { id: '1516', name: 'Demungla', user_id: User.first.id, extension_id: 68 },
  { id: '1517', name: 'Dolemtang', user_id: User.first.id, extension_id: 68 },
  { id: '1518', name: 'Drangling', user_id: User.first.id, extension_id: 68 },
  { id: '1519', name: 'Drangling/Dabang', user_id: User.first.id, extension_id: 68 },
  { id: '1520', name: 'Drangling/Emalaphuk', user_id: User.first.id, extension_id: 68 },
  { id: '1521', name: 'Drangling/Gangka', user_id: User.first.id, extension_id: 68 },
  { id: '1522', name: 'Drangling/Gaptangra', user_id: User.first.id, extension_id: 68 },
  { id: '1523', name: 'Drangling/Kadamwo', user_id: User.first.id, extension_id: 68 },
  { id: '1524', name: 'Drangling/Khanakshing', user_id: User.first.id, extension_id: 68 },
  { id: '1525', name: 'Drongteymawo', user_id: User.first.id, extension_id: 68 },
  { id: '1526', name: 'Gamanang', user_id: User.first.id, extension_id: 68 },
  { id: '1527', name: 'Gamanang/Jachu', user_id: User.first.id, extension_id: 68 },
  { id: '1528', name: 'Gamanang/Lungdubi', user_id: User.first.id, extension_id: 68 },
  { id: '1529', name: 'Gendrang/Takhambi', user_id: User.first.id, extension_id: 68 },
  { id: '1530', name: 'Horong', user_id: User.first.id, extension_id: 68 },
  { id: '1531', name: 'Janglageon', user_id: User.first.id, extension_id: 68 },
  { id: '1532', name: 'Karshingang', user_id: User.first.id, extension_id: 68 },
  { id: '1533', name: 'Khanashing', user_id: User.first.id, extension_id: 68 },
  { id: '1534', name: 'Khashalbadap', user_id: User.first.id, extension_id: 68 },
  { id: '1535', name: 'Khimsang', user_id: User.first.id, extension_id: 68 },
  { id: '1536', name: 'Langabi', user_id: User.first.id, extension_id: 68 },
  { id: '1537', name: 'Lebamani', user_id: User.first.id, extension_id: 68 },
  { id: '1538', name: 'Leksinghphu', user_id: User.first.id, extension_id: 68 },
  { id: '1539', name: 'Leksinghphu/Bongring', user_id: User.first.id, extension_id: 68 },
  { id: '1540', name: 'Leksinghphu/Churtung', user_id: User.first.id, extension_id: 68 },
  { id: '1541', name: 'Leksinghphu/Doktang', user_id: User.first.id, extension_id: 68 },
  { id: '1542', name: 'Leksinghphu/Drangling', user_id: User.first.id, extension_id: 68 },
  { id: '1543', name: 'Leksinghphu/Kadam', user_id: User.first.id, extension_id: 68 },
  { id: '1544', name: 'Leksinghphu/Thongwang', user_id: User.first.id, extension_id: 68 },
  { id: '1545', name: 'Leyjabi', user_id: User.first.id, extension_id: 68 },
  { id: '1546', name: 'Lhadrang', user_id: User.first.id, extension_id: 68 },
  { id: '1547', name: 'Lungdubi', user_id: User.first.id, extension_id: 68 },
  { id: '1548', name: 'Naktshang', user_id: User.first.id, extension_id: 68 },
  { id: '1549', name: 'Norbugang', user_id: User.first.id, extension_id: 68 },
  { id: '1550', name: 'Norbugang/Chutey', user_id: User.first.id, extension_id: 68 },
  { id: '1551', name: 'Norbugang/Dolaptang', user_id: User.first.id, extension_id: 68 },
  { id: '1552', name: 'Norbugang/Domula', user_id: User.first.id, extension_id: 68 },
  { id: '1553', name: 'Norbugang/Khashagang', user_id: User.first.id, extension_id: 68 },
  { id: '1554', name: 'Norbugang/Thodamla', user_id: User.first.id, extension_id: 68 },
  { id: '1555', name: 'Norbugang/Threwatong', user_id: User.first.id, extension_id: 68 },
  { id: '1556', name: 'Norbugang/Yartogang', user_id: User.first.id, extension_id: 68 },
  { id: '1557', name: 'Nyertshi', user_id: User.first.id, extension_id: 68 },
  { id: '1558', name: 'Nyertshi/Shabum', user_id: User.first.id, extension_id: 68 },
  { id: '1559', name: 'Nyertshi/Singma Nangka', user_id: User.first.id, extension_id: 68 },
  { id: '1560', name: 'Nyertshi/Tsema Nangka', user_id: User.first.id, extension_id: 68 },
  { id: '1561', name: 'Pang', user_id: User.first.id, extension_id: 68 },
  { id: '1562', name: 'Pangtshela', user_id: User.first.id, extension_id: 68 },
  { id: '1563', name: 'Perpobadap', user_id: User.first.id, extension_id: 68 },
  { id: '1564', name: 'Pongtshong', user_id: User.first.id, extension_id: 68 },
  { id: '1565', name: 'Pongtshong/Balamchungku', user_id: User.first.id, extension_id: 68 },
  { id: '1566', name: 'Pongtshong/Rababi', user_id: User.first.id, extension_id: 68 },
  { id: '1567', name: 'Pongtshongbi', user_id: User.first.id, extension_id: 68 },
  { id: '1568', name: 'Sewla Lhakhang', user_id: User.first.id, extension_id: 68 },
  { id: '1569', name: 'Shingmar Pokpa', user_id: User.first.id, extension_id: 68 },
  { id: '1570', name: 'Sowangtey', user_id: User.first.id, extension_id: 68 },
  { id: '1571', name: 'Takhambi', user_id: User.first.id, extension_id: 68 },
  { id: '1572', name: 'Takhambi Norbugang', user_id: User.first.id, extension_id: 68 },
  { id: '1573', name: 'Takhambi/Barnang', user_id: User.first.id, extension_id: 68 },
  { id: '1574', name: 'Takhambi/Chimsaning', user_id: User.first.id, extension_id: 68 },
  { id: '1575', name: 'Takhambi/Dekiling', user_id: User.first.id, extension_id: 68 },
  { id: '1576', name: 'Takhambi/Gangka', user_id: User.first.id, extension_id: 68 },
  { id: '1577', name: 'Takhambi/Khobum', user_id: User.first.id, extension_id: 68 },
  { id: '1578', name: 'Takhambi/Khomdangchu', user_id: User.first.id, extension_id: 68 },
  { id: '1579', name: 'Takhambi/Kingacholing', user_id: User.first.id, extension_id: 68 },
  { id: '1580', name: 'Takhambi/Pang', user_id: User.first.id, extension_id: 68 },
  { id: '1581', name: 'Takhambi/Wadong', user_id: User.first.id, extension_id: 68 },
  { id: '1582', name: 'Takhambi/Yerchung', user_id: User.first.id, extension_id: 68 },
  { id: '1583', name: 'Takhamtey', user_id: User.first.id, extension_id: 68 },
  { id: '1584', name: 'Talabadhap', user_id: User.first.id, extension_id: 68 },
  { id: '1585', name: 'Terkong', user_id: User.first.id, extension_id: 68 },
  { id: '1586', name: 'Tharmcharm', user_id: User.first.id, extension_id: 68 },
  { id: '1587', name: 'Thongzhong Goenpa', user_id: User.first.id, extension_id: 68 },
  { id: '1588', name: 'Thumling', user_id: User.first.id, extension_id: 68 },
  { id: '1589', name: 'Tormashong/Lhakhang', user_id: User.first.id, extension_id: 68 },
  { id: '1590', name: 'Tormashong/Thongwang', user_id: User.first.id, extension_id: 68 },
  { id: '1591', name: 'Tormashong/Wadong', user_id: User.first.id, extension_id: 68 },
  { id: '1592', name: 'Wadong', user_id: User.first.id, extension_id: 68 },
  { id: '1593', name: 'Yabi', user_id: User.first.id, extension_id: 68 },
  { id: '1594', name: 'Zangtung', user_id: User.first.id, extension_id: 68 },
  { id: '1595', name: 'Zhingjigpala', user_id: User.first.id, extension_id: 68 }
].each do |v|
  Village.find_or_create_by!(v)
end
