# frozen_string_literal: true

[
  # Kengkhar
  { id: '1263', name: 'Kamngeysa', user_id: User.first.id, extension_id: 60 },
  { id: '1262', name: 'Gishingwoong', user_id: User.first.id, extension_id: 60 },
  { id: '1261', name: 'Yuldari', user_id: User.first.id, extension_id: 60 },
  { id: '1260', name: 'Tsalabi/Menchabilam', user_id: User.first.id, extension_id: 60 },
  { id: '1259', name: 'Tsalabi/Magola', user_id: User.first.id, extension_id: 60 },
  { id: '1258', name: 'Khurdzong', user_id: User.first.id, extension_id: 60 },
  { id: '1257', name: 'Gyalkhar', user_id: User.first.id, extension_id: 60 },
  { id: '1256', name: 'Dongnala', user_id: User.first.id, extension_id: 60 },
  { id: '1255', name: 'Tsalabi', user_id: User.first.id, extension_id: 60 },
  { id: '1254', name: 'Tongla Mangzhing', user_id: User.first.id, extension_id: 60 },
  { id: '1253', name: 'Tongla/Tongla Goenpa', user_id: User.first.id, extension_id: 60 },
  { id: '1264', name: 'Shajoogla', user_id: User.first.id, extension_id: 60 },
  { id: '1251', name: 'Tongla/Goenpa', user_id: User.first.id, extension_id: 60 },
  { id: '1250', name: 'Tongla/Bargoenpa', user_id: User.first.id, extension_id: 60 },
  { id: '1249', name: 'Tongla', user_id: User.first.id, extension_id: 60 },
  { id: '1248', name: 'Zi-Tsibi', user_id: User.first.id, extension_id: 60 },
  { id: '1247', name: 'Soongkar', user_id: User.first.id, extension_id: 60 },
  { id: '1246', name: 'Tongkangla', user_id: User.first.id, extension_id: 60 },
  { id: '1245', name: 'Shingchongri/Zor', user_id: User.first.id, extension_id: 60 },
  { id: '1244', name: 'Shingchongri/Wangkhochi', user_id: User.first.id, extension_id: 60 },
  { id: '1243', name: 'Shingchongri/Tshelshingtang', user_id: User.first.id, extension_id: 60 },
  { id: '1242', name: 'Shingchongri/Tshamnagri', user_id: User.first.id, extension_id: 60 },
  { id: '1241', name: 'Shingchongri/Shetongbi', user_id: User.first.id, extension_id: 60 },
  { id: '1240', name: 'Shingchongri/Putshurme', user_id: User.first.id, extension_id: 60 },
  { id: '1239', name: 'Pangthong', user_id: User.first.id, extension_id: 60 },
  { id: '5000', name: 'Magola', user_id: User.first.id, extension_id: 60 },
  { id: '1237', name: 'Doongmanma', user_id: User.first.id, extension_id: 60 },
  { id: '1236', name: 'Dongkargoenpa', user_id: User.first.id, extension_id: 60 },
  { id: '1235', name: 'Duezawoong', user_id: User.first.id, extension_id: 60 },
  { id: '1234', name: 'Drongphog', user_id: User.first.id, extension_id: 60 },
  { id: '1233', name: 'Deshingpeg', user_id: User.first.id, extension_id: 60 },
  { id: '1232', name: 'Shingchongri', user_id: User.first.id, extension_id: 60 },
  { id: '1231', name: 'Nyoogphu', user_id: User.first.id, extension_id: 60 },
  { id: '1230', name: 'Kyidpari', user_id: User.first.id, extension_id: 60 },
  { id: '1229', name: 'Dochhuru', user_id: User.first.id, extension_id: 60 },
  { id: '1228', name: 'Dochiru', user_id: User.first.id, extension_id: 60 },
  { id: '1227', name: 'Amdaybu', user_id: User.first.id, extension_id: 60 },
  { id: '1226', name: 'Pogola', user_id: User.first.id, extension_id: 60 },
  { id: '1225', name: 'Olokid', user_id: User.first.id, extension_id: 60 },
  { id: '1224', name: 'Warongborang', user_id: User.first.id, extension_id: 60 },
  { id: '1223', name: 'Wangyer', user_id: User.first.id, extension_id: 60 },
  { id: '1222', name: 'Supari', user_id: User.first.id, extension_id: 60 },
  { id: '1221', name: 'Rizor', user_id: User.first.id, extension_id: 60 },
  { id: '1220', name: 'Rishoggay', user_id: User.first.id, extension_id: 60 },
  { id: '1219', name: 'Pegka', user_id: User.first.id, extension_id: 60 },
  { id: '1218', name: 'Neykolok/Pangthang', user_id: User.first.id, extension_id: 60 },
  { id: '1217', name: 'Nanari', user_id: User.first.id, extension_id: 60 },
  { id: '1216', name: 'Maentshala', user_id: User.first.id, extension_id: 60 },
  { id: '1215', name: 'Khoishing', user_id: User.first.id, extension_id: 60 },
  { id: '1214', name: 'Khochoong', user_id: User.first.id, extension_id: 60 },
  { id: '1213', name: 'Khesigang', user_id: User.first.id, extension_id: 60 },
  { id: '1212', name: 'Gomchhu', user_id: User.first.id, extension_id: 60 },
  { id: '1211', name: 'Genchaphu', user_id: User.first.id, extension_id: 60 },
  { id: '1210', name: 'Gabcha', user_id: User.first.id, extension_id: 60 },
  { id: '1209', name: 'Dogtshongnadang', user_id: User.first.id, extension_id: 60 },
  { id: '1208', name: 'Dogsabi', user_id: User.first.id, extension_id: 60 },
  { id: '1207', name: 'Barzor', user_id: User.first.id, extension_id: 60 },
  { id: '1206', name: 'Amshing Wog', user_id: User.first.id, extension_id: 60 },
  { id: '1205', name: 'Bainang', user_id: User.first.id, extension_id: 60 },
  { id: '1204', name: 'Neykorlog', user_id: User.first.id, extension_id: 60 },
  { id: '1203', name: 'Murung/Soichari', user_id: User.first.id, extension_id: 60 },
  { id: '1202', name: 'Murung/Romangla', user_id: User.first.id, extension_id: 60 },
  { id: '1201', name: 'Murung/Deng', user_id: User.first.id, extension_id: 60 },
  { id: '1200', name: 'Mooroong', user_id: User.first.id, extension_id: 60 },
  { id: '1199', name: 'Munma/Pedungrung', user_id: User.first.id, extension_id: 60 },
  { id: '1198', name: 'Munma/Nadang', user_id: User.first.id, extension_id: 60 },
  { id: '1197', name: 'Munma/Kumpari', user_id: User.first.id, extension_id: 60 },
  { id: '1196', name: 'Artshong', user_id: User.first.id, extension_id: 60 },
  { id: '1195', name: 'E-bi', user_id: User.first.id, extension_id: 60 },
  { id: '1194', name: 'Maanma', user_id: User.first.id, extension_id: 60 },
  { id: '1193', name: 'Serkong', user_id: User.first.id, extension_id: 60 },
  { id: '1192', name: 'Kuli', user_id: User.first.id, extension_id: 60 },
  { id: '1191', name: 'Aring', user_id: User.first.id, extension_id: 60 },
  { id: '1190', name: 'Khangma', user_id: User.first.id, extension_id: 60 },
  { id: '1189', name: 'Doktang/Zorthung', user_id: User.first.id, extension_id: 60 },
  { id: '1188', name: 'Doktang/Tshangnari', user_id: User.first.id, extension_id: 60 },
  { id: '1187', name: 'Doktang/Telpo', user_id: User.first.id, extension_id: 60 },
  { id: '1186', name: 'Doktang/Putshurme', user_id: User.first.id, extension_id: 60 },
  { id: '1185', name: 'Pangthang', user_id: User.first.id, extension_id: 60 },
  { id: '1184', name: 'Doktang/Korshingngari', user_id: User.first.id, extension_id: 60 },
  { id: '1183', name: 'Gumnari', user_id: User.first.id, extension_id: 60 },
  { id: '1182', name: 'Dogtang', user_id: User.first.id, extension_id: 60 },
  { id: '1181', name: 'Tshowangri', user_id: User.first.id, extension_id: 60 },
  { id: '1180', name: 'Tshowang', user_id: User.first.id, extension_id: 60 },
  { id: '1179', name: 'Dragphu', user_id: User.first.id, extension_id: 60 },
  { id: '1178', name: 'Bargoenpa', user_id: User.first.id, extension_id: 60 },
  { id: '1177', name: 'Chiphu', user_id: User.first.id, extension_id: 60 },

  # Monggar
  { id: '1292', name: 'Gyelposhing Throm', user_id: User.first.id, extension_id: 61 },
  { id: '1291', name: 'Yagpoogang', user_id: User.first.id, extension_id: 61 },
  { id: '1290', name: 'Wengkhar', user_id: User.first.id, extension_id: 61 },
  { id: '1289', name: 'Wangling', user_id: User.first.id, extension_id: 61 },
  { id: '1288', name: 'Tsheloong Goenpa', user_id: User.first.id, extension_id: 61 },
  { id: '1287', name: 'Tarling', user_id: User.first.id, extension_id: 61 },
  { id: '1286', name: 'Themnangbi', user_id: User.first.id, extension_id: 61 },
  { id: '1285', name: 'Tagchhu', user_id: User.first.id, extension_id: 61 },
  { id: '1284', name: 'Shongkaling', user_id: User.first.id, extension_id: 61 },
  { id: '1283', name: 'Pirmani', user_id: User.first.id, extension_id: 61 },
  { id: '1282', name: 'Perbi', user_id: User.first.id, extension_id: 61 },
  { id: '1281', name: 'Phosorong', user_id: User.first.id, extension_id: 61 },
  { id: '1280', name: 'Nyekhang', user_id: User.first.id, extension_id: 61 },
  { id: '1279', name: 'Nagling', user_id: User.first.id, extension_id: 61 },
  { id: '1278', name: 'Monggar Throm', user_id: User.first.id, extension_id: 61 },
  { id: '1277', name: 'Monggar', user_id: User.first.id, extension_id: 61 },
  { id: '1276', name: 'Loogpangthang', user_id: User.first.id, extension_id: 61 },
  { id: '1275', name: 'Koenbar', user_id: User.first.id, extension_id: 61 },
  { id: '1274', name: 'Kilikhar', user_id: User.first.id, extension_id: 61 },
  { id: '1273', name: 'Khisherpang', user_id: User.first.id, extension_id: 61 },
  { id: '1272', name: 'Kadam', user_id: User.first.id, extension_id: 61 },
  { id: '1271', name: 'Jamchhoeling', user_id: User.first.id, extension_id: 61 },
  { id: '1270', name: 'Jaibab', user_id: User.first.id, extension_id: 61 },
  { id: '1269', name: 'Gyelpoizhing', user_id: User.first.id, extension_id: 61 },
  { id: '1268', name: 'Gushingwang', user_id: User.first.id, extension_id: 61 },
  { id: '1267', name: 'Gora', user_id: User.first.id, extension_id: 61 },
  { id: '1266', name: 'Chirmani', user_id: User.first.id, extension_id: 61 },
  { id: '1265', name: 'Barpong', user_id: User.first.id, extension_id: 61 },

  # Na-Rang
  { id: '1597', name: 'Gomchu', user_id: User.first.id, extension_id: 62 },
  { id: '1598', name: 'Gomchu Bumpa', user_id: User.first.id, extension_id: 62 },
  { id: '1599', name: 'Gomchu Chema', user_id: User.first.id, extension_id: 62 },
  { id: '1600', name: 'Gomchu Deyphung', user_id: User.first.id, extension_id: 62 },
  { id: '1601', name: 'Gomchu Hurchilo', user_id: User.first.id, extension_id: 62 },
  { id: '1602', name: 'Gomchu Phenzur', user_id: User.first.id, extension_id: 62 },
  { id: '1603', name: 'Gomchuzur', user_id: User.first.id, extension_id: 62 },
  { id: '1604', name: 'Khalong', user_id: User.first.id, extension_id: 62 },
  { id: '1605', name: 'Narang', user_id: User.first.id, extension_id: 62 },
  { id: '1606', name: 'Narang Brakhagtang', user_id: User.first.id, extension_id: 62 },
  { id: '1607', name: 'Narang Chaskhar', user_id: User.first.id, extension_id: 62 },
  { id: '1608', name: 'Narang Dangthung', user_id: User.first.id, extension_id: 62 },
  { id: '1609', name: 'Narang Dengsor', user_id: User.first.id, extension_id: 62 },
  { id: '1610', name: 'Narang Garpamani', user_id: User.first.id, extension_id: 62 },
  { id: '1611', name: 'Narang Gothonpo', user_id: User.first.id, extension_id: 62 },
  { id: '1612', name: 'Narang Jomri', user_id: User.first.id, extension_id: 62 },
  { id: '1613', name: 'Narang Maithung', user_id: User.first.id, extension_id: 62 },
  { id: '1614', name: 'Narang Pangkang', user_id: User.first.id, extension_id: 62 },
  { id: '1615', name: 'Narang Pangkang Besipoktor', user_id: User.first.id, extension_id: 62 },
  { id: '1616', name: 'Narang Pangthang', user_id: User.first.id, extension_id: 62 },
  { id: '1617', name: 'Narang Phaphungpangkang', user_id: User.first.id, extension_id: 62 },
  { id: '1618', name: 'Narang Raynangkhar', user_id: User.first.id, extension_id: 62 },
  { id: '1619', name: 'Narang Thongkhar', user_id: User.first.id, extension_id: 62 },
  { id: '1620', name: 'Narang Wangyer', user_id: User.first.id, extension_id: 62 },
  { id: '1621', name: 'Narang Waphaipangthang', user_id: User.first.id, extension_id: 62 },
  { id: '1622', name: 'Pangkang', user_id: User.first.id, extension_id: 62 },
  { id: '1623', name: 'Pangkang Besipoktor', user_id: User.first.id, extension_id: 62 },
  { id: '1624', name: 'Pangkang Dongsum', user_id: User.first.id, extension_id: 62 },
  { id: '1625', name: 'Pangkang Gashari', user_id: User.first.id, extension_id: 62 },
  { id: '1626', name: 'Thrinang Phusizur', user_id: User.first.id, extension_id: 62 },
  { id: '1627', name: 'Thrinangphu', user_id: User.first.id, extension_id: 62 }
].each do |v|
  Village.find_or_create_by!(v)
end
