# frozen_string_literal: true

[
  # Chagsakhar
  { id: '1037', name: 'Yetong', user_id: User.first.id, extension_id: 55 },
  { id: '1036', name: 'Yangrapoongshing', user_id: User.first.id, extension_id: 55 },
  { id: '1035', name: 'Pam', user_id: User.first.id, extension_id: 55 },
  { id: '1034', name: 'Kharnang Lamwog', user_id: User.first.id, extension_id: 55 },
  { id: '1033', name: 'Kharnang Lamtak', user_id: User.first.id, extension_id: 55 },
  { id: '1032', name: 'Goenpa', user_id: User.first.id, extension_id: 55 },
  { id: '1031', name: 'Doongsingma', user_id: User.first.id, extension_id: 55 },

  # Dramedtse
  { id: '1069', name: 'Drametse Throm', user_id: User.first.id, extension_id: 56 },
  { id: '1068', name: 'Zangkhar', user_id: User.first.id, extension_id: 56 },
  { id: '1067', name: 'Yengkhartshing', user_id: User.first.id, extension_id: 56 },
  { id: '1066', name: 'Phentshomo', user_id: User.first.id, extension_id: 56 },
  { id: '1065', name: 'Ngarphel', user_id: User.first.id, extension_id: 56 },
  { id: '1064', name: 'Ngarphai', user_id: User.first.id, extension_id: 56 },
  { id: '1063', name: 'Luwang', user_id: User.first.id, extension_id: 56 },
  { id: '1062', name: 'Jiwa', user_id: User.first.id, extension_id: 56 },
  { id: '1061', name: 'Shaphangma Dungkhar', user_id: User.first.id, extension_id: 56 },
  { id: '1060', name: 'Shaphangma', user_id: User.first.id, extension_id: 56 },
  { id: '1059', name: 'Shapangma', user_id: User.first.id, extension_id: 56 },
  { id: '1058', name: 'Shadang', user_id: User.first.id, extension_id: 56 },
  { id: '1057', name: 'Serkhagphu', user_id: User.first.id, extension_id: 56 },
  { id: '1056', name: 'Laymey/Serkhagphu', user_id: User.first.id, extension_id: 56 },
  { id: '1055', name: 'Laymey', user_id: User.first.id, extension_id: 56 },
  { id: '1054', name: 'Gobka', user_id: User.first.id, extension_id: 56 },
  { id: '1053', name: 'Gashari', user_id: User.first.id, extension_id: 56 },
  { id: '1052', name: 'Dramdetse', user_id: User.first.id, extension_id: 56 },
  { id: '1051', name: 'Yaloong', user_id: User.first.id, extension_id: 56 },
  { id: '1050', name: 'Waichur', user_id: User.first.id, extension_id: 56 },
  { id: '1049', name: 'Thoongdari', user_id: User.first.id, extension_id: 56 },
  { id: '1048', name: 'Thongdabi', user_id: User.first.id, extension_id: 56 },
  { id: '1047', name: 'Thramlo', user_id: User.first.id, extension_id: 56 },
  { id: '1046', name: 'Bikhar', user_id: User.first.id, extension_id: 56 },
  { id: '1045', name: 'Bazor', user_id: User.first.id, extension_id: 56 },

  # Drepoong
  { id: '1043', name: 'Zunglen', user_id: User.first.id, extension_id: 57 },
  { id: '1042', name: 'Tsangkhar', user_id: User.first.id, extension_id: 57 },
  { id: '1041', name: 'Labtsa ', user_id: User.first.id, extension_id: 57 },
  { id: '1040', name: 'Drepoong', user_id: User.first.id, extension_id: 57 },
  { id: '1039', name: 'Chhagsuzor', user_id: User.first.id, extension_id: 57 },

  # Gongdue
  { id: '1105', name: 'Yangbari', user_id: User.first.id, extension_id: 58 },
  { id: '1104', name: 'Weringla', user_id: User.first.id, extension_id: 58 },
  { id: '1103', name: 'Tshamlabi', user_id: User.first.id, extension_id: 58 },
  { id: '1102', name: 'Tshabor', user_id: User.first.id, extension_id: 58 },
  { id: '1101', name: 'Toedkar', user_id: User.first.id, extension_id: 58 },
  { id: '1100', name: 'Doongda', user_id: User.first.id, extension_id: 58 },
  { id: '1099', name: 'Salibi', user_id: User.first.id, extension_id: 58 },
  { id: '1098', name: 'Phuchung Goenpa', user_id: User.first.id, extension_id: 58 },
  { id: '1097', name: 'Phosala', user_id: User.first.id, extension_id: 58 },
  { id: '1096', name: 'Phadzong', user_id: User.first.id, extension_id: 58 },
  { id: '1095', name: 'Pikari', user_id: User.first.id, extension_id: 58 },
  { id: '1094', name: 'Pangtong', user_id: User.first.id, extension_id: 58 },
  { id: '1093', name: 'Pangthang', user_id: User.first.id, extension_id: 58 },
  { id: '1092', name: 'Maentshang', user_id: User.first.id, extension_id: 58 },
  { id: '1091', name: 'Miden', user_id: User.first.id, extension_id: 58 },
  { id: '1090', name: 'Labtsa', user_id: User.first.id, extension_id: 58 },
  { id: '1089', name: 'Kumadzong', user_id: User.first.id, extension_id: 58 },
  { id: '1088', name: 'Kormed', user_id: User.first.id, extension_id: 58 },
  { id: '1087', name: 'Gungdue', user_id: User.first.id, extension_id: 58 },
  { id: '1086', name: 'Gorthongla', user_id: User.first.id, extension_id: 58 },
  { id: '1085', name: 'Gongdey', user_id: User.first.id, extension_id: 58 },
  { id: '1084', name: 'Goenpa', user_id: User.first.id, extension_id: 58 },
  { id: '1083', name: 'Dogmo', user_id: User.first.id, extension_id: 58 },
  { id: '1082', name: 'Dewabi', user_id: User.first.id, extension_id: 58 },
  { id: '1081', name: 'Dengkaling', user_id: User.first.id, extension_id: 58 },
  { id: '1080', name: 'Dekhar', user_id: User.first.id, extension_id: 58 },
  { id: '1079', name: 'Damkhar', user_id: User.first.id, extension_id: 58 },
  { id: '1078', name: 'Daagsa', user_id: User.first.id, extension_id: 58 },
  { id: '1077', name: 'Chhaibi', user_id: User.first.id, extension_id: 58 },
  { id: '1076', name: 'Bogarbi', user_id: User.first.id, extension_id: 58 },
  { id: '1075', name: 'Bangbangla', user_id: User.first.id, extension_id: 58 },
  { id: '1074', name: 'Baagla Khimong', user_id: User.first.id, extension_id: 58 },
  { id: '1073', name: 'Baagla Goenpa', user_id: User.first.id, extension_id: 58 },
  { id: '1072', name: 'E-di', user_id: User.first.id, extension_id: 58 },
  { id: '1071', name: 'Baagla', user_id: User.first.id, extension_id: 58 },

  # Jurmed
  { id: '1175', name: 'Yarakla/Shingserri', user_id: User.first.id, extension_id: 59 },
  { id: '1174', name: 'Yarakla/Pangkang', user_id: User.first.id, extension_id: 59 },
  { id: '1173', name: 'Maniling', user_id: User.first.id, extension_id: 59 },
  { id: '1172', name: 'Khyimtagpa', user_id: User.first.id, extension_id: 59 },
  { id: '1171', name: 'Kaikhar', user_id: User.first.id, extension_id: 59 },
  { id: '1170', name: 'Darong', user_id: User.first.id, extension_id: 59 },
  { id: '1169', name: 'Chenchhari', user_id: User.first.id, extension_id: 59 },
  { id: '1168', name: 'Yarakla/Bachha', user_id: User.first.id, extension_id: 59 },
  { id: '1167', name: 'Ya-Ragkla', user_id: User.first.id, extension_id: 59 },
  { id: '1166', name: 'Shingmoong', user_id: User.first.id, extension_id: 59 },
  { id: '1165', name: 'Rangri', user_id: User.first.id, extension_id: 59 },
  { id: '1164', name: 'Ngamphu', user_id: User.first.id, extension_id: 59 },
  { id: '1163', name: 'Sangkama', user_id: User.first.id, extension_id: 59 },
  { id: '1162', name: 'Roinangwong/Wodang', user_id: User.first.id, extension_id: 59 },
  { id: '1161', name: 'Roinangwong/Tshangkharzor', user_id: User.first.id, extension_id: 59 },
  { id: '1160', name: 'Roinangwong/Pungla', user_id: User.first.id, extension_id: 59 },
  { id: '1159', name: 'Roinangwong/Phentokma', user_id: User.first.id, extension_id: 59 },
  { id: '1158', name: 'Roinangwong/Mentshang', user_id: User.first.id, extension_id: 59 },
  { id: '1157', name: 'Roinangwong/Luzor', user_id: User.first.id, extension_id: 59 },
  { id: '1156', name: 'Roinangwong/Kurtakay', user_id: User.first.id, extension_id: 59 },
  { id: '1155', name: 'Roinangwong', user_id: User.first.id, extension_id: 59 },
  { id: '1154', name: 'Muktangkhar/Tshelam/Kamling', user_id: User.first.id, extension_id: 59 },
  { id: '1153', name: 'Muktangkhar/Thongpashing', user_id: User.first.id, extension_id: 59 },
  { id: '1152', name: 'Muktangkhar/Singyephu', user_id: User.first.id, extension_id: 59 },
  { id: '1151', name: 'Muktangkhar/Rewang', user_id: User.first.id, extension_id: 59 },
  { id: '1150', name: 'Muktangkhar/Rephujab', user_id: User.first.id, extension_id: 59 },
  { id: '1149', name: 'Muktangkhar/Rephu', user_id: User.first.id, extension_id: 59 },
  { id: '1148', name: 'Muktangkhar/Phaichelo', user_id: User.first.id, extension_id: 59 },
  { id: '1147', name: 'Muktangkhar/Pangthang', user_id: User.first.id, extension_id: 59 },
  { id: '1146', name: 'Muktangkhar/Orkawang', user_id: User.first.id, extension_id: 59 },
  { id: '1145', name: 'Muktangkhar/Langabi', user_id: User.first.id, extension_id: 59 },
  { id: '1144', name: 'Muktangkhar/Kanglung', user_id: User.first.id, extension_id: 59 },
  { id: '1143', name: 'Muktangkhar/Gomtshanglo', user_id: User.first.id, extension_id: 59 },
  { id: '1142', name: 'Muktangkhar/Ganggarthang', user_id: User.first.id, extension_id: 59 },
  { id: '1141', name: 'Muktangkhar/Gamong', user_id: User.first.id, extension_id: 59 },
  { id: '1140', name: 'Muktangkhar/Dungmen', user_id: User.first.id, extension_id: 59 },
  { id: '1139', name: 'Muktangkhar/Barpung', user_id: User.first.id, extension_id: 59 },
  { id: '1138', name: 'Muktangkhar/Bacha', user_id: User.first.id, extension_id: 59 },
  { id: '1137', name: 'Awa Tang', user_id: User.first.id, extension_id: 59 },
  { id: '1136', name: 'Moogtangkhar', user_id: User.first.id, extension_id: 59 },
  { id: '1135', name: 'Kognala', user_id: User.first.id, extension_id: 59 },
  { id: '1134', name: 'Tologbi', user_id: User.first.id, extension_id: 59 },
  { id: '1133', name: 'Tselam', user_id: User.first.id, extension_id: 59 },
  { id: '1132', name: 'Tashi Tshering ', user_id: User.first.id, extension_id: 59 },
  { id: '1131 ', name: 'Pangthang ', user_id: User.first.id, extension_id: 59 },
  { id: '1130 ', name: 'Gaykhar ', user_id: User.first.id, extension_id: 59 },
  { id: '1129', name: 'Dori ', user_id: User.first.id, extension_id: 59 },
  { id: '1128 ', name: 'Baydengnyer ', user_id: User.first.id, extension_id: 59 },
  { id: '1127', name: 'Barlamtoed', user_id: User.first.id, extension_id: 59 },
  { id: '1126', name: 'Dongkar', user_id: User.first.id, extension_id: 59 },
  { id: '1125 ', name: 'Samkhar ', user_id: User.first.id, extension_id: 59 },
  { id: '1124 ', name: 'Rimpagko ', user_id: User.first.id, extension_id: 59 },
  { id: '1123 ', name: 'Moodoongkhar ', user_id: User.first.id, extension_id: 59 },
  { id: '1122', name: 'Korphu', user_id: User.first.id, extension_id: 59 },
  { id: '1121', name: 'Karmaling', user_id: User.first.id, extension_id: 59 },
  { id: '1120', name: 'Dekilam', user_id: User.first.id, extension_id: 59 },
  { id: '1119', name: 'Chagpa', user_id: User.first.id, extension_id: 59 },
  { id: '1118', name: 'Boomnaleg', user_id: User.first.id, extension_id: 59 },
  { id: '1117', name: 'Chelam', user_id: User.first.id, extension_id: 59 },
  { id: '1116', name: 'Pegpela', user_id: User.first.id, extension_id: 59 },
  { id: '1115', name: 'Modoongbi', user_id: User.first.id, extension_id: 59 },
  { id: '1114', name: 'Menchaphoog', user_id: User.first.id, extension_id: 59 },
  { id: '1113', name: 'Maphel', user_id: User.first.id, extension_id: 59 },
  { id: '1112', name: 'Korkhang', user_id: User.first.id, extension_id: 59 },
  { id: '1111', name: 'Gongtshang', user_id: User.first.id, extension_id: 59 },
  { id: '1110', name: 'Doomdey', user_id: User.first.id, extension_id: 59 },
  { id: '1109', name: 'Dangkila', user_id: User.first.id, extension_id: 59 },
  { id: '1108', name: 'Aring Daza', user_id: User.first.id, extension_id: 59 },
  { id: '1107', name: 'Bilam', user_id: User.first.id, extension_id: 59 }
].each do |v|
  Village.find_or_create_by!(v)
end
