# frozen_string_literal: true

puts 'Seeding villages of Mongar...'

[
  # Balam
  { id: '901', name: 'Selkhar', user_id: User.first.id, extension_id: 53 },
  { id: '900', name: 'Sangjoogzor', user_id: User.first.id, extension_id: 53 },
  { id: '899', name: 'Khebishing', user_id: User.first.id, extension_id: 53 },
  { id: '898', name: 'Jadoong Goenpa', user_id: User.first.id, extension_id: 53 },
  { id: '897', name: 'Jadoong', user_id: User.first.id, extension_id: 53 },
  { id: '896', name: 'Balam', user_id: User.first.id, extension_id: 53 },

  # Chhaling
  { id: '1029', name: 'Zhongkey', user_id: User.first.id, extension_id: 54 },
  { id: '1028', name: 'Zhongje', user_id: User.first.id, extension_id: 54 },
  { id: '1027', name: 'Yokhoi', user_id: User.first.id, extension_id: 54 },
  { id: '1026', name: 'Yoezer Pangthang ', user_id: User.first.id, extension_id: 54 },
  { id: '1025', name: 'Yangthang', user_id: User.first.id, extension_id: 54 },
  { id: '1024', name: 'Jachhungling', user_id: User.first.id, extension_id: 54 },
  { id: '1023', name: 'Zigthuem', user_id: User.first.id, extension_id: 54 },
  { id: '1022', name: 'Wangkhar/Zhongje', user_id: User.first.id, extension_id: 54 },
  { id: '1021', name: 'Yonkhyim/Yontenkhemsang', user_id: User.first.id, extension_id: 54 },
  { id: '1020 ', name: 'Yokhoi ', user_id: User.first.id, extension_id: 54 },
  { id: '1019', name: 'Tshepadoong', user_id: User.first.id, extension_id: 54 },
  { id: '1018', name: 'Tashikhangsar', user_id: User.first.id, extension_id: 54 },
  { id: '1017', name: 'Tadzong', user_id: User.first.id, extension_id: 54 },
  { id: '1016', name: 'Soomthuen', user_id: User.first.id, extension_id: 54 },
  { id: '1015', name: 'Phangshing', user_id: User.first.id, extension_id: 54 },
  { id: '1014', name: 'Pachaphogchi', user_id: User.first.id, extension_id: 54 },
  { id: '1013', name: 'Wangkhar/Pangthang', user_id: User.first.id, extension_id: 54 },
  { id: '1012', name: 'Namathang', user_id: User.first.id, extension_id: 54 },
  { id: '1011', name: 'Mentshang', user_id: User.first.id, extension_id: 54 },
  { id: '1010', name: 'Khyimsang', user_id: User.first.id, extension_id: 54 },
  { id: '1009', name: 'Kawakhoi', user_id: User.first.id, extension_id: 54 },
  { id: '1008', name: 'Kamasa', user_id: User.first.id, extension_id: 54 },
  { id: '1007', name: 'Genseng', user_id: User.first.id, extension_id: 54 },
  { id: '1006', name: 'Doongjoog', user_id: User.first.id, extension_id: 54 },
  { id: '1005', name: 'Wangkhar/Dogtang', user_id: User.first.id, extension_id: 54 },
  { id: '1004', name: 'Dokorbang', user_id: User.first.id, extension_id: 54 },
  { id: '1003', name: 'Changmashing', user_id: User.first.id, extension_id: 54 },
  { id: '1002', name: 'Balingbi', user_id: User.first.id, extension_id: 54 },
  { id: '1001', name: 'Kadam', user_id: User.first.id, extension_id: 54 },
  { id: '1000', name: 'Wangkhar', user_id: User.first.id, extension_id: 54 },
  { id: '999 ', name: 'Tshokila ', user_id: User.first.id, extension_id: 54 },
  { id: '998', name: 'Tshangkhar', user_id: User.first.id, extension_id: 54 },
  { id: '997', name: 'Truelkusalung', user_id: User.first.id, extension_id: 54 },
  { id: '996', name: 'Thempang', user_id: User.first.id, extension_id: 54 },
  { id: '995', name: 'Thakthala', user_id: User.first.id, extension_id: 54 },
  { id: '994', name: 'Takling', user_id: User.first.id, extension_id: 54 },
  { id: '993', name: 'Shokposeng', user_id: User.first.id, extension_id: 54 },
  { id: '992', name: 'Shebchi', user_id: User.first.id, extension_id: 54 },
  { id: '991', name: 'Sapogtor', user_id: User.first.id, extension_id: 54 },
  { id: '990', name: 'Ramhambi', user_id: User.first.id, extension_id: 54 },
  { id: '989', name: 'Phoomazur', user_id: User.first.id, extension_id: 54 },
  { id: '988', name: 'Phodangma', user_id: User.first.id, extension_id: 54 },
  { id: '987', name: 'Pemagaysar', user_id: User.first.id, extension_id: 54 },
  { id: '986', name: 'Pangthang Shokposeng', user_id: User.first.id, extension_id: 54 },
  { id: '985', name: 'Pangthang Chungku', user_id: User.first.id, extension_id: 54 },
  { id: '984', name: 'Pangthang', user_id: User.first.id, extension_id: 54 },
  { id: '983', name: 'Pangjagpa', user_id: User.first.id, extension_id: 54 },
  { id: '982', name: 'Noomabiwang', user_id: User.first.id, extension_id: 54 },
  { id: '981', name: 'Nordangsa', user_id: User.first.id, extension_id: 54 },
  { id: '980', name: 'Nagtshangwog', user_id: User.first.id, extension_id: 54 },
  { id: '979', name: 'Nagtshang', user_id: User.first.id, extension_id: 54 },
  { id: '978', name: 'Masangkangjay', user_id: User.first.id, extension_id: 54 },
  { id: '977', name: 'Longkang', user_id: User.first.id, extension_id: 54 },
  { id: '976', name: 'Kuenjong', user_id: User.first.id, extension_id: 54 },
  { id: '975', name: 'Khoilajong', user_id: User.first.id, extension_id: 54 },
  { id: '974', name: 'Khoijongla', user_id: User.first.id, extension_id: 54 },
  { id: '973', name: 'Khartong', user_id: User.first.id, extension_id: 54 },
  { id: '972', name: 'Kharigab', user_id: User.first.id, extension_id: 54 },
  { id: '971', name: 'Khardoongma', user_id: User.first.id, extension_id: 54 },
  { id: '970', name: 'Khampaje', user_id: User.first.id, extension_id: 54 },
  { id: '969', name: 'Khachhorshing', user_id: User.first.id, extension_id: 54 },
  { id: '968 ', name: 'Roelmochhu ', user_id: User.first.id, extension_id: 54 },
  { id: '967', name: 'Bodhishing', user_id: User.first.id, extension_id: 54 },
  { id: '966', name: 'Japanang', user_id: User.first.id, extension_id: 54 },
  { id: '965', name: 'Jambi', user_id: User.first.id, extension_id: 54 },
  { id: '964', name: 'Gortongla', user_id: User.first.id, extension_id: 54 },
  { id: '963', name: 'Gorsoom', user_id: User.first.id, extension_id: 54 },
  { id: '962', name: 'Goensar', user_id: User.first.id, extension_id: 54 },
  { id: '961', name: 'Dogtang', user_id: User.first.id, extension_id: 54 },
  { id: '960', name: 'Drongtoed Bakhyim', user_id: User.first.id, extension_id: 54 },
  { id: '959', name: 'Drongtoed', user_id: User.first.id, extension_id: 54 },
  { id: '958', name: 'Domala', user_id: User.first.id, extension_id: 54 },
  { id: '957', name: 'Darseng', user_id: User.first.id, extension_id: 54 },
  { id: '956', name: 'Dabmaling', user_id: User.first.id, extension_id: 54 },
  { id: '955', name: 'Jongji', user_id: User.first.id, extension_id: 54 },
  { id: '954', name: 'Aagshaling', user_id: User.first.id, extension_id: 54 },
  { id: '953', name: 'Tagling', user_id: User.first.id, extension_id: 54 },
  { id: '952', name: 'Rolmochhu', user_id: User.first.id, extension_id: 54 },
  { id: '951', name: 'Pogtor', user_id: User.first.id, extension_id: 54 },
  { id: '950', name: 'Namling', user_id: User.first.id, extension_id: 54 },
  { id: '949', name: 'Chulebi/Longkang', user_id: User.first.id, extension_id: 54 },
  { id: '948', name: 'Chulebi/Pangthang', user_id: User.first.id, extension_id: 54 },
  { id: '947', name: 'Kampasadong', user_id: User.first.id, extension_id: 54 },
  { id: '946', name: 'Chulabi', user_id: User.first.id, extension_id: 54 },
  { id: '945', name: 'Chewang', user_id: User.first.id, extension_id: 54 },
  { id: '944', name: 'Chagsar', user_id: User.first.id, extension_id: 54 },
  { id: '943', name: 'Charzhong', user_id: User.first.id, extension_id: 54 },
  { id: '942', name: 'Chamkhang', user_id: User.first.id, extension_id: 54 },
  { id: '941', name: 'Zanglawang', user_id: User.first.id, extension_id: 54 },
  { id: '940', name: 'Wang', user_id: User.first.id, extension_id: 54 },
  { id: '939', name: 'Torzhonggor', user_id: User.first.id, extension_id: 54 },
  { id: '938', name: 'Tashipogtor', user_id: User.first.id, extension_id: 54 },
  { id: '937', name: 'Sokpaling', user_id: User.first.id, extension_id: 54 },
  { id: '936', name: 'Shingkharzhong', user_id: User.first.id, extension_id: 54 },
  { id: '935', name: 'Salathro', user_id: User.first.id, extension_id: 54 },
  { id: '934', name: 'Nyerpa', user_id: User.first.id, extension_id: 54 },
  { id: '933', name: 'Namabi', user_id: User.first.id, extension_id: 54 },
  { id: '932', name: 'Lhakhang Takpa', user_id: User.first.id, extension_id: 54 },
  { id: '931', name: 'Lhakhang Sokpaling', user_id: User.first.id, extension_id: 54 },
  { id: '930', name: 'Lhakhang Ringseng', user_id: User.first.id, extension_id: 54 },
  { id: '929', name: 'Lhakhang Rikseng', user_id: User.first.id, extension_id: 54 },
  { id: '928', name: 'Lhakhang Pangjab', user_id: User.first.id, extension_id: 54 },
  { id: '927', name: 'Lhakhang Lingchoong', user_id: User.first.id, extension_id: 54 },
  { id: '926', name: 'Lhakhang Lhakhangsu', user_id: User.first.id, extension_id: 54 },
  { id: '925', name: 'Lhakhang Khuchurma', user_id: User.first.id, extension_id: 54 },
  { id: '924', name: 'LhakhangKhoyoor', user_id: User.first.id, extension_id: 54 },
  { id: '923', name: 'Lhakhang Goenshing', user_id: User.first.id, extension_id: 54 },
  { id: '922', name: 'Lhakhang Dongbar', user_id: User.first.id, extension_id: 54 },
  { id: '921', name: 'Lhakhang Barna', user_id: User.first.id, extension_id: 54 },
  { id: '920', name: 'Lhakhang', user_id: User.first.id, extension_id: 54 },
  { id: '919', name: 'Kurzam', user_id: User.first.id, extension_id: 54 },
  { id: '918', name: 'Kotshomi', user_id: User.first.id, extension_id: 54 },
  { id: '917', name: 'Kharijab', user_id: User.first.id, extension_id: 54 },
  { id: '916', name: 'Dopang', user_id: User.first.id, extension_id: 54 },
  { id: '915', name: 'Chali/Chaukileng', user_id: User.first.id, extension_id: 54 },
  { id: '914', name: 'Bolipang', user_id: User.first.id, extension_id: 54 },
  { id: '913', name: 'Bana', user_id: User.first.id, extension_id: 54 },
  { id: '912', name: 'Tepaphu', user_id: User.first.id, extension_id: 54 },
  { id: '911', name: 'Chhaling', user_id: User.first.id, extension_id: 54 },
  { id: '910', name: 'Chawasing', user_id: User.first.id, extension_id: 54 },
  { id: '909', name: 'Bewling', user_id: User.first.id, extension_id: 54 },
  { id: '908', name: 'Barling', user_id: User.first.id, extension_id: 54 },
  { id: '907', name: 'Barigoila', user_id: User.first.id, extension_id: 54 },
  { id: '906', name: 'Bamijangsa', user_id: User.first.id, extension_id: 54 },
  { id: '905', name: 'Bakhyim', user_id: User.first.id, extension_id: 54 },
  { id: '904', name: 'Aumedung', user_id: User.first.id, extension_id: 54 },
  { id: '903', name: 'Aidurla', user_id: User.first.id, extension_id: 54 }
].each do |v|
  Village.find_or_create_by!(v)
end
