# frozen_string_literal: true

[
  # Tsento
  { id: '1973', name: 'Cheding', user_id: User.first.id, extension_id: 79 },
  { id: '1974', name: 'Chunjey', user_id: User.first.id, extension_id: 79 },
  { id: '1975', name: 'Jetsaphu', user_id: User.first.id, extension_id: 79 },
  { id: '1976', name: 'Lemgon', user_id: User.first.id, extension_id: 79 },
  { id: '1977', name: 'Metsi', user_id: User.first.id, extension_id: 79 },
  { id: '1978', name: 'Namji', user_id: User.first.id, extension_id: 79 },
  { id: '1979', name: 'Nechu', user_id: User.first.id, extension_id: 79 },
  { id: '1980', name: 'Nyamey', user_id: User.first.id, extension_id: 79 },
  { id: '1981', name: 'Phangdo', user_id: User.first.id, extension_id: 79 },
  { id: '1982', name: 'Shana', user_id: User.first.id, extension_id: 79 },
  { id: '1983', name: 'Shana/Chuyul', user_id: User.first.id, extension_id: 79 },
  { id: '1984', name: 'Shana/Lemdo', user_id: User.first.id, extension_id: 79 },
  { id: '1985', name: 'Shari', user_id: User.first.id, extension_id: 79 },
  { id: '1986', name: 'Soey Domzang', user_id: User.first.id, extension_id: 79 },
  { id: '1987', name: 'Soey yaksha', user_id: User.first.id, extension_id: 79 },
  { id: '1988', name: 'Taksang', user_id: User.first.id, extension_id: 79 },
  { id: '1989', name: 'Tsatsam', user_id: User.first.id, extension_id: 79 },
  { id: '1990', name: 'Tshenshi', user_id: User.first.id, extension_id: 79 },
  { id: '1991', name: 'Yaksha', user_id: User.first.id, extension_id: 79 },
  { id: '1992', name: 'Zamtsa', user_id: User.first.id, extension_id: 79 },
  { id: '1993', name: 'Nubri', user_id: User.first.id, extension_id: 79 },

  # Wangchang
  { id: '1995', name: 'Bondey', user_id: User.first.id, extension_id: 80 },
  { id: '1996', name: 'Chang Rouna', user_id: User.first.id, extension_id: 80 },
  { id: '1997', name: 'Chang Sinchuna', user_id: User.first.id, extension_id: 80 },
  { id: '1998', name: 'Changkar', user_id: User.first.id, extension_id: 80 },
  { id: '1999', name: 'Changmithangka', user_id: User.first.id, extension_id: 80 },
  { id: '2000', name: 'Chewnang', user_id: User.first.id, extension_id: 80 },
  { id: '2001', name: 'Chiminang', user_id: User.first.id, extension_id: 80 },
  { id: '2002', name: 'Chimuna', user_id: User.first.id, extension_id: 80 },
  { id: '2003', name: 'Chintsho', user_id: User.first.id, extension_id: 80 },
  { id: '2004', name: 'Choten Dangrim', user_id: User.first.id, extension_id: 80 },
  { id: '2005', name: 'Dochukha', user_id: User.first.id, extension_id: 80 },
  { id: '2006', name: 'Druna', user_id: User.first.id, extension_id: 80 },
  { id: '2007', name: 'Dungchuphu', user_id: User.first.id, extension_id: 80 },
  { id: '2008', name: 'Dungkar', user_id: User.first.id, extension_id: 80 },
  { id: '2009', name: 'Gangkha', user_id: User.first.id, extension_id: 80 },
  { id: '2010', name: 'Gangtey', user_id: User.first.id, extension_id: 80 },
  { id: '2011', name: 'Geptey', user_id: User.first.id, extension_id: 80 },
  { id: '2012', name: 'Geptey Barico', user_id: User.first.id, extension_id: 80 },
  { id: '2013', name: 'Geptey Deshigang', user_id: User.first.id, extension_id: 80 },
  { id: '2014', name: 'Geptey Druna', user_id: User.first.id, extension_id: 80 },
  { id: '2015', name: 'Geptey Langmana', user_id: User.first.id, extension_id: 80 },
  { id: '2016', name: 'Geptey Ngetsu', user_id: User.first.id, extension_id: 80 },
  { id: '2017', name: 'Geptey Shingkha', user_id: User.first.id, extension_id: 80 },
  { id: '2018', name: 'Geptey Sisitakpa', user_id: User.first.id, extension_id: 80 },
  { id: '2019', name: 'Geptey Yoowang', user_id: User.first.id, extension_id: 80 },
  { id: '2020', name: 'Gepty Druna', user_id: User.first.id, extension_id: 80 },
  { id: '2021', name: 'Gepty Tshongdue', user_id: User.first.id, extension_id: 80 },
  { id: '2022', name: 'Gepty Yoowang', user_id: User.first.id, extension_id: 80 },
  { id: '2023', name: 'Gorina', user_id: User.first.id, extension_id: 80 },
  { id: '2024', name: 'Gyelgang', user_id: User.first.id, extension_id: 80 },
  { id: '2025', name: 'Jangkhuna', user_id: User.first.id, extension_id: 80 },
  { id: '2026', name: 'Jangsabu', user_id: User.first.id, extension_id: 80 },
  { id: '2027', name: 'Jangsina', user_id: User.first.id, extension_id: 80 },
  { id: '2028', name: 'Jangsuna', user_id: User.first.id, extension_id: 80 },
  { id: '2029', name: 'Jangteyna', user_id: User.first.id, extension_id: 80 },
  { id: '2030', name: 'Jew', user_id: User.first.id, extension_id: 80 },
  { id: '2031', name: 'Jimnang', user_id: User.first.id, extension_id: 80 },
  { id: '2032', name: 'Kangjulo', user_id: User.first.id, extension_id: 80 },
  { id: '2033', name: 'Khangkhu', user_id: User.first.id, extension_id: 80 },
  { id: '2034', name: 'Khangkhu Changmethangka', user_id: User.first.id, extension_id: 80 },
  { id: '2035', name: 'Khangkhu Chiminang', user_id: User.first.id, extension_id: 80 },
  { id: '2036', name: 'Khangkhu Segona', user_id: User.first.id, extension_id: 80 },
  { id: '2037', name: 'Khangkhu Wochukha', user_id: User.first.id, extension_id: 80 },
  { id: '2038', name: 'Khangkhu Zakha', user_id: User.first.id, extension_id: 80 },
  { id: '2039', name: 'Khimsabu', user_id: User.first.id, extension_id: 80 },
  { id: '2040', name: 'Langmana', user_id: User.first.id, extension_id: 80 },
  { id: '2041', name: 'Langmanang', user_id: User.first.id, extension_id: 80 },
  { id: '2042', name: 'Lhakhang Jab', user_id: User.first.id, extension_id: 80 },
  { id: '2043', name: 'Lomlo', user_id: User.first.id, extension_id: 80 },
  { id: '2044', name: 'Mendi/Rauna', user_id: User.first.id, extension_id: 80 },
  { id: '2045', name: 'Mindi', user_id: User.first.id, extension_id: 80 },
  { id: '2046', name: 'Nakha', user_id: User.first.id, extension_id: 80 },
  { id: '2047', name: 'Nakha/Bondey', user_id: User.first.id, extension_id: 80 },
  { id: '2048', name: 'Nakha/Rawna', user_id: User.first.id, extension_id: 80 },
  { id: '2049', name: 'Chang Namkar', user_id: User.first.id, extension_id: 80 },
  { id: '2050', name: 'Nangshikha', user_id: User.first.id, extension_id: 80 },
  { id: '2051', name: 'Naymey', user_id: User.first.id, extension_id: 80 },
  { id: '2052', name: 'Ngetsu', user_id: User.first.id, extension_id: 80 },
  { id: '2053', name: 'Ngetsu Chotentsawa', user_id: User.first.id, extension_id: 80 },
  { id: '2054', name: 'Olathang', user_id: User.first.id, extension_id: 80 },
  { id: '2055', name: 'Omchuna', user_id: User.first.id, extension_id: 80 },
  { id: '2056', name: 'Pumsima', user_id: User.first.id, extension_id: 80 },
  { id: '2057', name: 'Pumtakha', user_id: User.first.id, extension_id: 80 },
  { id: '2058', name: 'Ramposhing', user_id: User.first.id, extension_id: 80 },
  { id: '2059', name: 'Rawna', user_id: User.first.id, extension_id: 80 },
  { id: '2060', name: 'Segona', user_id: User.first.id, extension_id: 80 },
  { id: '2061', name: 'Shikha', user_id: User.first.id, extension_id: 80 },
  { id: '2062', name: 'Sisitakpa', user_id: User.first.id, extension_id: 80 },
  { id: '2063', name: 'Tagokha', user_id: User.first.id, extension_id: 80 },
  { id: '2064', name: 'Taju', user_id: User.first.id, extension_id: 80 },
  { id: '2065', name: 'Tshongdu', user_id: User.first.id, extension_id: 80 },
  { id: '2066', name: 'Tshoshitsawa', user_id: User.first.id, extension_id: 80 },
  { id: '2067', name: 'Tsirena', user_id: User.first.id, extension_id: 80 },
  { id: '2068', name: 'Wochukha', user_id: User.first.id, extension_id: 80 },
  { id: '2069', name: 'Yekukha', user_id: User.first.id, extension_id: 80 },
  { id: '2070', name: 'Yoowang', user_id: User.first.id, extension_id: 80 },
  { id: '2071', name: 'Zachekha', user_id: User.first.id, extension_id: 80 },

  # Paro Thromde
  { id: '1971', name: 'Throm', user_id: User.first.id, extension_id: 81 }
].each do |v|
  Village.find_or_create_by!(v)
end
