# frozen_string_literal: true

[
  # Loong-nyi
  { id: '1807', name: 'Bondey', user_id: User.first.id, extension_id: 76 },
  { id: '1808', name: 'Dzongdra  Chetoekha', user_id: User.first.id, extension_id: 76 },
  { id: '1809', name: 'Dzongdra  Tashigang', user_id: User.first.id, extension_id: 76 },
  { id: '1810', name: 'Dzongdra bara', user_id: User.first.id, extension_id: 76 },
  { id: '1811', name: 'Dzongdra Dachu', user_id: User.first.id, extension_id: 76 },
  { id: '1812', name: 'Dzongdra Dramalo', user_id: User.first.id, extension_id: 76 },
  { id: '1813', name: 'Dzongdra Jangsarbu', user_id: User.first.id, extension_id: 76 },
  { id: '1814', name: 'Dzongdra Khapara', user_id: User.first.id, extension_id: 76 },
  { id: '1815', name: 'Dzongdra Khazhi', user_id: User.first.id, extension_id: 76 },
  { id: '1816', name: 'Dzongdra Lhakhango Kha', user_id: User.first.id, extension_id: 76 },
  { id: '1817', name: 'Dzongdra Lhashingtsa', user_id: User.first.id, extension_id: 76 },
  { id: '1818', name: 'Dzongdra shingkalachu', user_id: User.first.id, extension_id: 76 },
  { id: '1819', name: 'Dzongdra Toechochu', user_id: User.first.id, extension_id: 76 },
  { id: '1820', name: 'Dzongdra Toechoelu', user_id: User.first.id, extension_id: 76 },
  { id: '1821', name: 'Dzongdrakha', user_id: User.first.id, extension_id: 76 },
  { id: '1822', name: 'Dzongdrakha Acholakha', user_id: User.first.id, extension_id: 76 },
  { id: '1823', name: 'Gada Tshaphelo', user_id: User.first.id, extension_id: 76 },
  { id: '1824', name: 'Gadana', user_id: User.first.id, extension_id: 76 },
  { id: '1825', name: 'Gadra Achilakha', user_id: User.first.id, extension_id: 76 },
  { id: '1826', name: 'Gadra Bachina', user_id: User.first.id, extension_id: 76 },
  { id: '1827', name: 'Gadra Doleychen', user_id: User.first.id, extension_id: 76 },
  { id: '1828', name: 'Gadra Dralu', user_id: User.first.id, extension_id: 76 },
  { id: '1829', name: 'Gadra Gonim', user_id: User.first.id, extension_id: 76 },
  { id: '1830', name: 'Gadra Jangtoekha', user_id: User.first.id, extension_id: 76 },
  { id: '1831', name: 'Gadra Lambatoe', user_id: User.first.id, extension_id: 76 },
  { id: '1832', name: 'Gadra Serikha', user_id: User.first.id, extension_id: 76 },
  { id: '1833', name: 'Gadra Talung', user_id: User.first.id, extension_id: 76 },
  { id: '1834', name: 'Gadra Tshaphelo', user_id: User.first.id, extension_id: 76 },
  { id: '1835', name: 'Gadradazhikha', user_id: User.first.id, extension_id: 76 },
  { id: '1836', name: 'Jieu', user_id: User.first.id, extension_id: 76 },
  { id: '1837', name: 'Jieu Bameynyikha', user_id: User.first.id, extension_id: 76 },
  { id: '1838', name: 'Jieu Dado', user_id: User.first.id, extension_id: 76 },
  { id: '1839', name: 'Jieu Kelakha', user_id: User.first.id, extension_id: 76 },
  { id: '1840', name: 'Jieu Ridolepchen', user_id: User.first.id, extension_id: 76 },
  { id: '1841', name: 'Jieu Sasa', user_id: User.first.id, extension_id: 76 },
  { id: '1842', name: 'Jieu Serina', user_id: User.first.id, extension_id: 76 },
  { id: '1843', name: 'Jieu Shari Tshetekha', user_id: User.first.id, extension_id: 76 },
  { id: '1844', name: 'Jieu Sharigturwawog', user_id: User.first.id, extension_id: 76 },
  { id: '1845', name: 'Jieu Sharijekema', user_id: User.first.id, extension_id: 76 },
  { id: '1846', name: 'Jieu Shariling Shingtsa', user_id: User.first.id, extension_id: 76 },
  { id: '1847', name: 'Jieu Sharimenchu', user_id: User.first.id, extension_id: 76 },
  { id: '1848', name: 'Jieu Sharipotokha', user_id: User.first.id, extension_id: 76 },
  { id: '1849', name: 'Jieu Shariyarwatakpa', user_id: User.first.id, extension_id: 76 },
  { id: '1850', name: 'Jieu Shariyarwog', user_id: User.first.id, extension_id: 76 },
  { id: '1851', name: 'Jieu Tamatsa', user_id: User.first.id, extension_id: 76 },
  { id: '1852', name: 'Jieu Zhingchen', user_id: User.first.id, extension_id: 76 },
  { id: '1853', name: 'Jieu Zhingchen Thangkha', user_id: User.first.id, extension_id: 76 },
  { id: '1854', name: 'Jieu Zhongkukha', user_id: User.first.id, extension_id: 76 },
  { id: '1855', name: 'Nemjo', user_id: User.first.id, extension_id: 76 },
  { id: '1856', name: 'Nemjo Bedo', user_id: User.first.id, extension_id: 76 },
  { id: '1857', name: 'Nemjo Bedotshekha', user_id: User.first.id, extension_id: 76 },
  { id: '1858', name: 'Nemjo Chuzakha', user_id: User.first.id, extension_id: 76 },
  { id: '1859', name: 'Nemjo Dobu', user_id: User.first.id, extension_id: 76 },
  { id: '1860', name: 'Nemjo Dzongdra goenpa', user_id: User.first.id, extension_id: 76 },
  { id: '1861', name: 'Nemjo Getse', user_id: User.first.id, extension_id: 76 },
  { id: '1862', name: 'Nemjo Jangka', user_id: User.first.id, extension_id: 76 },
  { id: '1863', name: 'Nemjo Jangka Tsekha', user_id: User.first.id, extension_id: 76 },
  { id: '1864', name: 'Nemjo Jangsa', user_id: User.first.id, extension_id: 76 },
  { id: '1865', name: 'Nemjo Lamchen', user_id: User.first.id, extension_id: 76 },
  { id: '1866', name: 'Nemjo Lechukha', user_id: User.first.id, extension_id: 76 },
  { id: '1867', name: 'Nemjo Mayulkha', user_id: User.first.id, extension_id: 76 },
  { id: '1868', name: 'Nemjo Mekhu', user_id: User.first.id, extension_id: 76 },
  { id: '1869', name: 'Nemjo Nazhikha', user_id: User.first.id, extension_id: 76 },
  { id: '1870', name: 'Nemjo Pori', user_id: User.first.id, extension_id: 76 },
  { id: '1871', name: 'Nemjo Rema', user_id: User.first.id, extension_id: 76 },
  { id: '1872', name: 'Nemjo Rempori', user_id: User.first.id, extension_id: 76 },
  { id: '1873', name: 'Nemjo Riphakha', user_id: User.first.id, extension_id: 76 },
  { id: '1874', name: 'Nemjo Sekhu', user_id: User.first.id, extension_id: 76 },
  { id: '1875', name: 'Nemjo Sema', user_id: User.first.id, extension_id: 76 },
  { id: '1876', name: 'Nemjo Thangkha', user_id: User.first.id, extension_id: 76 },
  { id: '1877', name: 'Nemjo Tsedo', user_id: User.first.id, extension_id: 76 },
  { id: '1878', name: 'Nemjo Tshekha', user_id: User.first.id, extension_id: 76 },
  { id: '1879', name: 'Pangbisa', user_id: User.first.id, extension_id: 76 },
  { id: '1880', name: 'Pangbisa Atsha', user_id: User.first.id, extension_id: 76 },
  { id: '1881', name: 'Pangbisa Dzongkha', user_id: User.first.id, extension_id: 76 },
  { id: '1882', name: 'Pangbisa Dzongtsakha', user_id: User.first.id, extension_id: 76 },
  { id: '1883', name: 'Pangbisa Gemena', user_id: User.first.id, extension_id: 76 },
  { id: '1884', name: 'Pangbisa Jangsekha', user_id: User.first.id, extension_id: 76 },
  { id: '1885', name: 'Pangbisa Jangsipetsa', user_id: User.first.id, extension_id: 76 },
  { id: '1886', name: 'Pangbisa Jemphu', user_id: User.first.id, extension_id: 76 },
  { id: '1887', name: 'Pangbisa Khimchuna', user_id: User.first.id, extension_id: 76 },
  { id: '1888', name: 'Pangbisa Lhakhangna', user_id: User.first.id, extension_id: 76 },
  { id: '1889', name: 'Pangbisa Linga', user_id: User.first.id, extension_id: 76 },
  { id: '1890', name: 'Pangbisa Namchikha', user_id: User.first.id, extension_id: 76 },
  { id: '1891', name: 'Pangbisa Rangetsawa', user_id: User.first.id, extension_id: 76 },
  { id: '1892', name: 'Pangbisa Temisema', user_id: User.first.id, extension_id: 76 },
  { id: '1893', name: 'Pangbisa Tshoshithangkha', user_id: User.first.id, extension_id: 76 },
  { id: '1894', name: 'Pangbisa UgyenGuru', user_id: User.first.id, extension_id: 76 },
  { id: '1895', name: 'Pangbisa Walina', user_id: User.first.id, extension_id: 76 },
  { id: '1896', name: 'Pangbisa Wochen', user_id: User.first.id, extension_id: 76 },
  { id: '1897', name: 'Pangbisa Wolithangka', user_id: User.first.id, extension_id: 76 },
  { id: '1898', name: 'Pepchu', user_id: User.first.id, extension_id: 76 },
  { id: '1899', name: 'Wochu Damcho', user_id: User.first.id, extension_id: 76 },
  { id: '1900', name: 'Wochu Gaitsa', user_id: User.first.id, extension_id: 76 },
  { id: '1901', name: 'Wochu Gangchujab', user_id: User.first.id, extension_id: 76 },
  { id: '1902', name: 'Wochu Gangtoe', user_id: User.first.id, extension_id: 76 },
  { id: '1903', name: 'Wochu Gatsana', user_id: User.first.id, extension_id: 76 },
  { id: '1904', name: 'Wochu Gatshana', user_id: User.first.id, extension_id: 76 },
  { id: '1905', name: 'Wochu Janalu', user_id: User.first.id, extension_id: 76 },
  { id: '1906', name: 'Wochu Jangchubtoe', user_id: User.first.id, extension_id: 76 },
  { id: '1907', name: 'Wochu Jangka', user_id: User.first.id, extension_id: 76 },
  { id: '1908', name: 'Wochu Jangkaworba', user_id: User.first.id, extension_id: 76 },
  { id: '1909', name: 'Wochu Jangna', user_id: User.first.id, extension_id: 76 },
  { id: '1910', name: 'Wochu Lungbizakha', user_id: User.first.id, extension_id: 76 },
  { id: '1911', name: 'Wochu Naksshangtsa', user_id: User.first.id, extension_id: 76 },
  { id: '1912', name: 'Wochu Naktshangtsa', user_id: User.first.id, extension_id: 76 },
  { id: '1913', name: 'Wochu Omchena', user_id: User.first.id, extension_id: 76 },
  { id: '1914', name: 'Wochu Pumnang', user_id: User.first.id, extension_id: 76 },
  { id: '1915', name: 'Wochu Raselma', user_id: User.first.id, extension_id: 76 },
  { id: '1916', name: 'Wochu Renpalok', user_id: User.first.id, extension_id: 76 },
  { id: '1917', name: 'Wochu Rhizhima', user_id: User.first.id, extension_id: 76 },
  { id: '1918', name: 'Wochu Toe', user_id: User.first.id, extension_id: 76 },
  { id: '1919', name: 'Wochu Toe Ngo', user_id: User.first.id, extension_id: 76 },
  { id: '1920', name: 'Wochu Tshangpa', user_id: User.first.id, extension_id: 76 },
  { id: '1921', name: 'Wochu Tshelgona', user_id: User.first.id, extension_id: 76 },
  { id: '1922', name: 'Wochu Zhango Wongma', user_id: User.first.id, extension_id: 76 },
  { id: '1923', name: 'Wochu Zhelngo', user_id: User.first.id, extension_id: 76 },
  { id: '1924', name: 'Woochu', user_id: User.first.id, extension_id: 76 }
].each do |v|
  Village.find_or_create_by!(v)
end
