# frozen_string_literal: true

puts 'Seeding villages of Paro...'

[
  # Dokar
  { id: '1630', name: 'Bangkha', user_id: User.first.id, extension_id: 71 },
  { id: '1631', name: 'Chhuzom', user_id: User.first.id, extension_id: 71 },
  { id: '1632', name: 'Dala', user_id: User.first.id, extension_id: 71 },
  { id: '1633', name: 'Dawakha', user_id: User.first.id, extension_id: 71 },
  { id: '1634', name: 'Dongkarla', user_id: User.first.id, extension_id: 71 },
  { id: '1635', name: 'Dzongang', user_id: User.first.id, extension_id: 71 },
  { id: '1636', name: 'Dzonggang', user_id: User.first.id, extension_id: 71 },
  { id: '1637', name: 'Gajay', user_id: User.first.id, extension_id: 71 },
  { id: '1638', name: 'Gayjo', user_id: User.first.id, extension_id: 71 },
  { id: '1639', name: 'Goensakha', user_id: User.first.id, extension_id: 71 },
  { id: '1640', name: 'Issakha', user_id: User.first.id, extension_id: 71 },
  { id: '1641', name: 'Issuna', user_id: User.first.id, extension_id: 71 },
  { id: '1642', name: 'Jabisa', user_id: User.first.id, extension_id: 71 },
  { id: '1643', name: 'Jamdo', user_id: User.first.id, extension_id: 71 },
  { id: '1644', name: 'Jamdo Goma', user_id: User.first.id, extension_id: 71 },
  { id: '1645', name: 'Jamdowoma', user_id: User.first.id, extension_id: 71 },
  { id: '1646', name: 'Karphu', user_id: User.first.id, extension_id: 71 },
  { id: '1647', name: 'Khamda', user_id: User.first.id, extension_id: 71 },
  { id: '1648', name: 'Khamda Gang', user_id: User.first.id, extension_id: 71 },
  { id: '1649', name: 'Kharibji', user_id: User.first.id, extension_id: 71 },
  { id: '1650', name: 'Kharphu', user_id: User.first.id, extension_id: 71 },
  { id: '1651', name: 'Lagyel', user_id: User.first.id, extension_id: 71 },
  { id: '1652', name: 'Lomekha', user_id: User.first.id, extension_id: 71 },
  { id: '1653', name: 'Mendi Jabkha', user_id: User.first.id, extension_id: 71 },
  { id: '1654', name: 'Phuchekha', user_id: User.first.id, extension_id: 71 },
  { id: '1655', name: 'Sali', user_id: User.first.id, extension_id: 71 },
  { id: '1656', name: 'Segyelna/Karphu', user_id: User.first.id, extension_id: 71 },
  { id: '1657', name: 'Selgoen', user_id: User.first.id, extension_id: 71 },
  { id: '1658', name: 'Tamdegang', user_id: User.first.id, extension_id: 71 },
  { id: '1659', name: 'Tango', user_id: User.first.id, extension_id: 71 },
  { id: '1660', name: 'Tenchekha', user_id: User.first.id, extension_id: 71 },
  { id: '1661', name: 'Tepchugang', user_id: User.first.id, extension_id: 71 },
  { id: '1662', name: 'Totokha', user_id: User.first.id, extension_id: 71 },
  { id: '1663', name: 'Trashigang', user_id: User.first.id, extension_id: 71 },
  { id: '1664', name: 'Tsenakha', user_id: User.first.id, extension_id: 71 },
  { id: '1665', name: 'Tsephu', user_id: User.first.id, extension_id: 71 },
  { id: '1666', name: 'Tshelgang', user_id: User.first.id, extension_id: 71 },
  { id: '1667', name: 'Tshongkha', user_id: User.first.id, extension_id: 71 },

  # Dopshar-ri
  { id: '1669', name: 'Bara', user_id: User.first.id, extension_id: 72 },
  { id: '1670', name: 'Bichukha', user_id: User.first.id, extension_id: 72 },
  { id: '1671', name: 'Changdungkar', user_id: User.first.id, extension_id: 72 },
  { id: '1672', name: 'Chimakha', user_id: User.first.id, extension_id: 72 },
  { id: '1673', name: 'Damchenang', user_id: User.first.id, extension_id: 72 },
  { id: '1674', name: 'Damzhi', user_id: User.first.id, extension_id: 72 },
  { id: '1675', name: 'Damzhing', user_id: User.first.id, extension_id: 72 },
  { id: '1676', name: 'Deozhi', user_id: User.first.id, extension_id: 72 },
  { id: '1677', name: 'Hingshiwog', user_id: User.first.id, extension_id: 72 },
  { id: '1678', name: 'Jangonang', user_id: User.first.id, extension_id: 72 },
  { id: '1679', name: 'Jangsa', user_id: User.first.id, extension_id: 72 },
  { id: '1680', name: 'Jangsa Dangribu', user_id: User.first.id, extension_id: 72 },
  { id: '1681', name: 'Jangsa Darbeylo', user_id: User.first.id, extension_id: 72 },
  { id: '1682', name: 'Jangsa Drabeylo', user_id: User.first.id, extension_id: 72 },
  { id: '1683', name: 'Jangsa Jachukha', user_id: User.first.id, extension_id: 72 },
  { id: '1684', name: 'Jangsa Jachutsekha', user_id: User.first.id, extension_id: 72 },
  { id: '1685', name: 'Jangsa Karshitsha', user_id: User.first.id, extension_id: 72 },
  { id: '1686', name: 'Jangsa Nazhikha', user_id: User.first.id, extension_id: 72 },
  { id: '1687', name: 'Jangsakha', user_id: User.first.id, extension_id: 72 },
  { id: '1688', name: 'Jeshigang', user_id: User.first.id, extension_id: 72 },
  { id: '1689', name: 'Jipa', user_id: User.first.id, extension_id: 72 },
  { id: '1690', name: 'Jipa batsekha', user_id: User.first.id, extension_id: 72 },
  { id: '1691', name: 'Jipa Dorokha', user_id: User.first.id, extension_id: 72 },
  { id: '1692', name: 'Jipa Jangonang', user_id: User.first.id, extension_id: 72 },
  { id: '1693', name: 'Jipa Jangsagongma', user_id: User.first.id, extension_id: 72 },
  { id: '1694', name: 'Jipa Jangsana', user_id: User.first.id, extension_id: 72 },
  { id: '1695', name: 'Jipa Jangsanang', user_id: User.first.id, extension_id: 72 },
  { id: '1696', name: 'Jipa Khamshingwog', user_id: User.first.id, extension_id: 72 },
  { id: '1697', name: 'Jipa Khimsab', user_id: User.first.id, extension_id: 72 },
  { id: '1698', name: 'Jipa Lew', user_id: User.first.id, extension_id: 72 },
  { id: '1699', name: 'Jipa Singyedra', user_id: User.first.id, extension_id: 72 },
  { id: '1700', name: 'Jishigang', user_id: User.first.id, extension_id: 72 },
  { id: '1701', name: 'Jugang Thasukha', user_id: User.first.id, extension_id: 72 },
  { id: '1702', name: 'Jugangthatshukha', user_id: User.first.id, extension_id: 72 },
  { id: '1703', name: 'Juka', user_id: User.first.id, extension_id: 72 },
  { id: '1704', name: 'Juka Gom', user_id: User.first.id, extension_id: 72 },
  { id: '1705', name: 'Juka Khimsabu', user_id: User.first.id, extension_id: 72 },
  { id: '1706', name: 'Juka Shangzhikha', user_id: User.first.id, extension_id: 72 },
  { id: '1707', name: 'Juka Thangkha', user_id: User.first.id, extension_id: 72 },
  { id: '1708', name: 'Kempa', user_id: User.first.id, extension_id: 72 },
  { id: '1709', name: 'Kempa Bamizhikha', user_id: User.first.id, extension_id: 72 },
  { id: '1710', name: 'Kempa Changyalkha', user_id: User.first.id, extension_id: 72 },
  { id: '1711', name: 'Kempa Dolukha', user_id: User.first.id, extension_id: 72 },
  { id: '1712', name: 'Kempa Jangsana', user_id: User.first.id, extension_id: 72 },
  { id: '1713', name: 'Kempa Jangsunang', user_id: User.first.id, extension_id: 72 },
  { id: '1714', name: 'Kempa Jomonang', user_id: User.first.id, extension_id: 72 },
  { id: '1715', name: 'kempa Khimsarbu', user_id: User.first.id, extension_id: 72 },
  { id: '1716', name: 'Kempa Kuduphu', user_id: User.first.id, extension_id: 72 },
  { id: '1717', name: 'Kempa Lungkha', user_id: User.first.id, extension_id: 72 },
  { id: '1718', name: 'Kempa Phatom', user_id: User.first.id, extension_id: 72 },
  { id: '1719', name: 'Kempa Phenshing Zhikha', user_id: User.first.id, extension_id: 72 },
  { id: '1720', name: 'Kempa Pidikha', user_id: User.first.id, extension_id: 72 },
  { id: '1721', name: 'Kempa Rimdotsekha', user_id: User.first.id, extension_id: 72 },
  { id: '1722', name: 'Kempa Tshozakha', user_id: User.first.id, extension_id: 72 },
  { id: '1723', name: 'Kempa Tshozarkha', user_id: User.first.id, extension_id: 72 },
  { id: '1724', name: 'Kempa Zorikha', user_id: User.first.id, extension_id: 72 },
  { id: '1725', name: 'Kuduphu', user_id: User.first.id, extension_id: 72 },
  { id: '1726', name: 'Kuduphu Kotsha', user_id: User.first.id, extension_id: 72 },
  { id: '1727', name: 'Nazhikha', user_id: User.first.id, extension_id: 72 },
  { id: '1728', name: 'Rabnang', user_id: User.first.id, extension_id: 72 },
  { id: '1729', name: 'Ramnang', user_id: User.first.id, extension_id: 72 },
  { id: '1730', name: 'Richukha', user_id: User.first.id, extension_id: 72 },
  { id: '1731', name: 'Riju', user_id: User.first.id, extension_id: 72 },
  { id: '1732', name: 'Rijukha', user_id: User.first.id, extension_id: 72 },
  { id: '1733', name: 'Rijukrima', user_id: User.first.id, extension_id: 72 },
  { id: '1734', name: 'Rimdo Kempa', user_id: User.first.id, extension_id: 72 },
  { id: '1735', name: 'Rinchending', user_id: User.first.id, extension_id: 72 },
  { id: '1736', name: 'Rotogang', user_id: User.first.id, extension_id: 72 },
  { id: '1737', name: 'Samakha', user_id: User.first.id, extension_id: 72 },
  { id: '1738', name: 'Sephu Jishigang', user_id: User.first.id, extension_id: 72 },
  { id: '1739', name: 'Shari', user_id: User.first.id, extension_id: 72 },
  { id: '1740', name: 'Tadinkha', user_id: User.first.id, extension_id: 72 },
  { id: '1741', name: 'Thangkana', user_id: User.first.id, extension_id: 72 },
  { id: '1742', name: 'Totokha', user_id: User.first.id, extension_id: 72 },
  { id: '1743', name: 'Zhikha', user_id: User.first.id, extension_id: 72 }
].each do |v|
  Village.find_or_create_by!(v)
end
