# frozen_string_literal: true

[
  # Doteng
  { id: '1745', name: 'Atso', user_id: User.first.id, extension_id: 73 },
  { id: '1746', name: 'Chindu Genpa', user_id: User.first.id, extension_id: 73 },
  { id: '1747', name: 'Chubar', user_id: User.first.id, extension_id: 73 },
  { id: '1748', name: 'Jabjee', user_id: User.first.id, extension_id: 73 },
  { id: '1749', name: 'Jukar', user_id: User.first.id, extension_id: 73 },
  { id: '1750', name: 'Jukar Tsekha', user_id: User.first.id, extension_id: 73 },
  { id: '1751', name: 'Lukche', user_id: User.first.id, extension_id: 73 },
  { id: '1752', name: 'Pachu', user_id: User.first.id, extension_id: 73 },
  { id: '1753', name: 'Pangbisa', user_id: User.first.id, extension_id: 73 },
  { id: '1754', name: 'Phunu', user_id: User.first.id, extension_id: 73 },
  { id: '1755', name: 'Phushar', user_id: User.first.id, extension_id: 73 },

  # Hoongrel
  { id: '1757', name: 'Changsima', user_id: User.first.id, extension_id: 74 },
  { id: '1758', name: 'Chubjakha', user_id: User.first.id, extension_id: 74 },
  { id: '1759', name: 'Chukhozakha', user_id: User.first.id, extension_id: 74 },
  { id: '1760', name: 'Donamo', user_id: User.first.id, extension_id: 74 },
  { id: '1761', name: 'Drukgyeling', user_id: User.first.id, extension_id: 74 },
  { id: '1762', name: 'Gaupay', user_id: User.first.id, extension_id: 74 },
  { id: '1763', name: 'Gida/Shongna', user_id: User.first.id, extension_id: 74 },
  { id: '1764', name: 'Goenkha', user_id: User.first.id, extension_id: 74 },
  { id: '1765', name: 'Hungrelkha', user_id: User.first.id, extension_id: 74 },
  { id: '1766', name: 'Hungrelkha/Changkhor', user_id: User.first.id, extension_id: 74 },
  { id: '1767', name: 'Hungrelkha/Namizampa', user_id: User.first.id, extension_id: 74 },
  { id: '1768', name: 'Jangmeyna', user_id: User.first.id, extension_id: 74 },
  { id: '1769', name: 'Jangsarbu', user_id: User.first.id, extension_id: 74 },
  { id: '1770', name: 'Lungchuna', user_id: User.first.id, extension_id: 74 },
  { id: '1771', name: 'Lungchuna/Zori Goenpa', user_id: User.first.id, extension_id: 74 },
  { id: '1772', name: 'Nangshikha', user_id: User.first.id, extension_id: 74 },
  { id: '1773', name: 'Tshongdu', user_id: User.first.id, extension_id: 74 },

  # Lamgong
  { id: '1775', name: 'Chukha', user_id: User.first.id, extension_id: 75 },
  { id: '1776', name: 'Darkhang', user_id: User.first.id, extension_id: 75 },
  { id: '1777', name: 'Dharkhang', user_id: User.first.id, extension_id: 75 },
  { id: '1778', name: 'Gangju', user_id: User.first.id, extension_id: 75 },
  { id: '1779', name: 'Jaga Thangtoe', user_id: User.first.id, extension_id: 75 },
  { id: '1780', name: 'Jaga Thangtoe/Gyetazam', user_id: User.first.id, extension_id: 75 },
  { id: '1781', name: 'Jaga Thangtoed', user_id: User.first.id, extension_id: 75 },
  { id: '1782', name: 'Jagar Thangmey', user_id: User.first.id, extension_id: 75 },
  { id: '1783', name: 'Jagar Thangtoe', user_id: User.first.id, extension_id: 75 },
  { id: '1784', name: 'JagarThangme', user_id: User.first.id, extension_id: 75 },
  { id: '1785', name: 'JagarThangtoed', user_id: User.first.id, extension_id: 75 },
  { id: '1786', name: 'JagarThangtoed/Darkhang', user_id: User.first.id, extension_id: 75 },
  { id: '1787', name: 'Kichu', user_id: User.first.id, extension_id: 75 },
  { id: '1788', name: 'Ngopa', user_id: User.first.id, extension_id: 75 },
  { id: '1789', name: 'Nubri', user_id: User.first.id, extension_id: 75 },
  { id: '1790', name: 'Sergang', user_id: User.first.id, extension_id: 75 },
  { id: '1791', name: 'Shomo', user_id: User.first.id, extension_id: 75 },
  { id: '1792', name: 'Soe', user_id: User.first.id, extension_id: 75 },
  { id: '1793', name: 'Soe Yaksa', user_id: User.first.id, extension_id: 75 },
  { id: '1794', name: 'Soey Yaksha', user_id: User.first.id, extension_id: 75 },
  { id: '1795', name: 'Tsendanang', user_id: User.first.id, extension_id: 75 },
  { id: '1796', name: 'Tsendona', user_id: User.first.id, extension_id: 75 },
  { id: '1797', name: 'Tsendonang', user_id: User.first.id, extension_id: 75 },
  { id: '1798', name: 'Tsenthang', user_id: User.first.id, extension_id: 75 },
  { id: '1799', name: 'Tsenthang Bartshik', user_id: User.first.id, extension_id: 75 },
  { id: '1800', name: 'Tsenthang Dokha', user_id: User.first.id, extension_id: 75 },
  { id: '1801', name: 'Tsenthang Gepkha', user_id: User.first.id, extension_id: 75 },
  { id: '1802', name: 'Tsenthang Geptsha', user_id: User.first.id, extension_id: 75 },
  { id: '1803', name: 'Tsenthang Sharhikha', user_id: User.first.id, extension_id: 75 },
  { id: '1804', name: 'Tsenthang Thangtoed', user_id: User.first.id, extension_id: 75 },
  { id: '1805', name: 'Tsenthang toed', user_id: User.first.id, extension_id: 75 },

  # Nagya
  { id: '1926', name: 'Betekha', user_id: User.first.id, extension_id: 77 },
  { id: '1927', name: 'Betekha/Tabjo', user_id: User.first.id, extension_id: 77 },
  { id: '1928', name: 'Jadokha', user_id: User.first.id, extension_id: 77 },
  { id: '1929', name: 'Jagoen', user_id: User.first.id, extension_id: 77 },
  { id: '1930', name: 'Jagoen/Betekha', user_id: User.first.id, extension_id: 77 },
  { id: '1931', name: 'Jaleykha', user_id: User.first.id, extension_id: 77 },
  { id: '1932', name: 'Jeleykha', user_id: User.first.id, extension_id: 77 },
  { id: '1933', name: 'Lingshi', user_id: User.first.id, extension_id: 77 },
  { id: '1934', name: 'Nagu', user_id: User.first.id, extension_id: 77 },
  { id: '1935', name: 'Nagu/Pherukha', user_id: User.first.id, extension_id: 77 },
  { id: '1936', name: 'Rangshigang', user_id: User.first.id, extension_id: 77 },
  { id: '1937', name: 'Tshebji', user_id: User.first.id, extension_id: 77 },
  { id: '1938', name: 'Tshegoan', user_id: User.first.id, extension_id: 77 },
  { id: '1939', name: 'Tshegoen', user_id: User.first.id, extension_id: 77 },
  { id: '1940', name: 'Zusuna', user_id: User.first.id, extension_id: 77 },
  { id: '1941', name: 'Jashina', user_id: User.first.id, extension_id: 77 },
  { id: '1942', name: 'Tshendu Goenpa', user_id: User.first.id, extension_id: 77 },
  { id: '1943', name: 'Tokhab', user_id: User.first.id, extension_id: 77 },
  { id: '1944', name: 'Wanakha', user_id: User.first.id, extension_id: 77 },
  { id: '1945', name: 'Bemphu', user_id: User.first.id, extension_id: 77 },

  # Sharpa
  { id: '1947', name: 'Bara', user_id: User.first.id, extension_id: 78 },
  { id: '1948', name: 'Bara Serina', user_id: User.first.id, extension_id: 78 },
  { id: '1949', name: 'Bara Tashichholing', user_id: User.first.id, extension_id: 78 },
  { id: '1950', name: 'Bara Zhingo', user_id: User.first.id, extension_id: 78 },
  { id: '1951', name: 'Barakempa', user_id: User.first.id, extension_id: 78 },
  { id: '1952', name: 'Baratokha', user_id: User.first.id, extension_id: 78 },
  { id: '1953', name: 'Drugyeldingkha', user_id: User.first.id, extension_id: 78 },
  { id: '1954', name: 'Gangri', user_id: User.first.id, extension_id: 78 },
  { id: '1955', name: 'Lholing', user_id: User.first.id, extension_id: 78 },
  { id: '1956', name: 'Naychu', user_id: User.first.id, extension_id: 78 },
  { id: '1957', name: 'Neyphu', user_id: User.first.id, extension_id: 78 },
  { id: '1958', name: 'Shungkarna', user_id: User.first.id, extension_id: 78 },
  { id: '1959', name: 'Teli', user_id: User.first.id, extension_id: 78 },
  { id: '1960', name: 'Yongkarna', user_id: User.first.id, extension_id: 78 },
  { id: '1961', name: 'Zhelngo', user_id: User.first.id, extension_id: 78 },
  { id: '1962', name: 'Zhungkarna', user_id: User.first.id, extension_id: 78 },
  { id: '1963', name: 'Bjishikha', user_id: User.first.id, extension_id: 78 },
  { id: '1964', name: 'Chesham', user_id: User.first.id, extension_id: 78 },
  { id: '1965', name: 'Chukha', user_id: User.first.id, extension_id: 78 },
  { id: '1966', name: 'Gangjukha', user_id: User.first.id, extension_id: 78 },
  { id: '1967', name: 'Khasuna', user_id: User.first.id, extension_id: 78 },
  { id: '1968', name: 'Phubana', user_id: User.first.id, extension_id: 78 },
  { id: '1969', name: 'Siluna', user_id: User.first.id, extension_id: 22 }
].each do |v|
  Village.find_or_create_by!(v)
end
