# frozen_string_literal: true

puts 'Seeding villages of Pema Gatshel...'

[
  # Chhoekhorling
  { id: '2172', name: 'Arden', user_id: User.first.id, extension_id: 82 },
  { id: '2173', name: 'Chhoekhorling', user_id: User.first.id, extension_id: 82 },
  { id: '2174', name: 'Dezama', user_id: User.first.id, extension_id: 82 },
  { id: '2175', name: 'Kerong', user_id: User.first.id, extension_id: 82 },
  { id: '2176', name: 'Yarjeywoong', user_id: User.first.id, extension_id: 82 },

  # Chhimoong
  { id: '2074', name: 'Chimung', user_id: User.first.id, extension_id: 83 },
  { id: '2075', name: 'Chiphung', user_id: User.first.id, extension_id: 83 },
  { id: '2076', name: 'Longkholom', user_id: User.first.id, extension_id: 83 },
  { id: '2077', name: 'Ngaskhar', user_id: User.first.id, extension_id: 83 },
  { id: '2078', name: 'Pangthang', user_id: User.first.id, extension_id: 83 },
  { id: '2079', name: 'Redingla', user_id: User.first.id, extension_id: 83 },

  # Chongshing
  { id: '2081', name: 'Chongshing', user_id: User.first.id, extension_id: 84 },
  { id: '2082', name: 'Guyoum', user_id: User.first.id, extension_id: 84 },
  { id: '2083', name: 'Jorphung', user_id: User.first.id, extension_id: 84 },
  { id: '2084', name: 'Kalishong', user_id: User.first.id, extension_id: 84 },
  { id: '2085', name: 'Lanangzor', user_id: User.first.id, extension_id: 84 },
  { id: '2086', name: 'Mandi', user_id: User.first.id, extension_id: 84 },
  { id: '2087', name: 'Thongsa', user_id: User.first.id, extension_id: 84 },
  { id: '2088', name: 'Yomzor', user_id: User.first.id, extension_id: 84 },

  # Dechhenling
  { id: '2178', name: 'Babta', user_id: User.first.id, extension_id: 85 },
  { id: '2179', name: 'Dungphu Gonpa(Ngangrey/Yebashing)', user_id: User.first.id, extension_id: 85 },
  { id: '2180', name: 'Gonpawoong', user_id: User.first.id, extension_id: 85 },
  { id: '2181', name: 'Kholomri', user_id: User.first.id, extension_id: 85 },
  { id: '2182', name: 'Namdaling(Kulamanti)', user_id: User.first.id, extension_id: 85 },
  { id: '2183', name: 'Dechhenling(Martshala)', user_id: User.first.id, extension_id: 85 },
  { id: '2184', name: 'Rezomo(Mongar)', user_id: User.first.id, extension_id: 85 },
  { id: '2185', name: 'Rognowang', user_id: User.first.id, extension_id: 85 },
  { id: '2186', name: 'Shingchongri', user_id: User.first.id, extension_id: 85 },
  { id: '2187', name: 'Mendelgang(Yangmalashing/Kherbari)', user_id: User.first.id, extension_id: 85 },
  { id: '2188', name: 'Pelinthang(Nachbandar)', user_id: User.first.id, extension_id: 85 },

  # Dungmaed
  { id: '2090', name: 'Aumshing', user_id: User.first.id, extension_id: 86 },
  { id: '2091', name: 'Bangyul', user_id: User.first.id, extension_id: 86 },
  { id: '2092', name: 'Belna Geonpa', user_id: User.first.id, extension_id: 86 },
  { id: '2093', name: 'Belnangzor', user_id: User.first.id, extension_id: 86 },
  { id: '2094', name: 'Dungmin', user_id: User.first.id, extension_id: 86 },
  { id: '2095', name: 'Laneri', user_id: User.first.id, extension_id: 86 },
  { id: '2096', name: 'Leydung', user_id: User.first.id, extension_id: 86 },
  { id: '2097', name: 'Mangthari', user_id: User.first.id, extension_id: 86 },
  { id: '2098', name: 'Meuri', user_id: User.first.id, extension_id: 86 },
  { id: '2099', name: 'Mikuri', user_id: User.first.id, extension_id: 86 },
  { id: '2100', name: 'Tep Tep La', user_id: User.first.id, extension_id: 86 },
  { id: '2101', name: 'Thumchung', user_id: User.first.id, extension_id: 86 },
  { id: '2102', name: 'Tomi', user_id: User.first.id, extension_id: 86 },
  { id: '2103', name: 'Womborang', user_id: User.first.id, extension_id: 86 },
  { id: '2104', name: 'Zimzor', user_id: User.first.id, extension_id: 86 },

  # Khar
  { id: '2106', name: 'Bongmun', user_id: User.first.id, extension_id: 87 },
  { id: '2107', name: 'Duewang', user_id: User.first.id, extension_id: 87 },
  { id: '2108', name: 'Khar', user_id: User.first.id, extension_id: 87 },
  { id: '2109', name: 'Khawar', user_id: User.first.id, extension_id: 87 },
  { id: '2110', name: 'Khengzor', user_id: User.first.id, extension_id: 87 },
  { id: '2111', name: 'Labar', user_id: User.first.id, extension_id: 87 },
  { id: '2112', name: 'Nagtsheri', user_id: User.first.id, extension_id: 87 },
  { id: '2113', name: 'Phadi', user_id: User.first.id, extension_id: 87 },
  { id: '2114', name: 'Regi', user_id: User.first.id, extension_id: 87 },
  { id: '2115', name: 'Shemshem', user_id: User.first.id, extension_id: 87 },
  { id: '2116', name: 'Shinangre', user_id: User.first.id, extension_id: 87 },
  { id: '2117', name: 'Tsebar', user_id: User.first.id, extension_id: 87 },
  { id: '2118', name: 'Yajur', user_id: User.first.id, extension_id: 87 },
  { id: '2119', name: 'Zordung', user_id: User.first.id, extension_id: 87 },

  # Nanong
  { id: '2190', name: 'Bainang Chur', user_id: User.first.id, extension_id: 88 },
  { id: '2191', name: 'Bainang Tang', user_id: User.first.id, extension_id: 88 },
  { id: '2192', name: 'Balangnang', user_id: User.first.id, extension_id: 88 },
  { id: '2193', name: 'Bargoenpa', user_id: User.first.id, extension_id: 88 },
  { id: '2194', name: 'Barkadung', user_id: User.first.id, extension_id: 88 },
  { id: '2195', name: 'Borphu', user_id: User.first.id, extension_id: 88 },
  { id: '2196', name: 'Champhari', user_id: User.first.id, extension_id: 88 },
  { id: '2197', name: 'Chotenkor', user_id: User.first.id, extension_id: 88 },
  { id: '2198', name: 'Denphu', user_id: User.first.id, extension_id: 88 },
  { id: '2199', name: 'Dhalung', user_id: User.first.id, extension_id: 88 },
  { id: '2200', name: 'Dingri', user_id: User.first.id, extension_id: 88 },
  { id: '2201', name: 'Dongtsheri', user_id: User.first.id, extension_id: 88 },
  { id: '2202', name: 'Drangsa Wong', user_id: User.first.id, extension_id: 88 },
  { id: '2203', name: 'Gayri', user_id: User.first.id, extension_id: 88 },
  { id: '2204', name: 'Ghashing Khar', user_id: User.first.id, extension_id: 88 },
  { id: '2205', name: 'Ghorkaling', user_id: User.first.id, extension_id: 88 },
  { id: '2206', name: 'Gongkaling', user_id: User.first.id, extension_id: 88 },
  { id: '2207', name: 'Jangray', user_id: User.first.id, extension_id: 88 },
  { id: '2208', name: 'Jazung', user_id: User.first.id, extension_id: 88 },
  { id: '2209', name: 'Jomgom', user_id: User.first.id, extension_id: 88 },
  { id: '2210', name: 'Kapurung', user_id: User.first.id, extension_id: 88 },
  { id: '2211', name: 'Khangmari', user_id: User.first.id, extension_id: 88 },
  { id: '2212', name: 'Khay Khar', user_id: User.first.id, extension_id: 88 },
  { id: '2213', name: 'Kheshingri', user_id: User.first.id, extension_id: 88 },
  { id: '2214', name: 'Kheydong', user_id: User.first.id, extension_id: 88 },
  { id: '2215', name: 'Kulung', user_id: User.first.id, extension_id: 88 },
  { id: '2216', name: 'Laypheri', user_id: User.first.id, extension_id: 88 },
  { id: '2217', name: 'Lumri', user_id: User.first.id, extension_id: 88 },
  { id: '2218', name: 'Maygamri', user_id: User.first.id, extension_id: 88 },
  { id: '2219', name: 'Menjung', user_id: User.first.id, extension_id: 88 },
  { id: '2220', name: 'Menphu', user_id: User.first.id, extension_id: 88 },
  { id: '2221', name: 'Mongthung', user_id: User.first.id, extension_id: 88 },
  { id: '2222', name: 'Muna', user_id: User.first.id, extension_id: 88 },
  { id: '2223', name: 'Nanong', user_id: User.first.id, extension_id: 88 },
  { id: '2224', name: 'Panglap Thongma', user_id: User.first.id, extension_id: 88 },
  { id: '2225', name: 'Pangthang', user_id: User.first.id, extension_id: 88 },
  { id: '2226', name: 'Phalamphu', user_id: User.first.id, extension_id: 88 },
  { id: '2227', name: 'Raling', user_id: User.first.id, extension_id: 88 },
  { id: '2228', name: 'Rangshi Gayri', user_id: User.first.id, extension_id: 88 },
  { id: '2229', name: 'Rangshi Goenpa', user_id: User.first.id, extension_id: 88 },
  { id: '2230', name: 'Rangthang Wong', user_id: User.first.id, extension_id: 88 },
  { id: '2231', name: 'Rashu Goenpa', user_id: User.first.id, extension_id: 88 },
  { id: '2232', name: 'Rayzor', user_id: User.first.id, extension_id: 88 },
  { id: '2233', name: 'Relung', user_id: User.first.id, extension_id: 88 },
  { id: '2234', name: 'Sa Yul', user_id: User.first.id, extension_id: 88 },
  { id: '2235', name: 'Sangshing Tang', user_id: User.first.id, extension_id: 88 },
  { id: '2236', name: 'Sayri', user_id: User.first.id, extension_id: 88 },
  { id: '2237', name: 'Sayrimkha', user_id: User.first.id, extension_id: 88 },
  { id: '2238', name: 'Tearphu', user_id: User.first.id, extension_id: 88 },
  { id: '2239', name: 'Thongshing Gag', user_id: User.first.id, extension_id: 88 },
  { id: '2240', name: 'Thongthung', user_id: User.first.id, extension_id: 88 },
  { id: '2241', name: 'Thongthung Goenpa', user_id: User.first.id, extension_id: 88 },
  { id: '2242', name: 'Thorkhar', user_id: User.first.id, extension_id: 88 },
  { id: '2243', name: 'Thrangshing', user_id: User.first.id, extension_id: 88 },
  { id: '2244', name: 'Tokari', user_id: User.first.id, extension_id: 88 },
  { id: '2245', name: 'Tokari Gayri', user_id: User.first.id, extension_id: 88 },
  { id: '2246', name: 'Tshatshi', user_id: User.first.id, extension_id: 88 },
  { id: '2247', name: 'Wongchelo', user_id: User.first.id, extension_id: 88 },
  { id: '2248', name: 'Wouling Tang', user_id: User.first.id, extension_id: 88 },
  { id: '2249', name: 'Zhingri', user_id: User.first.id, extension_id: 88 }
].each do |v|
  Village.find_or_create_by!(v)
end
