# frozen_string_literal: true

puts 'Seeding villages of Punakha...'

[
  # Barp
  { id: '2585', name: 'Boemena', user_id: User.first.id, extension_id: 94 },
  { id: '2586', name: 'Chasa', user_id: User.first.id, extension_id: 94 },
  { id: '2587', name: 'Choezhekha', user_id: User.first.id, extension_id: 94 },
  { id: '2588', name: 'Dechen Ding Kha', user_id: User.first.id, extension_id: 94 },
  { id: '2589', name: 'Dosega', user_id: User.first.id, extension_id: 94 },
  { id: '2590', name: 'Gamaluma', user_id: User.first.id, extension_id: 94 },
  { id: '2591', name: 'Gamkha', user_id: User.first.id, extension_id: 94 },
  { id: '2592', name: 'Gangkha', user_id: User.first.id, extension_id: 94 },
  { id: '2593', name: 'Goenchukha', user_id: User.first.id, extension_id: 94 },
  { id: '2594', name: 'Jalung', user_id: User.first.id, extension_id: 94 },
  { id: '2595', name: 'Laphuna', user_id: User.first.id, extension_id: 94 },
  { id: '2596', name: 'Lobesa', user_id: User.first.id, extension_id: 94 },
  { id: '2597', name: 'Lumina', user_id: User.first.id, extension_id: 94 },
  { id: '2598', name: 'Martolungchu', user_id: User.first.id, extension_id: 94 },
  { id: '2599', name: 'Menchuzakha', user_id: User.first.id, extension_id: 94 },
  { id: '2600', name: 'Metshena', user_id: User.first.id, extension_id: 94 },
  { id: '2601', name: 'Pacheykha', user_id: User.first.id, extension_id: 94 },
  { id: '2602', name: 'Phuntshoyangkhel', user_id: User.first.id, extension_id: 94 },
  { id: '2603', name: 'Sebjeekha', user_id: User.first.id, extension_id: 94 },
  { id: '2604', name: 'Siptokha', user_id: User.first.id, extension_id: 94 },
  { id: '2605', name: 'Sobsokha', user_id: User.first.id, extension_id: 94 },
  { id: '2606', name: 'Tongde Bay Kha', user_id: User.first.id, extension_id: 94 },
  { id: '2607', name: 'Tshokhana', user_id: User.first.id, extension_id: 94 },
  { id: '2608', name: 'Wangjokha', user_id: User.first.id, extension_id: 94 },
  { id: '2609', name: 'Youwakha', user_id: User.first.id, extension_id: 94 },
  { id: '2610', name: 'Yusakha', user_id: User.first.id, extension_id: 94 },
  { id: '2611', name: 'Zheekha', user_id: User.first.id, extension_id: 94 },
  { id: '2612', name: 'Motokha', user_id: User.first.id, extension_id: 94 },

  # Dzomi
  { id: '2282', name: 'Bidongkha', user_id: User.first.id, extension_id: 96 },
  { id: '2283', name: 'Changjokha', user_id: User.first.id, extension_id: 96 },
  { id: '2284', name: 'Chekakha', user_id: User.first.id, extension_id: 96 },
  { id: '2285', name: 'Danamo', user_id: User.first.id, extension_id: 96 },
  { id: '2286', name: 'Darwakha', user_id: User.first.id, extension_id: 96 },
  { id: '2287', name: 'Dzomsa', user_id: User.first.id, extension_id: 96 },
  { id: '2288', name: 'Gobji', user_id: User.first.id, extension_id: 96 },
  { id: '2289', name: 'Jangsar', user_id: User.first.id, extension_id: 96 },
  { id: '2290', name: 'Jangsarbu', user_id: User.first.id, extension_id: 96 },
  { id: '2291', name: 'Jara', user_id: User.first.id, extension_id: 96 },
  { id: '2292', name: 'Jarakha', user_id: User.first.id, extension_id: 96 },
  { id: '2293', name: 'Jasha Geonpa', user_id: User.first.id, extension_id: 96 },
  { id: '2294', name: 'Jimthang', user_id: User.first.id, extension_id: 96 },
  { id: '2295', name: 'Jopkha', user_id: User.first.id, extension_id: 96 },
  { id: '2296', name: 'Khabakha', user_id: User.first.id, extension_id: 96 },
  { id: '2297', name: 'Khilikha', user_id: User.first.id, extension_id: 96 },
  { id: '2298', name: 'Likashong', user_id: User.first.id, extension_id: 96 },
  { id: '2299', name: 'Lungkha', user_id: User.first.id, extension_id: 96 },
  { id: '2300', name: 'Lungkhajang', user_id: User.first.id, extension_id: 96 },
  { id: '2301', name: 'Medhagang', user_id: User.first.id, extension_id: 96 },
  { id: '2302', name: 'Samdingkha', user_id: User.first.id, extension_id: 96 },
  { id: '2303', name: 'Tamidamchu', user_id: User.first.id, extension_id: 96 },
  { id: '2304', name: 'Tana', user_id: User.first.id, extension_id: 96 },
  { id: '2305', name: 'Thangzhi', user_id: User.first.id, extension_id: 96 },
  { id: '2306', name: 'Tseykakha', user_id: User.first.id, extension_id: 96 },
  { id: '2307', name: 'Wangkha', user_id: User.first.id, extension_id: 96 },
  { id: '2308', name: 'Yangchenkha', user_id: User.first.id, extension_id: 96 },
  { id: '2309', name: 'Yusakha', user_id: User.first.id, extension_id: 96 },
  { id: '2310', name: 'Jozhe Goenpa', user_id: User.first.id, extension_id: 96 },

  # Goenshari
  { id: '2312', name: 'Drachukha', user_id: User.first.id, extension_id: 97 },
  { id: '2313', name: 'Gumgang', user_id: User.first.id, extension_id: 97 },
  { id: '2314', name: 'Sechunang', user_id: User.first.id, extension_id: 97 },
  { id: '2315', name: 'Sechunang Rimchu', user_id: User.first.id, extension_id: 97 },
  { id: '2316', name: 'Youbu', user_id: User.first.id, extension_id: 97 },
  { id: '2317', name: 'Zhengosa', user_id: User.first.id, extension_id: 97 },

  # Guma
  { id: '2319', name: 'Bemsesi', user_id: User.first.id, extension_id: 98 },
  { id: '2320', name: 'Bemsesi Khuru', user_id: User.first.id, extension_id: 98 },
  { id: '2321', name: 'Dochokha', user_id: User.first.id, extension_id: 98 },
  { id: '2322', name: 'Dochokha Bangmena', user_id: User.first.id, extension_id: 98 },
  { id: '2323', name: 'Dochokha Gogoenpa', user_id: User.first.id, extension_id: 98 },
  { id: '2324', name: 'Dochokha Menchugang', user_id: User.first.id, extension_id: 98 },
  { id: '2325', name: 'Dochokha Phaduna', user_id: User.first.id, extension_id: 98 },
  { id: '2326', name: 'Dochokha Ritsa', user_id: User.first.id, extension_id: 98 },
  { id: '2327', name: 'Dochokha Ritsa Tongsana', user_id: User.first.id, extension_id: 98 },
  { id: '2328', name: 'Dochokha Tongsana', user_id: User.first.id, extension_id: 98 },
  { id: '2329', name: 'Gumakha', user_id: User.first.id, extension_id: 98 },
  { id: '2330', name: 'Jangsa', user_id: User.first.id, extension_id: 98 },
  { id: '2331', name: 'Khuru', user_id: User.first.id, extension_id: 98 },
  { id: '2332', name: 'Khuru Bemsesi', user_id: User.first.id, extension_id: 98 },
  { id: '2333', name: 'Khuru Bemsesi Washegang', user_id: User.first.id, extension_id: 98 },
  { id: '2334', name: 'Lakhu', user_id: User.first.id, extension_id: 98 },
  { id: '2335', name: 'Lakhu Patari', user_id: User.first.id, extension_id: 98 },
  { id: '2336', name: 'Wolajangsa Gumagangchu', user_id: User.first.id, extension_id: 98 },
  { id: '2337', name: 'Woolakha', user_id: User.first.id, extension_id: 98 },
  { id: '2338', name: 'Zamdongkhar', user_id: User.first.id, extension_id: 98 },
  { id: '2339', name: 'Zamdongkhar Bebigachha', user_id: User.first.id, extension_id: 98 },
  { id: '2340', name: 'Zamdongkhar Bebigar', user_id: User.first.id, extension_id: 98 },
  { id: '2341', name: 'Zamdongkhar Bebigarkha', user_id: User.first.id, extension_id: 98 },
  { id: '2342', name: 'Zamdongkhar Changyul', user_id: User.first.id, extension_id: 98 },
  { id: '2343', name: 'Zamdongkhar Dekiling', user_id: User.first.id, extension_id: 98 },
  { id: '2344', name: 'Zamdongkhar Dongkuju', user_id: User.first.id, extension_id: 98 },
  { id: '2345', name: 'Zamdongkhar Dumkana', user_id: User.first.id, extension_id: 98 },
  { id: '2346', name: 'Zamdongkhar Gaupay', user_id: User.first.id, extension_id: 98 },
  { id: '2347', name: 'Zamdongkhar Laykha', user_id: User.first.id, extension_id: 98 },
  { id: '2348', name: 'Zamdongkhar Lekithang', user_id: User.first.id, extension_id: 98 },
  { id: '2349', name: 'Zamdongkhar Logodama', user_id: User.first.id, extension_id: 98 },
  { id: '2350', name: 'Zamdongkhar Lunakha', user_id: User.first.id, extension_id: 98 },
  { id: '2351', name: 'Zamdongkhar Lungsigang', user_id: User.first.id, extension_id: 98 },
  { id: '2352', name: 'Zamdongkhar Pangalay', user_id: User.first.id, extension_id: 98 },
  { id: '2353', name: 'Zamdongkhar Selipang', user_id: User.first.id, extension_id: 98 },
  { id: '2354', name: 'Zamdongkhar Simtogangchu', user_id: User.first.id, extension_id: 98 },
  { id: '2355', name: 'Zamdongkhar Taba Chorten', user_id: User.first.id, extension_id: 98 },
  { id: '2356', name: 'Zamdongkhar Tashijong', user_id: User.first.id, extension_id: 98 },
  { id: '2357', name: 'Zamdongkhar Thara', user_id: User.first.id, extension_id: 98 },
  { id: '2358', name: 'Zamdongkhar Tshendengang', user_id: User.first.id, extension_id: 98 },
  { id: '2359', name: 'Zamdongkhar Yungu', user_id: User.first.id, extension_id: 98 },
  { id: '2360', name: 'Zamdongkhar Zingchey', user_id: User.first.id, extension_id: 98 },
  { id: '2361', name: 'Seodrangsa', user_id: User.first.id, extension_id: 98 },
  { id: '2362', name: 'Zamdongkhar Gumgang', user_id: User.first.id, extension_id: 98 },
  { id: '2363', name: 'Dzomlithang', user_id: User.first.id, extension_id: 98 },
  { id: '2364', name: 'Dongkokha Pepchu', user_id: User.first.id, extension_id: 98 },
  { id: '2365', name: 'Darchargang', user_id: User.first.id, extension_id: 98 },
  { id: '2366', name: 'Nyarugang', user_id: User.first.id, extension_id: 98 },
  { id: '2367', name: 'Zerkha', user_id: User.first.id, extension_id: 98 },
  { id: '2368', name: 'Drangwana', user_id: User.first.id, extension_id: 98 },
  { id: '2369', name: 'Botolo', user_id: User.first.id, extension_id: 98 },
  { id: '2370', name: 'Pangmarp', user_id: User.first.id, extension_id: 98 },
  { id: '2371', name: 'Pachaykha', user_id: User.first.id, extension_id: 98 },
  { id: '2372', name: 'Thara Bachay', user_id: User.first.id, extension_id: 98 },
  { id: '2373', name: 'Tenpakha', user_id: User.first.id, extension_id: 98 },
  { id: '2374', name: 'Wangwakha', user_id: User.first.id, extension_id: 98 },
  { id: '2375', name: 'Tongtshasho', user_id: User.first.id, extension_id: 98 },
  { id: '2376', name: 'Dargaygang', user_id: User.first.id, extension_id: 98 },
  { id: '2377', name: 'Baymenang', user_id: User.first.id, extension_id: 98 },
  { id: '2378', name: 'Nejiwoma', user_id: User.first.id, extension_id: 98 },
  { id: '2379', name: 'Neybi', user_id: User.first.id, extension_id: 98 },
  { id: '2380', name: 'Gagona', user_id: User.first.id, extension_id: 98 },
  { id: '2381', name: 'Nebji', user_id: User.first.id, extension_id: 98 },
  { id: '2382', name: 'Gona Tengkha', user_id: User.first.id, extension_id: 98 },
  { id: '2383', name: 'Chokhor Luchu', user_id: User.first.id, extension_id: 98 },
  { id: '2384', name: 'Goenchukha', user_id: User.first.id, extension_id: 98 },
  { id: '2385', name: 'Langsigang', user_id: User.first.id, extension_id: 98 },
  { id: '2386', name: 'Thongde Bay Kha', user_id: User.first.id, extension_id: 98 },
  { id: '2387', name: 'Guru', user_id: User.first.id, extension_id: 98 },
  { id: '2388', name: 'Dongkokha', user_id: User.first.id, extension_id: 98 }
].each do |v|
  Village.find_or_create_by!(v)
end
