# frozen_string_literal: true

[
  # Chhubu
  { id: '2262', name: 'Bali', user_id: User.first.id, extension_id: 95 },
  { id: '2263', name: 'Bumtakha', user_id: User.first.id, extension_id: 95 },
  { id: '2264', name: 'Chukhu Nidupchu', user_id: User.first.id, extension_id: 95 },
  { id: '2265', name: 'Chuphu Nidupchu', user_id: User.first.id, extension_id: 95 },
  { id: '2266', name: 'Jangkholo', user_id: User.first.id, extension_id: 95 },
  { id: '2267', name: 'Jawakha', user_id: User.first.id, extension_id: 95 },
  { id: '2268', name: 'Lhabesa', user_id: User.first.id, extension_id: 95 },
  { id: '2269', name: 'Lorina', user_id: User.first.id, extension_id: 95 },
  { id: '2270', name: 'Nidupchu', user_id: User.first.id, extension_id: 95 },
  { id: '2271', name: 'Nidupchu Chukha', user_id: User.first.id, extension_id: 95 },
  { id: '2272', name: 'Nidupchu Gangkha', user_id: User.first.id, extension_id: 95 },
  { id: '2273', name: 'Nidupchu Khemsina', user_id: User.first.id, extension_id: 95 },
  { id: '2274', name: 'Nidupchu Tengkha', user_id: User.first.id, extension_id: 95 },
  { id: '2275', name: 'Puna Gom', user_id: User.first.id, extension_id: 95 },
  { id: '2276', name: 'Rechena', user_id: User.first.id, extension_id: 95 },
  { id: '2277', name: 'Seowla', user_id: User.first.id, extension_id: 95 },
  { id: '2278', name: 'Tenpakha', user_id: User.first.id, extension_id: 95 },
  { id: '2279', name: 'Yebesa', user_id: User.first.id, extension_id: 95 },
  { id: '2280', name: 'Nawakha', user_id: User.first.id, extension_id: 95 },

  # Kabisa
  { id: '2390', name: 'Agona', user_id: User.first.id, extension_id: 99 },
  { id: '2391', name: 'Ap Zhuksa', user_id: User.first.id, extension_id: 99 },
  { id: '2392', name: 'Bara', user_id: User.first.id, extension_id: 99 },
  { id: '2393', name: 'Baymenang', user_id: User.first.id, extension_id: 99 },
  { id: '2394', name: 'Baypai Gangkha', user_id: User.first.id, extension_id: 99 },
  { id: '2395', name: 'Botokha', user_id: User.first.id, extension_id: 99 },
  { id: '2396', name: 'Botolo', user_id: User.first.id, extension_id: 99 },
  { id: '2397', name: 'Chisegang', user_id: User.first.id, extension_id: 99 },
  { id: '2398', name: 'Chokhor Luchu', user_id: User.first.id, extension_id: 99 },
  { id: '2399', name: 'Chorten Nyingbu', user_id: User.first.id, extension_id: 99 },
  { id: '2400', name: 'Chulukha', user_id: User.first.id, extension_id: 99 },
  { id: '2401', name: 'Chuzamgang', user_id: User.first.id, extension_id: 99 },
  { id: '2402', name: 'Damchi', user_id: User.first.id, extension_id: 99 },
  { id: '2403', name: 'Damteykha', user_id: User.first.id, extension_id: 99 },
  { id: '2404', name: 'Dargaygang', user_id: User.first.id, extension_id: 99 },
  { id: '2405', name: 'Dawana', user_id: User.first.id, extension_id: 99 },
  { id: '2406', name: 'Dokuna', user_id: User.first.id, extension_id: 99 },
  { id: '2407', name: 'Dokuna Shophu', user_id: User.first.id, extension_id: 99 },
  { id: '2408', name: 'Dophukha', user_id: User.first.id, extension_id: 99 },
  { id: '2409', name: 'Dzongchung', user_id: User.first.id, extension_id: 99 },
  { id: '2410', name: 'Gagona', user_id: User.first.id, extension_id: 99 },
  { id: '2411', name: 'Gomgang', user_id: User.first.id, extension_id: 99 },
  { id: '2412', name: 'Gona Tengkha', user_id: User.first.id, extension_id: 99 },
  { id: '2413', name: 'Haylu', user_id: User.first.id, extension_id: 99 },
  { id: '2414', name: 'Haylu Tongshu', user_id: User.first.id, extension_id: 99 },
  { id: '2415', name: 'Jangchubchen', user_id: User.first.id, extension_id: 99 },
  { id: '2416', name: 'Jangsa', user_id: User.first.id, extension_id: 99 },
  { id: '2417', name: 'Kazhikha', user_id: User.first.id, extension_id: 99 },
  { id: '2418', name: 'Kelwagang', user_id: User.first.id, extension_id: 99 },
  { id: '2419', name: 'Kilakha', user_id: User.first.id, extension_id: 99 },
  { id: '2420', name: 'Lengo Gaysa', user_id: User.first.id, extension_id: 99 },
  { id: '2421', name: 'Logodama', user_id: User.first.id, extension_id: 99 },
  { id: '2422', name: 'Lungnakha', user_id: User.first.id, extension_id: 99 },
  { id: '2423', name: 'Lungtamo', user_id: User.first.id, extension_id: 99 },
  { id: '2424', name: 'Lungtengang', user_id: User.first.id, extension_id: 99 },
  { id: '2425', name: 'Lungtikha', user_id: User.first.id, extension_id: 99 },
  { id: '2426', name: 'Lutamo', user_id: User.first.id, extension_id: 99 },
  { id: '2427', name: 'Nebji', user_id: User.first.id, extension_id: 99 },
  { id: '2428', name: 'Nejiwoma', user_id: User.first.id, extension_id: 99 },
  { id: '2429', name: 'Neybi', user_id: User.first.id, extension_id: 99 },
  { id: '2430', name: 'Pachaykha', user_id: User.first.id, extension_id: 99 },
  { id: '2431', name: 'Pamarpo', user_id: User.first.id, extension_id: 99 },
  { id: '2432', name: 'Pangreju', user_id: User.first.id, extension_id: 99 },
  { id: '2433', name: 'Pasuna', user_id: User.first.id, extension_id: 99 },
  { id: '2434', name: 'Petari', user_id: User.first.id, extension_id: 99 },
  { id: '2435', name: 'Phakakha', user_id: User.first.id, extension_id: 99 },
  { id: '2436', name: 'Rangrekha', user_id: User.first.id, extension_id: 99 },
  { id: '2437', name: 'Semto Gangchu', user_id: User.first.id, extension_id: 99 },
  { id: '2438', name: 'Serigang', user_id: User.first.id, extension_id: 99 },
  { id: '2439', name: 'Tenpakha', user_id: User.first.id, extension_id: 99 },
  { id: '2440', name: 'Thara Bachay', user_id: User.first.id, extension_id: 99 },
  { id: '2441', name: 'Tongchena', user_id: User.first.id, extension_id: 99 },
  { id: '2442', name: 'Tongshigang', user_id: User.first.id, extension_id: 99 },
  { id: '2443', name: 'Tongshina', user_id: User.first.id, extension_id: 99 },
  { id: '2444', name: 'Tongshiremay', user_id: User.first.id, extension_id: 99 },
  { id: '2445', name: 'Tongtshasho', user_id: User.first.id, extension_id: 99 },
  { id: '2446', name: 'Tongzhuna', user_id: User.first.id, extension_id: 99 },
  { id: '2447', name: 'Tshetenang', user_id: User.first.id, extension_id: 99 },
  { id: '2448', name: 'Tshomiding', user_id: User.first.id, extension_id: 99 },
  { id: '2449', name: 'Wakhuna', user_id: User.first.id, extension_id: 99 },
  { id: '2450', name: 'Wangwakha', user_id: User.first.id, extension_id: 99 },
  { id: '2451', name: 'Yousakha', user_id: User.first.id, extension_id: 99 },
  { id: '2452', name: 'Yurba', user_id: User.first.id, extension_id: 99 },
  { id: '2453', name: 'Yusakha', user_id: User.first.id, extension_id: 99 },
  { id: '2454', name: 'Yuwa', user_id: User.first.id, extension_id: 99 },
  { id: '2455', name: 'Zarbesa', user_id: User.first.id, extension_id: 99 },
  { id: '2456', name: 'Zerkha', user_id: User.first.id, extension_id: 99 },
  { id: '2457', name: 'Zhingsahang', user_id: User.first.id, extension_id: 99 },
  { id: '2458', name: 'Lorina', user_id: User.first.id, extension_id: 99 },

  # Lingmukha
  { id: '2460', name: 'Dompala', user_id: User.first.id, extension_id: 100 },
  { id: '2461', name: 'Gumkarmo', user_id: User.first.id, extension_id: 100 },
  { id: '2462', name: 'Lingmukha', user_id: User.first.id, extension_id: 100 },
  { id: '2463', name: 'Nabchey', user_id: User.first.id, extension_id: 100 },
  { id: '2464', name: 'Omtekha', user_id: User.first.id, extension_id: 100 },
  { id: '2465', name: 'Yusakha', user_id: User.first.id, extension_id: 100 },

  # Shelnga
  { id: '2467', name: 'Bangna Thangka', user_id: User.first.id, extension_id: 101 },
  { id: '2468', name: 'Bara', user_id: User.first.id, extension_id: 101 },
  { id: '2469', name: 'Barnatheka', user_id: User.first.id, extension_id: 101 },
  { id: '2470', name: 'Changjokha', user_id: User.first.id, extension_id: 101 },
  { id: '2471', name: 'Chongchog Goenpa', user_id: User.first.id, extension_id: 101 },
  { id: '2472', name: 'Chongzhikha', user_id: User.first.id, extension_id: 101 },
  { id: '2473', name: 'Datong Goenpa', user_id: User.first.id, extension_id: 101 },
  { id: '2474', name: 'Domina', user_id: User.first.id, extension_id: 101 },
  { id: '2475', name: 'Domsimo', user_id: User.first.id, extension_id: 101 },
  { id: '2476', name: 'Dupchu Goenpa', user_id: User.first.id, extension_id: 101 },
  { id: '2477', name: 'Gangchula', user_id: User.first.id, extension_id: 101 },
  { id: '2478', name: 'Gangkha', user_id: User.first.id, extension_id: 101 },
  { id: '2479', name: 'Gangla', user_id: User.first.id, extension_id: 101 },
  { id: '2480', name: 'Garakha', user_id: User.first.id, extension_id: 101 },
  { id: '2481', name: 'Goen Wogma', user_id: User.first.id, extension_id: 101 },
  { id: '2482', name: 'Goleygang', user_id: User.first.id, extension_id: 101 },
  { id: '2483', name: 'Gumena', user_id: User.first.id, extension_id: 101 },
  { id: '2484', name: 'Japana', user_id: User.first.id, extension_id: 101 },
  { id: '2485', name: 'Jarigang', user_id: User.first.id, extension_id: 101 },
  { id: '2486', name: 'Jazhikha', user_id: User.first.id, extension_id: 101 },
  { id: '2487', name: 'Jimjig', user_id: User.first.id, extension_id: 101 },
  { id: '2488', name: 'Jozhe Goenpa', user_id: User.first.id, extension_id: 101 },
  { id: '2489', name: 'Keparabsel', user_id: User.first.id, extension_id: 101 },
  { id: '2490', name: 'Kubji', user_id: User.first.id, extension_id: 101 },
  { id: '2491', name: 'Kutsiphakar', user_id: User.first.id, extension_id: 101 },
  { id: '2492', name: 'Langjo', user_id: User.first.id, extension_id: 101 },
  { id: '2493', name: 'Loigima', user_id: User.first.id, extension_id: 101 },
  { id: '2494', name: 'Lungkha', user_id: User.first.id, extension_id: 101 },
  { id: '2495', name: 'Manikha', user_id: User.first.id, extension_id: 101 },
  { id: '2496', name: 'Manikha Damchugang', user_id: User.first.id, extension_id: 101 },
  { id: '2497', name: 'Menchudamlay', user_id: User.first.id, extension_id: 101 },
  { id: '2498', name: 'Mendrelji', user_id: User.first.id, extension_id: 101 },
  { id: '2499', name: 'Menzhi', user_id: User.first.id, extension_id: 101 },
  { id: '2500', name: 'Nangpakha', user_id: User.first.id, extension_id: 101 },
  { id: '2501', name: 'Norbu Tashi', user_id: User.first.id, extension_id: 101 },
  { id: '2502', name: 'Nyebakha', user_id: User.first.id, extension_id: 101 },
  { id: '2503', name: 'Palu', user_id: User.first.id, extension_id: 101 },
  { id: '2504', name: 'Pangzhi', user_id: User.first.id, extension_id: 101 },
  { id: '2505', name: 'Saychikha', user_id: User.first.id, extension_id: 101 },
  { id: '2506', name: 'Shenga Goenpa', user_id: User.first.id, extension_id: 101 },
  { id: '2507', name: 'Shongchumo', user_id: User.first.id, extension_id: 101 },
  { id: '2508', name: 'Tagochen', user_id: User.first.id, extension_id: 101 },
  { id: '2509', name: 'Thongji', user_id: User.first.id, extension_id: 101 },
  { id: '2510', name: 'Tshamkhana', user_id: User.first.id, extension_id: 101 },
  { id: '2511', name: 'Tshosa', user_id: User.first.id, extension_id: 101 },
  { id: '2512', name: 'Yedogang', user_id: User.first.id, extension_id: 101 },
  { id: '2513', name: 'Yedopang', user_id: User.first.id, extension_id: 101 }
].each do |v|
  Village.find_or_create_by!(v)
end
