# frozen_string_literal: true

[
  # Talog
  { id: '2515', name: 'Dongkokha', user_id: User.first.id, extension_id: 102 },
  { id: '2516', name: 'Dongkokha Dapchagang', user_id: User.first.id, extension_id: 102 },
  { id: '2517', name: 'Dongkokha Lungsigang', user_id: User.first.id, extension_id: 102 },
  { id: '2518', name: 'Dongkokha Pepchu', user_id: User.first.id, extension_id: 102 },
  { id: '2519', name: 'Dongkokha Shongrina', user_id: User.first.id, extension_id: 102 },
  { id: '2520', name: 'Gangthramo', user_id: User.first.id, extension_id: 102 },
  { id: '2521', name: 'Jawana', user_id: User.first.id, extension_id: 102 },
  { id: '2522', name: 'Lapchakha', user_id: User.first.id, extension_id: 102 },
  { id: '2523', name: 'Lunakha', user_id: User.first.id, extension_id: 102 },
  { id: '2524', name: 'Lungsegang', user_id: User.first.id, extension_id: 102 },
  { id: '2525', name: 'Nobgang', user_id: User.first.id, extension_id: 102 },
  { id: '2526', name: 'Nobgang Bemidingkha', user_id: User.first.id, extension_id: 102 },
  { id: '2527', name: 'Nobgang Bulgang', user_id: User.first.id, extension_id: 102 },
  { id: '2528', name: 'Nobgang Dashingang', user_id: User.first.id, extension_id: 102 },
  { id: '2529', name: 'Nobgang Gaupay', user_id: User.first.id, extension_id: 102 },
  { id: '2530', name: 'Nobgang Lamseri', user_id: User.first.id, extension_id: 102 },
  { id: '2531', name: 'Nobgang Serinang', user_id: User.first.id, extension_id: 102 },
  { id: '2532', name: 'Nobgang Tshochuna', user_id: User.first.id, extension_id: 102 },
  { id: '2533', name: 'Talo', user_id: User.first.id, extension_id: 102 },
  { id: '2534', name: 'Talo Goenpa', user_id: User.first.id, extension_id: 102 },
  { id: '2535', name: 'Talo Pangkarpo', user_id: User.first.id, extension_id: 102 },
  { id: '2536', name: 'Yungu', user_id: User.first.id, extension_id: 102 },
  { id: '2537', name: 'Siew Drangsa', user_id: User.first.id, extension_id: 102 },
  { id: '2538', name: 'Dargaygang', user_id: User.first.id, extension_id: 102 },

  # Toedpaisa
  { id: '2614', name: 'Aechey', user_id: User.first.id, extension_id: 103 },
  { id: '2615', name: 'Bechekha', user_id: User.first.id, extension_id: 103 },
  { id: '2616', name: 'Bemsisi', user_id: User.first.id, extension_id: 103 },
  { id: '2617', name: 'Bomthangka', user_id: User.first.id, extension_id: 103 },
  { id: '2618', name: 'Chandana', user_id: User.first.id, extension_id: 103 },
  { id: '2619', name: 'Chasa', user_id: User.first.id, extension_id: 103 },
  { id: '2620', name: 'Chelekha', user_id: User.first.id, extension_id: 103 },
  { id: '2621', name: 'Damche', user_id: User.first.id, extension_id: 103 },
  { id: '2622', name: 'Dochula', user_id: User.first.id, extension_id: 103 },
  { id: '2623', name: 'Gyemkha', user_id: User.first.id, extension_id: 103 },
  { id: '2624', name: 'Gyemsa', user_id: User.first.id, extension_id: 103 },
  { id: '2625', name: 'Jalung', user_id: User.first.id, extension_id: 103 },
  { id: '2626', name: 'Lemjakha', user_id: User.first.id, extension_id: 103 },
  { id: '2627', name: 'Lungjam', user_id: User.first.id, extension_id: 103 },
  { id: '2628', name: 'Menchuna', user_id: User.first.id, extension_id: 103 },
  { id: '2629', name: 'Mendelgang', user_id: User.first.id, extension_id: 103 },
  { id: '2630', name: 'Phentekha', user_id: User.first.id, extension_id: 103 },
  { id: '2631', name: 'Rinakha', user_id: User.first.id, extension_id: 103 },
  { id: '2632', name: 'Siluna', user_id: User.first.id, extension_id: 103 },
  { id: '2633', name: 'Simtokha', user_id: User.first.id, extension_id: 103 },
  { id: '2634', name: 'Tang Ho', user_id: User.first.id, extension_id: 103 },
  { id: '2635', name: 'Thinleygang', user_id: User.first.id, extension_id: 103 },
  { id: '2636', name: 'Tokha', user_id: User.first.id, extension_id: 103 },
  { id: '2637', name: 'Toktokha', user_id: User.first.id, extension_id: 103 },
  { id: '2638', name: 'Tsheringgang', user_id: User.first.id, extension_id: 103 },
  { id: '2639', name: 'Yanglo', user_id: User.first.id, extension_id: 103 },
  { id: '2640', name: 'Yuamo', user_id: User.first.id, extension_id: 103 },

  # Toedwang
  { id: '2540', name: 'Bedarlo', user_id: User.first.id, extension_id: 104 },
  { id: '2541', name: 'Bidongkha', user_id: User.first.id, extension_id: 104 },
  { id: '2542', name: 'Bidongkha Tsentending', user_id: User.first.id, extension_id: 104 },
  { id: '2543', name: 'Bumtakha', user_id: User.first.id, extension_id: 104 },
  { id: '2544', name: 'Chungkha', user_id: User.first.id, extension_id: 104 },
  { id: '2545', name: 'Dabji', user_id: User.first.id, extension_id: 104 },
  { id: '2546', name: 'Dangtsa', user_id: User.first.id, extension_id: 104 },
  { id: '2547', name: 'Dawakha', user_id: User.first.id, extension_id: 104 },
  { id: '2548', name: 'Dawanang', user_id: User.first.id, extension_id: 104 },
  { id: '2549', name: 'Dengana', user_id: User.first.id, extension_id: 104 },
  { id: '2550', name: 'Dharshongna', user_id: User.first.id, extension_id: 104 },
  { id: '2551', name: 'Gengo', user_id: User.first.id, extension_id: 104 },
  { id: '2552', name: 'Humpathang', user_id: User.first.id, extension_id: 104 },
  { id: '2553', name: 'Kepailo', user_id: User.first.id, extension_id: 104 },
  { id: '2554', name: 'Kewana', user_id: User.first.id, extension_id: 104 },
  { id: '2555', name: 'Kutshana', user_id: User.first.id, extension_id: 104 },
  { id: '2556', name: 'Lebchula', user_id: User.first.id, extension_id: 104 },
  { id: '2557', name: 'Limkha', user_id: User.first.id, extension_id: 104 },
  { id: '2558', name: 'Lorina', user_id: User.first.id, extension_id: 104 },
  { id: '2559', name: 'Naripa', user_id: User.first.id, extension_id: 104 },
  { id: '2560', name: 'Nawakha', user_id: User.first.id, extension_id: 104 },
  { id: '2561', name: 'Nebtenkha', user_id: User.first.id, extension_id: 104 },
  { id: '2562', name: 'Omchukha', user_id: User.first.id, extension_id: 104 },
  { id: '2563', name: 'Pangsho', user_id: User.first.id, extension_id: 104 },
  { id: '2564', name: 'Raro', user_id: User.first.id, extension_id: 104 },
  { id: '2565', name: 'Tamidamchu', user_id: User.first.id, extension_id: 104 },
  { id: '2566', name: 'Thangbji', user_id: User.first.id, extension_id: 104 },
  { id: '2567', name: 'Tserig', user_id: User.first.id, extension_id: 104 },
  { id: '2568', name: 'Tseykha', user_id: User.first.id, extension_id: 104 },
  { id: '2569', name: 'Tseyphu', user_id: User.first.id, extension_id: 104 },
  { id: '2570', name: 'Tseyphu Atako', user_id: User.first.id, extension_id: 104 },
  { id: '2571', name: 'Tseyphu Bumpai Tsawa', user_id: User.first.id, extension_id: 104 },
  { id: '2572', name: 'Tseyphu Jara', user_id: User.first.id, extension_id: 104 },
  { id: '2573', name: 'Tseyphu Khawakha', user_id: User.first.id, extension_id: 104 },
  { id: '2574', name: 'Tseyphu Semeki', user_id: User.first.id, extension_id: 104 },
  { id: '2575', name: 'Tshachuphu', user_id: User.first.id, extension_id: 104 },
  { id: '2576', name: 'Tshachuphu Kati', user_id: User.first.id, extension_id: 104 },
  { id: '2577', name: 'Tshachuphugang', user_id: User.first.id, extension_id: 104 },
  { id: '2578', name: 'Wangkha', user_id: User.first.id, extension_id: 104 },
  { id: '2579', name: 'Yusakha', user_id: User.first.id, extension_id: 104 },
  { id: '2580', name: 'Yusakha Neyji', user_id: User.first.id, extension_id: 104 },
  { id: '2581', name: 'Samdingkha', user_id: User.first.id, extension_id: 104 },
  { id: '2582', name: 'Thangzhi', user_id: User.first.id, extension_id: 104 },
  { id: '2583', name: 'Jopkha', user_id: User.first.id, extension_id: 104 },

  # Khuruthang Thromde
  { id: '4713', name: 'Khuruthang Throm', user_id: User.first.id, extension_id: 105 },
  { id: '4714', name: 'Zamdongkhar', user_id: User.first.id, extension_id: 105 },
  { id: '4715', name: 'Zamdongkhar Bebigarkha', user_id: User.first.id, extension_id: 105 },
  { id: '4716', name: 'Zamdongkhar Lekithang', user_id: User.first.id, extension_id: 105 },
  { id: '4719', name: 'Zamdongkhar Selipang', user_id: User.first.id, extension_id: 105 },
  { id: '4720', name: 'Zamdongkhar Tshendengang', user_id: User.first.id, extension_id: 105 },
  { id: '4722', name: 'Zamdongkhar Zingchey', user_id: User.first.id, extension_id: 105 }
].each do |v|
  Village.find_or_create_by!(v)
end
