# frozen_string_literal: true

[
  # Pemathang
  { id: '2748', name: 'Pemathang(Beldara)', user_id: User.first.id, extension_id: 112 },
  { id: '2749', name: 'Pemathang(Dalim)', user_id: User.first.id, extension_id: 112 },
  { id: '2750', name: 'Labtshazor(Deorali)', user_id: User.first.id, extension_id: 112 },
  { id: '2751', name: 'Kadupdang(Diklai)', user_id: User.first.id, extension_id: 112 },
  { id: '2752', name: 'Dungkarling(Dumpha)', user_id: User.first.id, extension_id: 112 },
  { id: '2753', name: 'Luminang(Gairitar)', user_id: User.first.id, extension_id: 112 },
  { id: '2754', name: 'Dramzeygang(Kataray)', user_id: User.first.id, extension_id: 112 },
  { id: '2755', name: 'Chirtshosa(Kharbandi)', user_id: User.first.id, extension_id: 112 },
  { id: '2756', name: 'Banakha(Majuwa)', user_id: User.first.id, extension_id: 112 },
  { id: '2757', name: 'Yuesana(Nainital)', user_id: User.first.id, extension_id: 112 },
  { id: '2758', name: 'Yuwathang(Nalapara)', user_id: User.first.id, extension_id: 112 },
  { id: '2759', name: 'Dorangthag(Peoli)', user_id: User.first.id, extension_id: 112 },
  { id: '2760', name: 'Raling(Phedi)', user_id: User.first.id, extension_id: 112 },
  { id: '2761', name: 'Methothang(Shillingay)', user_id: User.first.id, extension_id: 112 },
  { id: '2762', name: 'Lingmayshong(Tarulay)', user_id: User.first.id, extension_id: 112 },
  { id: '2763', name: 'Warong(Warang)', user_id: User.first.id, extension_id: 112 },
  { id: '2764', name: 'Tsheothang(Perungay)', user_id: User.first.id, extension_id: 112 },

  # Phuentshogthang
  { id: '2766', name: 'Tshochung(Bauney)', user_id: User.first.id, extension_id: 113 },
  { id: '2767', name: 'Mendrupling(Bhawaney)', user_id: User.first.id, extension_id: 113 },
  { id: '2768', name: 'Tshechiwoong(Daurey)', user_id: User.first.id, extension_id: 113 },
  { id: '2769', name: 'Dungkarling/Dumpha/Gangatay', user_id: User.first.id, extension_id: 113 },
  { id: '2770', name: 'Chumeythang(Gauthalay)', user_id: User.first.id, extension_id: 113 },
  { id: '2771', name: 'Thongjaling(Jagartala)', user_id: User.first.id, extension_id: 113 },
  { id: '2772', name: 'Karmaling(Kataray)', user_id: User.first.id, extension_id: 113 },
  { id: '2773', name: 'Zomlaythang(Katikay)', user_id: User.first.id, extension_id: 113 },
  { id: '2774', name: 'Khamethang/Mansitar', user_id: User.first.id, extension_id: 113 },
  { id: '2775', name: 'Selmothang(Koila)', user_id: User.first.id, extension_id: 113 },
  { id: '2776', name: 'Dupchugang(Kubindey)', user_id: User.first.id, extension_id: 113 },
  { id: '2777', name: 'Tshokorling(Majuwa)', user_id: User.first.id, extension_id: 113 },
  { id: '2778', name: 'Balamnang(Nakalitar)', user_id: User.first.id, extension_id: 113 },
  { id: '2779', name: 'Phuntshothang/Bakuli', user_id: User.first.id, extension_id: 113 },
  { id: '2780', name: 'Samdrupcholing/Raitar', user_id: User.first.id, extension_id: 113 },
  { id: '2781', name: 'Thongsigang(Saureney)', user_id: User.first.id, extension_id: 113 },
  { id: '2782', name: 'Mengigang(Tekree)', user_id: User.first.id, extension_id: 113 },
  { id: '2783', name: 'Thangchugonpa/Chotaytar', user_id: User.first.id, extension_id: 113 },
  { id: '2784', name: 'Tsangchutham/U.Mansitar', user_id: User.first.id, extension_id: 113 },
  { id: '2785', name: 'Baylamsharang', user_id: User.first.id, extension_id: 113 },
  { id: '2786', name: 'Sangshingzor', user_id: User.first.id, extension_id: 113 },
  { id: '2787', name: 'Shukuni/Sangshingzor', user_id: User.first.id, extension_id: 113 },
  { id: '2788', name: 'Merudaza/Sangshingzor', user_id: User.first.id, extension_id: 113 },
  { id: '2789', name: 'Dadulthang(Bangtar)', user_id: User.first.id, extension_id: 113 },
  { id: '2790', name: 'Samdrupcholing(Raitar)', user_id: User.first.id, extension_id: 113 },

  # Samrang
  { id: '2792', name: 'Damsagang(Hillay)', user_id: User.first.id, extension_id: 114 },
  { id: '2793', name: 'Ngangtshothang Ka(Samrang A)', user_id: User.first.id, extension_id: 114 },
  { id: '2794', name: 'Ngangtshothang Kha(Samrang B)', user_id: User.first.id, extension_id: 114 },
  { id: '2795', name: 'Tshodun(Sathpokari)', user_id: User.first.id, extension_id: 114 },

  # Serthig
  { id: '2797', name: 'Barkalangnang', user_id: User.first.id, extension_id: 115 },
  { id: '2798', name: 'Chaskhar/ Menjiwoong', user_id: User.first.id, extension_id: 115 },
  { id: '2799', name: 'Chemari', user_id: User.first.id, extension_id: 115 },
  { id: '2800', name: 'Chemari/ Borla', user_id: User.first.id, extension_id: 115 },
  { id: '2801', name: 'Dekorwoong/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2802', name: 'Denphu', user_id: User.first.id, extension_id: 115 },
  { id: '2803', name: 'Deptsang', user_id: User.first.id, extension_id: 115 },
  { id: '2804', name: 'Dhangtsho/ Serthi', user_id: User.first.id, extension_id: 115 },
  { id: '2805', name: 'Dhukha/ Monmola', user_id: User.first.id, extension_id: 115 },
  { id: '2806', name: 'Dhuwangka/ Monmola', user_id: User.first.id, extension_id: 115 },
  { id: '2807', name: 'Gonpa/ Monmola', user_id: User.first.id, extension_id: 115 },
  { id: '2808', name: 'Jab/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2809', name: 'Junme', user_id: User.first.id, extension_id: 115 },
  { id: '2810', name: 'Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2811', name: 'Lamkhabjay/ Serthi', user_id: User.first.id, extension_id: 115 },
  { id: '2812', name: 'Lhakhangzor/ Serthi', user_id: User.first.id, extension_id: 115 },
  { id: '2813', name: 'Menjiwoong/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2814', name: 'Menjiwoongpeka/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2815', name: 'Pangthang/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2816', name: 'Pangthang/ Monmola', user_id: User.first.id, extension_id: 115 },
  { id: '2817', name: 'Pangthang/ Serthi', user_id: User.first.id, extension_id: 115 },
  { id: '2818', name: 'Pemagatshel', user_id: User.first.id, extension_id: 115 },
  { id: '2819', name: 'Phakchu', user_id: User.first.id, extension_id: 115 },
  { id: '2820', name: 'Phakchu/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2821', name: 'Rebalingbi', user_id: User.first.id, extension_id: 115 },
  { id: '2822', name: 'Sakari/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2823', name: 'Suskar', user_id: User.first.id, extension_id: 115 },
  { id: '2824', name: 'Tang Frang/ Serthi', user_id: User.first.id, extension_id: 115 },
  { id: '2825', name: 'Tang Phrang/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2826', name: 'Tangngakpa/ Serthi', user_id: User.first.id, extension_id: 115 },
  { id: '2827', name: 'Tashi Thangjay', user_id: User.first.id, extension_id: 115 },
  { id: '2828', name: 'Thujaycheling/ Monmola', user_id: User.first.id, extension_id: 115 },
  { id: '2829', name: 'Tokari Gonpa/ Serthi', user_id: User.first.id, extension_id: 115 },
  { id: '2830', name: 'Woong/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2831', name: 'Zor/ Khanduphung', user_id: User.first.id, extension_id: 115 },
  { id: '2832', name: 'Zor/ Monmola', user_id: User.first.id, extension_id: 115 },
  { id: '2833', name: 'Chitori', user_id: User.first.id, extension_id: 115 },

  # Wangphu
  { id: '2865', name: 'Bayul', user_id: User.first.id, extension_id: 116 },
  { id: '2866', name: 'Benporong', user_id: User.first.id, extension_id: 116 },
  { id: '2867', name: 'Haila', user_id: User.first.id, extension_id: 116 },
  { id: '2868', name: 'Khainorong/Shokshi', user_id: User.first.id, extension_id: 116 },
  { id: '2869', name: 'Langnang Ringmo/Wangphu', user_id: User.first.id, extension_id: 116 },
  { id: '2870', name: 'Lingsum/Shokshi', user_id: User.first.id, extension_id: 116 },
  { id: '2871', name: 'Manidangre/Shokshi', user_id: User.first.id, extension_id: 116 },
  { id: '2872', name: 'Sachilo', user_id: User.first.id, extension_id: 116 },
  { id: '2873', name: 'Serchenmo', user_id: User.first.id, extension_id: 116 },
  { id: '2874', name: 'Shoguwoong', user_id: User.first.id, extension_id: 116 },
  { id: '2875', name: 'Shokshi', user_id: User.first.id, extension_id: 116 },
  { id: '2876', name: 'Shokshi Pangthang', user_id: User.first.id, extension_id: 116 },
  { id: '2877', name: 'Wangphu', user_id: User.first.id, extension_id: 116 },
  { id: '2878', name: 'Yarphu', user_id: User.first.id, extension_id: 116 },
  { id: '2879', name: 'Singsi Borang', user_id: User.first.id, extension_id: 116 }
].each do |v|
  Village.find_or_create_by!(v)
end
