# frozen_string_literal: true

puts 'Seeding villages of Samdrup Jongkhar...'
[
  # Dewathang
  { id: '2835', name: 'Ashikhar', user_id: User.first.id, extension_id: 106 },
  { id: '2836', name: 'Bangtsho', user_id: User.first.id, extension_id: 106 },
  { id: '2837', name: 'Bangtsho Goenpa ', user_id: User.first.id, extension_id: 106 },
  { id: '2838', name: 'Barkadung', user_id: User.first.id, extension_id: 106 },
  { id: '2839', name: 'Chenari', user_id: User.first.id, extension_id: 106 },
  { id: '2840', name: 'Chenari Gezor ', user_id: User.first.id, extension_id: 106 },
  { id: '2841', name: 'Dungkarcholing', user_id: User.first.id, extension_id: 106 },
  { id: '2842', name: 'Deothang Throm', user_id: User.first.id, extension_id: 106 },
  { id: '2843', name: 'Domphu', user_id: User.first.id, extension_id: 106 },
  { id: '2844', name: 'Drupkhang', user_id: User.first.id, extension_id: 106 },
  { id: '2845', name: 'Gerwa', user_id: User.first.id, extension_id: 106 },
  { id: '2846 ', name: 'Gaykheri ', user_id: User.first.id, extension_id: 106 },
  { id: '2847 ', name: 'Gezor ', user_id: User.first.id, extension_id: 106 },
  { id: '2848', name: 'Khesangtiri', user_id: User.first.id, extension_id: 106 },
  { id: '2849', name: 'Khorpam', user_id: User.first.id, extension_id: 106 },
  { id: '2850', name: 'Kopur', user_id: User.first.id, extension_id: 106 },
  { id: '2851', name: 'Pazor', user_id: User.first.id, extension_id: 106 },
  { id: '2852', name: 'Martang', user_id: User.first.id, extension_id: 106 },
  { id: '2853', name: 'Rantsham', user_id: User.first.id, extension_id: 106 },
  { id: '2854 ', name: 'Samdrupgatshel ', user_id: User.first.id, extension_id: 106 },
  { id: '2855 ', name: 'Sengdengri ', user_id: User.first.id, extension_id: 106 },
  { id: '2856 ', name: 'Sepka ', user_id: User.first.id, extension_id: 106 },
  { id: '2857', name: 'Rechurpo', user_id: User.first.id, extension_id: 106 },
  { id: '2858', name: 'Reshor', user_id: User.first.id, extension_id: 106 },
  { id: '2859', name: 'Rikhey', user_id: User.first.id, extension_id: 106 },
  { id: '2860', name: 'S/Jongkhar Throm', user_id: User.first.id, extension_id: 106 },
  { id: '2861', name: 'Kheripam', user_id: User.first.id, extension_id: 106 },
  { id: '2862', name: 'Rabteyling(Mathanga)', user_id: User.first.id, extension_id: 106 },
  { id: '2863', name: 'Dungkarcholing(Shangkarjuli)', user_id: User.first.id, extension_id: 106 },

  # Gomdar
  { id: '2643', name: 'Amshing', user_id: User.first.id, extension_id: 107 },
  { id: '2644', name: 'Bargoenpa', user_id: User.first.id, extension_id: 107 },
  { id: '2645', name: 'Barzor', user_id: User.first.id, extension_id: 107 },
  { id: '2646', name: 'Belnang Woong', user_id: User.first.id, extension_id: 107 },
  { id: '2647', name: 'Brongshing', user_id: User.first.id, extension_id: 107 },
  { id: '2648', name: 'Brumi', user_id: User.first.id, extension_id: 107 },
  { id: '2649', name: 'Chidungkhar', user_id: User.first.id, extension_id: 107 },
  { id: '2650', name: 'Denchi', user_id: User.first.id, extension_id: 107 },
  { id: '2651', name: 'Denchi Khoyar', user_id: User.first.id, extension_id: 107 },
  { id: '2652', name: 'Fremi', user_id: User.first.id, extension_id: 107 },
  { id: '2653', name: 'Gomdar', user_id: User.first.id, extension_id: 107 },
  { id: '2654', name: 'Khandoma', user_id: User.first.id, extension_id: 107 },
  { id: '2655', name: 'Khoyar', user_id: User.first.id, extension_id: 107 },
  { id: '2656', name: 'Khoyar Panthang', user_id: User.first.id, extension_id: 107 },
  { id: '2657', name: 'Luzor', user_id: User.first.id, extension_id: 107 },
  { id: '2658', name: 'Narphung', user_id: User.first.id, extension_id: 107 },
  { id: '2659', name: 'Perung', user_id: User.first.id, extension_id: 107 },
  { id: '2660', name: 'Rechanglo', user_id: User.first.id, extension_id: 107 },
  { id: '2661', name: 'Rongchanglu', user_id: User.first.id, extension_id: 107 },
  { id: '2662', name: 'Sawang', user_id: User.first.id, extension_id: 107 },

  # Langchenphu
  { id: '2664', name: 'Agurthang(Aguritar)', user_id: User.first.id, extension_id: 108 },
  { id: '2665', name: 'Namchazor(Bajhrangi)', user_id: User.first.id, extension_id: 108 },
  { id: '2666', name: 'Aumshing(Betholi)', user_id: User.first.id, extension_id: 108 },
  { id: '2667', name: 'Jomotshangkha(Daifam Throm)', user_id: User.first.id, extension_id: 108 },
  { id: '2668', name: 'Daisam', user_id: User.first.id, extension_id: 108 },
  { id: '2669', name: 'Damtsang(Daldalay)', user_id: User.first.id, extension_id: 108 },
  { id: '2670', name: 'Jampani', user_id: User.first.id, extension_id: 108 },
  { id: '2671', name: 'Chelthang(Kharbandi/Khowrong)', user_id: User.first.id, extension_id: 108 },
  { id: '2672', name: 'Rongchuthang(Khowrong)', user_id: User.first.id, extension_id: 108 },
  { id: '2673', name: 'Jangsawom(Lower Golanti)', user_id: User.first.id, extension_id: 108 },
  { id: '2674', name: 'Langchenphumeth(Lower Hastinapur)', user_id: User.first.id, extension_id: 108 },
  { id: '2675', name: 'Tashiling(Majhbath)', user_id: User.first.id, extension_id: 108 },
  { id: '2676', name: 'Pagshingkha(Malabasy)', user_id: User.first.id, extension_id: 108 },
  { id: '2677', name: 'Dawathang(Nangley)', user_id: User.first.id, extension_id: 108 },
  { id: '2678', name: 'Jangsagom(Upper Golanti)', user_id: User.first.id, extension_id: 108 },
  { id: '2679', name: 'Langchenphutey(Upper Hastinapur)', user_id: User.first.id, extension_id: 108 },

  # Lauri
  { id: '2681', name: 'Betseling', user_id: User.first.id, extension_id: 109 },
  { id: '2682', name: 'Dungmanma', user_id: User.first.id, extension_id: 109 },
  { id: '2683', name: 'Gonong', user_id: User.first.id, extension_id: 109 },
  { id: '2684', name: 'Lauri', user_id: User.first.id, extension_id: 109 },
  { id: '2685', name: 'Momring', user_id: User.first.id, extension_id: 109 },
  { id: '2686', name: 'Patpanadang', user_id: User.first.id, extension_id: 109 },
  { id: '2687', name: 'Phajo Gonpa', user_id: User.first.id, extension_id: 109 },
  { id: '2688', name: 'Relnang', user_id: User.first.id, extension_id: 109 },
  { id: '2689', name: 'Serzhong', user_id: User.first.id, extension_id: 109 },
  { id: '2690', name: 'Tashiphu', user_id: User.first.id, extension_id: 109 },
  { id: '2691', name: 'Tshephu', user_id: User.first.id, extension_id: 109 },
  { id: '2692', name: 'Tshothang', user_id: User.first.id, extension_id: 109 },
  { id: '2693', name: 'Woongthi', user_id: User.first.id, extension_id: 109 },

  # Martshala
  { id: '2695', name: 'Choidung', user_id: User.first.id, extension_id: 110 },
  { id: '2696', name: 'Chongmashing', user_id: User.first.id, extension_id: 110 },
  { id: '2697', name: 'Dengshingzor', user_id: User.first.id, extension_id: 110 },
  { id: '2698', name: 'Dungmanba B', user_id: User.first.id, extension_id: 110 },
  { id: '2699', name: 'Galingkhar', user_id: User.first.id, extension_id: 110 },
  { id: '2700', name: 'Gorthongma', user_id: User.first.id, extension_id: 110 },
  { id: '2701', name: 'Kakaney', user_id: User.first.id, extension_id: 110 },
  { id: '2702', name: 'Kakpadung', user_id: User.first.id, extension_id: 110 },
  { id: '2703', name: 'Keptang', user_id: User.first.id, extension_id: 110 },
  { id: '2704', name: 'Khalingdangre/Galingkhar', user_id: User.first.id, extension_id: 110 },
  { id: '2705', name: 'Lungbaktang', user_id: User.first.id, extension_id: 110 },
  { id: '2706', name: 'Martshala', user_id: User.first.id, extension_id: 110 },
  { id: '2707', name: 'Merudaza/Sangshingzor', user_id: User.first.id, extension_id: 110 },
  { id: '2708', name: 'Pelrithang/Rechanglo', user_id: User.first.id, extension_id: 110 },
  { id: '2709', name: 'Raushing', user_id: User.first.id, extension_id: 110 },
  { id: '2710', name: 'Rechanglo', user_id: User.first.id, extension_id: 110 },
  { id: '2711', name: 'Sachilo', user_id: User.first.id, extension_id: 110 },
  { id: '2712', name: 'Sarjung', user_id: User.first.id, extension_id: 110 },
  { id: '2713', name: 'Shem Shem', user_id: User.first.id, extension_id: 110 },
  { id: '2714', name: 'Singsi Borang', user_id: User.first.id, extension_id: 110 },
  { id: '2715', name: 'Sozor', user_id: User.first.id, extension_id: 110 },
  { id: '2716', name: 'Thizor', user_id: User.first.id, extension_id: 110 },
  { id: '2717', name: 'Thongpashing', user_id: User.first.id, extension_id: 110 },
  { id: '2718', name: 'Tsholingkhar', user_id: User.first.id, extension_id: 110 },
  { id: '2719', name: 'Tshotsalo', user_id: User.first.id, extension_id: 110 },
  { id: '2720', name: 'Wangphu', user_id: User.first.id, extension_id: 110 },

  # Orong
  { id: '2722', name: 'Batshung', user_id: User.first.id, extension_id: 111 },
  { id: '2723', name: 'Belam', user_id: User.first.id, extension_id: 111 },
  { id: '2724', name: 'Chongti', user_id: User.first.id, extension_id: 111 },
  { id: '2725', name: 'Durtsun', user_id: User.first.id, extension_id: 111 },
  { id: '2726', name: 'Gonminang', user_id: User.first.id, extension_id: 111 },
  { id: '2727', name: 'Jalamwoong', user_id: User.first.id, extension_id: 111 },
  { id: '2728', name: 'Jangchubling', user_id: User.first.id, extension_id: 111 },
  { id: '2729', name: 'Malang', user_id: User.first.id, extension_id: 111 },
  { id: '2730', name: 'Mandar', user_id: User.first.id, extension_id: 111 },
  { id: '2731', name: 'Mantsang', user_id: User.first.id, extension_id: 111 },
  { id: '2732', name: 'Menchari', user_id: User.first.id, extension_id: 111 },
  { id: '2733', name: 'Milum', user_id: User.first.id, extension_id: 111 },
  { id: '2734', name: 'Mitseshing', user_id: User.first.id, extension_id: 111 },
  { id: '2735', name: 'Morong', user_id: User.first.id, extension_id: 111 },
  { id: '2736', name: 'Nabar', user_id: User.first.id, extension_id: 111 },
  { id: '2737', name: 'Nakzor', user_id: User.first.id, extension_id: 111 },
  { id: '2738', name: 'Pheldung', user_id: User.first.id, extension_id: 111 },
  { id: '2739', name: 'Pheluma', user_id: User.first.id, extension_id: 111 },
  { id: '2740', name: 'Phu', user_id: User.first.id, extension_id: 111 },
  { id: '2741', name: 'Redume', user_id: User.first.id, extension_id: 111 },
  { id: '2742', name: 'Remung', user_id: User.first.id, extension_id: 111 },
  { id: '2743', name: 'Suzung', user_id: User.first.id, extension_id: 111 },
  { id: '2744', name: 'Tershiree', user_id: User.first.id, extension_id: 111 },
  { id: '2745', name: 'Thungshing', user_id: User.first.id, extension_id: 111 },
  { id: '2746', name: 'Wooling', user_id: User.first.id, extension_id: 111 },
  { id: '4730', name: 'Tokorong', user_id: User.first.id, extension_id: 111 }
].each do |v|
  Village.find_or_create_by!(v)
end
