# frozen_string_literal: true

puts 'Seeding villages of Samtse...'
[
  # Norgaygang (Bara)
  { id: '2882', name: 'Tsha Chhu(Assamtsa)', user_id: User.first.id, extension_id: 117 },
  { id: '2883', name: 'Patshaling(Beteni)', user_id: User.first.id, extension_id: 117 },
  { id: '2884', name: 'Dangrey bug(Bich Gaon)', user_id: User.first.id, extension_id: 117 },
  { id: '2885', name: 'Chongzhu(Chanju)', user_id: User.first.id, extension_id: 117 },
  { id: '2886', name: 'Chhungu(Chingu)', user_id: User.first.id, extension_id: 117 },
  { id: '2887', name: 'Miphelgang(Dhakal Gaon)', user_id: User.first.id, extension_id: 117 },
  { id: '2888', name: 'Dugphey(Dubey)', user_id: User.first.id, extension_id: 117 },
  { id: '2889', name: 'Phendegang(Fenchi)', user_id: User.first.id, extension_id: 117 },
  { id: '2890', name: 'Joenpang(Gempang)', user_id: User.first.id, extension_id: 117 },
  { id: '2891', name: 'Guengaling(Ghunday Gaon)', user_id: User.first.id, extension_id: 117 },
  { id: '2892', name: 'Karmaling(Kami Gaon)', user_id: User.first.id, extension_id: 117 },
  { id: '2893', name: 'Samphelgang(Lepcha Gaon)', user_id: User.first.id, extension_id: 117 },
  { id: '2894', name: 'Lingarnang(Lingtam)', user_id: User.first.id, extension_id: 117 },
  { id: '2895', name: 'Norgeygang(Lower Bara)', user_id: User.first.id, extension_id: 117 },
  { id: '2896', name: 'Satsangma(Majuwa)', user_id: User.first.id, extension_id: 117 },
  { id: '2897', name: 'Zhendebgang(Mukheni Gaon)', user_id: User.first.id, extension_id: 117 },
  { id: '2898', name: 'Noryog(Nayak)', user_id: User.first.id, extension_id: 117 },
  { id: '2899', name: 'Khababgang(Thika)', user_id: User.first.id, extension_id: 117 },

  # Pemaling (Biru)
  { id: '2901', name: 'Damtshanang(Ahaley)', user_id: User.first.id, extension_id: 118 },
  { id: '2902', name: 'Komaling(Balsey)', user_id: User.first.id, extension_id: 118 },
  { id: '2903', name: 'Gatsheling(Baraney)', user_id: User.first.id, extension_id: 118 },
  { id: '2904', name: 'Jureygang(Bararay)', user_id: User.first.id, extension_id: 118 },
  { id: '2905', name: 'Balsathang(Bimirey)', user_id: User.first.id, extension_id: 118 },
  { id: '2906', name: 'Tamchhabsa(Birukhola)', user_id: User.first.id, extension_id: 118 },
  { id: '2907', name: 'Thangchhenang(Birutar)', user_id: User.first.id, extension_id: 118 },
  { id: '2908', name: 'Khangzhima(Chargharey)', user_id: User.first.id, extension_id: 118 },
  { id: '2909', name: 'Chhujugthang(Chhetritar)', user_id: User.first.id, extension_id: 118 },
  { id: '2910', name: 'Chhusilgang(Chisopani)', user_id: User.first.id, extension_id: 118 },
  { id: '2911', name: 'Chhoetenkha(Deorali)', user_id: User.first.id, extension_id: 118 },
  { id: '2912', name: 'Neydagling(Dhamigaon)', user_id: User.first.id, extension_id: 118 },
  { id: '2913', name: 'Ngadungsa(Dhengrey)', user_id: User.first.id, extension_id: 118 },
  { id: '2914', name: 'Nyachhabsa(Gangatey)', user_id: User.first.id, extension_id: 118 },
  { id: '2915', name: 'Pagsamthang(Ghondeytar)', user_id: User.first.id, extension_id: 118 },
  { id: '2916', name: 'Tsajnsa Ka(Hatikharka A)', user_id: User.first.id, extension_id: 118 },
  { id: '2917', name: 'Tsajnsa Kha(Hatikharka B)', user_id: User.first.id, extension_id: 118 },
  { id: '2918', name: 'Darzhingthang(Jagatar)', user_id: User.first.id, extension_id: 118 },
  { id: '2919', name: 'Pangthangjug(Jhandey)', user_id: User.first.id, extension_id: 118 },
  { id: '2920', name: 'Shingdegang(Jyamirkot)', user_id: User.first.id, extension_id: 118 },
  { id: '2921', name: 'Pemaling(Kamigaon)', user_id: User.first.id, extension_id: 118 },
  { id: '2922', name: 'Dramzeling(Kataray)', user_id: User.first.id, extension_id: 118 },
  { id: '2923', name: 'Nyadoesa(Katley)', user_id: User.first.id, extension_id: 118 },
  { id: '2924', name: 'Shing Ngarma(Khamarey)', user_id: User.first.id, extension_id: 118 },
  { id: '2925', name: 'Dizanggang(Khopi)', user_id: User.first.id, extension_id: 118 },
  { id: '2926', name: 'Yurungthang(Khopitar)', user_id: User.first.id, extension_id: 118 },
  { id: '2927', name: 'Beyulgang(Kopchey)', user_id: User.first.id, extension_id: 118 },
  { id: '2928', name: 'Lamaithang(Lamatar)', user_id: User.first.id, extension_id: 118 },
  { id: '2929', name: 'Manidara', user_id: User.first.id, extension_id: 118 },
  { id: '2930', name: 'Manigang(Manidara/Gangatey)', user_id: User.first.id, extension_id: 118 },
  { id: '2931', name: 'Nakeling(Nigurey)', user_id: User.first.id, extension_id: 118 },
  { id: '2932', name: 'Zamthangnang(Sagutar)', user_id: User.first.id, extension_id: 118 },
  { id: '2933', name: 'Tsakethang(Samatar)', user_id: User.first.id, extension_id: 118 },
  { id: '2934', name: 'Dechengang(Sarki Gaon)', user_id: User.first.id, extension_id: 118 },
  { id: '2935', name: 'Lungtensa(Saureni)', user_id: User.first.id, extension_id: 118 },
  { id: '2936', name: 'Chhokorling(Schooley)', user_id: User.first.id, extension_id: 118 },
  { id: '2937', name: 'Damesa(Sepeni)', user_id: User.first.id, extension_id: 118 },
  { id: '2938', name: 'Lungsirma(Sirisey)', user_id: User.first.id, extension_id: 118 },
  { id: '2939', name: 'Tashithang(Tachey)', user_id: User.first.id, extension_id: 118 },
  { id: '2940', name: 'Norgeyling(Taley)', user_id: User.first.id, extension_id: 118 },
  { id: '2941', name: 'Gomsumposa(Tinratey)', user_id: User.first.id, extension_id: 118 },
  { id: '2942', name: 'Pekarling(Toribari)', user_id: User.first.id, extension_id: 118 },

  # Sang-Ngag-Chhoeling (Chargharey)
  { id: '2944', name: 'Bumpathang(Bahunitar)', user_id: User.first.id, extension_id: 119 },
  { id: '2945', name: 'Saduzhima Ka(Chargharay A)', user_id: User.first.id, extension_id: 119 },
  { id: '2946', name: 'Saduzhima Kha(Chargharay B)', user_id: User.first.id, extension_id: 119 },
  { id: '2947', name: 'Chungthung', user_id: User.first.id, extension_id: 119 },
  { id: '2948', name: 'Depheling Ka(Gathiya A)', user_id: User.first.id, extension_id: 119 },
  { id: '2949', name: 'Depheling Kha(Gathiya B)', user_id: User.first.id, extension_id: 119 },
  { id: '2950', name: 'Depheling Ga(Gathiya C)', user_id: User.first.id, extension_id: 119 },
  { id: '2951', name: 'Depheling Nga(Gathiya D)', user_id: User.first.id, extension_id: 119 },
  { id: '2952', name: 'Chhunchhungsa Ka(Jitti A)', user_id: User.first.id, extension_id: 119 },
  { id: '2953', name: 'Chhunchhungsa Kha(Jitti B)', user_id: User.first.id, extension_id: 119 },
  { id: '2954', name: 'Chhunchhungsa Ga(Jitti C)', user_id: User.first.id, extension_id: 119 },
  { id: '2955', name: 'Khangzangling(Labarbot)', user_id: User.first.id, extension_id: 119 },
  { id: '2956', name: 'Tsangchushong(Latakhola)', user_id: User.first.id, extension_id: 119 },
  { id: '2957', name: 'Lingthang(Lengthey)', user_id: User.first.id, extension_id: 119 },
  { id: '2958', name: 'Karsel ling(Mongargaon)', user_id: User.first.id, extension_id: 119 },
  { id: '2959', name: 'Namseling', user_id: User.first.id, extension_id: 119 },
  { id: '2960', name: 'Khangchung Gang(Pakhadura)', user_id: User.first.id, extension_id: 119 },
  { id: '2961', name: 'Khamzangling(Satvaiya)', user_id: User.first.id, extension_id: 119 },
  { id: '2962', name: 'Joenlegsa(Setipekha)', user_id: User.first.id, extension_id: 119 },
  { id: '2963', name: 'Nidupling Ka(Sombek A)', user_id: User.first.id, extension_id: 119 },
  { id: '2964', name: 'Nidupling Kha(Sombek B)', user_id: User.first.id, extension_id: 119 },
  { id: '2965', name: 'Nidupling Ga(Sombek C)', user_id: User.first.id, extension_id: 119 },
  { id: '2966', name: 'Khangthongsumpa(Tintalay)', user_id: User.first.id, extension_id: 119 },
  { id: '2967', name: 'Tharpung(Tharphu)', user_id: User.first.id, extension_id: 119 },

  # Doomtoed
  { id: '3036', name: 'Daragaon', user_id: User.first.id, extension_id: 120 },
  { id: '3037', name: 'Gairigaon', user_id: User.first.id, extension_id: 120 },
  { id: '3038', name: 'Jarikha(Jaringay)', user_id: User.first.id, extension_id: 120 },
  { id: '3039', name: 'Tongpaling(Khaling Goan)', user_id: User.first.id, extension_id: 120 },
  { id: '3040', name: 'Kuzhuggang(Kuchey)', user_id: User.first.id, extension_id: 120 },
  { id: '3041', name: 'Dumtob chhungwa(Sanu Dumtoe)', user_id: User.first.id, extension_id: 120 },
  { id: '3042', name: 'Dumtob chhewa(Thulo Dumtoe)', user_id: User.first.id, extension_id: 120 },
  { id: '3043', name: 'Phuchena', user_id: User.first.id, extension_id: 120 },
  { id: '3044', name: 'Gibjee', user_id: User.first.id, extension_id: 120 },

  # Duenchhukha
  { id: '2988', name: 'Gawaling(Baseni)', user_id: User.first.id, extension_id: 121 },
  { id: '2989', name: 'Phazhing(Beteni)', user_id: User.first.id, extension_id: 121 },
  { id: '2990', name: 'Domchhukha(Bhalukhola)', user_id: User.first.id, extension_id: 121 },
  { id: '2991', name: 'Damji(Demjee)', user_id: User.first.id, extension_id: 121 },
  { id: '2992', name: 'Denchhukha(Denchukha)', user_id: User.first.id, extension_id: 121 },
  { id: '2993', name: 'Denchukha /Gajbee', user_id: User.first.id, extension_id: 121 },
  { id: '2994', name: 'Gaji(Gabjee)', user_id: User.first.id, extension_id: 121 },
  { id: '2995', name: 'Kharzhing(Kadori)', user_id: User.first.id, extension_id: 121 },
  { id: '2996', name: 'Khempaling(Khempa)', user_id: User.first.id, extension_id: 121 },
  { id: '2997', name: 'Relukha', user_id: User.first.id, extension_id: 121 },
  { id: '2998', name: 'Setekha', user_id: User.first.id, extension_id: 121 },
  { id: '2999', name: 'Benyekha(Benekha)', user_id: User.first.id, extension_id: 121 },
  { id: '3000', name: 'Gesarling(Boribotey)', user_id: User.first.id, extension_id: 121 },
  { id: '3001', name: 'Drameling(Dhamiley)', user_id: User.first.id, extension_id: 121 },
  { id: '3002', name: 'Yomeling(Mayona)', user_id: User.first.id, extension_id: 121 },
  { id: '3003', name: 'Mayona/Dhamiley', user_id: User.first.id, extension_id: 121 },
  { id: '3004', name: 'Pungtha A', user_id: User.first.id, extension_id: 121 },
  { id: '3005', name: 'Pungtha B', user_id: User.first.id, extension_id: 121 },
  { id: '3006', name: 'Gabjee/Mayona', user_id: User.first.id, extension_id: 121 },

  # Dophuchen (Dorokha)
  { id: '3008', name: 'Chhuka(Basantey)', user_id: User.first.id, extension_id: 122 },
  { id: '3009', name: 'Dangreybug Ka(Beachgaon A)', user_id: User.first.id, extension_id: 122 },
  { id: '3010', name: 'Dangreybug Kha(Beachgoan)', user_id: User.first.id, extension_id: 122 },
  { id: '3011', name: 'Chilumchen(Chelumchen)', user_id: User.first.id, extension_id: 122 },
  { id: '3012', name: 'Ngagang(Damphuchen)', user_id: User.first.id, extension_id: 122 },
  { id: '3013', name: 'Gangtogkha(Daragaon)', user_id: User.first.id, extension_id: 122 },
  { id: '3014', name: 'Daragoan', user_id: User.first.id, extension_id: 122 },
  { id: '3015', name: 'Dograp(Dogap)', user_id: User.first.id, extension_id: 122 },
  { id: '3016', name: 'Dokarkha Ka(Dorokha A)', user_id: User.first.id, extension_id: 122 },
  { id: '3017', name: 'Dokarkha Kha(Dorokha B)', user_id: User.first.id, extension_id: 122 },
  { id: '3018', name: 'Dokarkha Ga(Dorokha C)', user_id: User.first.id, extension_id: 122 },
  { id: '3019', name: 'Jigme', user_id: User.first.id, extension_id: 122 },
  { id: '3020', name: 'Legpagang(Lapchey Goan)', user_id: User.first.id, extension_id: 122 },
  { id: '3021', name: 'Manidangrey Ka(Maney A)', user_id: User.first.id, extension_id: 122 },
  { id: '3022', name: 'Manidangrey Kha(Maney B)', user_id: User.first.id, extension_id: 122 },
  { id: '3023', name: 'Bamengang(Mithun)', user_id: User.first.id, extension_id: 122 },
  { id: '3024', name: 'Namchu', user_id: User.first.id, extension_id: 122 },
  { id: '3025', name: 'Sanglung', user_id: User.first.id, extension_id: 122 },
  { id: '3026', name: 'Tengshog(Satakha)', user_id: User.first.id, extension_id: 122 },
  { id: '3027', name: 'Melonggang(Sebichang)', user_id: User.first.id, extension_id: 122 },
  { id: '3028', name: 'Sengteng', user_id: User.first.id, extension_id: 122 },
  { id: '3029', name: 'Singgye', user_id: User.first.id, extension_id: 122 },
  { id: '3030', name: 'Mizomsa(Somlachen)', user_id: User.first.id, extension_id: 122 },
  { id: '3031', name: 'Aringgang(Tarigaon)', user_id: User.first.id, extension_id: 122 },
  { id: '3032', name: 'Thulunggang(Thulung Gang)', user_id: User.first.id, extension_id: 122 },
  { id: '3033', name: 'Thingyersa(Timburey)', user_id: User.first.id, extension_id: 122 },
  { id: '3034', name: 'Wangchuk', user_id: User.first.id, extension_id: 122 }
].each do |v|
  Village.find_or_create_by!(v)
end
