# frozen_string_literal: true

[
  # Namgyalchhoeling
  { id: '3064', name: 'Bibi', user_id: User.first.id, extension_id: 123 },
  { id: '3065', name: 'Chinga', user_id: User.first.id, extension_id: 123 },
  { id: '3066', name: 'Chhodagling(Choksa)', user_id: User.first.id, extension_id: 123 },
  { id: '3067', name: 'Dongchey', user_id: User.first.id, extension_id: 123 },
  { id: '3068', name: 'Gangtog(Gyanthok)', user_id: User.first.id, extension_id: 123 },
  { id: '3069', name: 'Namgaychholing(Hangay)', user_id: User.first.id, extension_id: 123 },
  { id: '3070', name: 'Chhunaggang(Kalikhola)', user_id: User.first.id, extension_id: 123 },
  { id: '3071', name: 'Sernyagang(Kholakharka)', user_id: User.first.id, extension_id: 123 },
  { id: '3072', name: 'Satsangsa(Majuwa)', user_id: User.first.id, extension_id: 123 },
  { id: '3073', name: 'Pagshingkha(Malbasay)', user_id: User.first.id, extension_id: 123 },
  { id: '3074', name: 'Tsachhungang(Noonpani)', user_id: User.first.id, extension_id: 123 },
  { id: '3075', name: 'Tsholingkhar(Pokhari Dara)', user_id: User.first.id, extension_id: 123 },
  { id: '3076', name: 'Gyelposhing(Raja Rukh)', user_id: User.first.id, extension_id: 123 },
  { id: '3077', name: 'Tshosarling(Rangedara)', user_id: User.first.id, extension_id: 123 },
  { id: '3078', name: 'Shyma', user_id: User.first.id, extension_id: 123 },
  { id: '3079', name: 'Yaba', user_id: User.first.id, extension_id: 123 },

  # Phuentshogpelri (Pugli)
  { id: '3103', name: 'Dewthang(Banstar)', user_id: User.first.id, extension_id: 124 },
  { id: '3104', name: 'Gaden(Bhotaykharka)', user_id: User.first.id, extension_id: 124 },
  { id: '3105', name: 'Neygang(Damdara)', user_id: User.first.id, extension_id: 124 },
  { id: '3106', name: 'Doleg(Dholay)', user_id: User.first.id, extension_id: 124 },
  { id: '3107', name: 'Yulgeyeling(Dolomthang)', user_id: User.first.id, extension_id: 124 },
  { id: '3108', name: 'Dhumshigang(Dumshidara)', user_id: User.first.id, extension_id: 124 },
  { id: '3109', name: 'Gashingma(Gashing)', user_id: User.first.id, extension_id: 124 },
  { id: '3110', name: 'Goenpakha(Gombadara)', user_id: User.first.id, extension_id: 124 },
  { id: '3111', name: 'Peldenling(Gomtu)', user_id: User.first.id, extension_id: 124 },
  { id: '3112', name: 'Chhunag(Kalapani)', user_id: User.first.id, extension_id: 124 },
  { id: '3113', name: 'Satergang(Khanigaon)', user_id: User.first.id, extension_id: 124 },
  { id: '3114', name: 'Lachhungthang(Lahatar)', user_id: User.first.id, extension_id: 124 },
  { id: '3115', name: 'Tashitshe(Lechi)', user_id: User.first.id, extension_id: 124 },
  { id: '3116', name: 'Tashilakha(Numlakha)', user_id: User.first.id, extension_id: 124 },
  { id: '3117', name: 'Satorma(Pangray)', user_id: User.first.id, extension_id: 124 },
  { id: '3118', name: 'Nyoenpaling A(Pugli A)', user_id: User.first.id, extension_id: 124 },
  { id: '3119', name: 'Nyoenpaling B(Pugli B)', user_id: User.first.id, extension_id: 124 },
  { id: '3120', name: 'Nyoenpaling C(Pugli C)', user_id: User.first.id, extension_id: 124 },
  { id: '3121', name: 'Samerchan(Ratey)', user_id: User.first.id, extension_id: 124 },
  { id: '3122', name: 'Ketshelgang(Thotney)', user_id: User.first.id, extension_id: 124 },
  { id: '3123', name: 'Thongjabi(Thumkey)', user_id: User.first.id, extension_id: 124 },
  { id: '3124', name: 'Chhutharsum(Tindharey)', user_id: User.first.id, extension_id: 124 },
  { id: '3125', name: 'Tingtingma(Titi)', user_id: User.first.id, extension_id: 124 },
  { id: '3126', name: 'Jancholing(Uttarey)', user_id: User.first.id, extension_id: 124 },

  # Samtse
  { id: '3128', name: 'Damtshangma(Ahalay)', user_id: User.first.id, extension_id: 125 },
  { id: '3129', name: 'Dewathang(Banstar)', user_id: User.first.id, extension_id: 125 },
  { id: '3130', name: 'Majathang(Budhuney)', user_id: User.first.id, extension_id: 125 },
  { id: '3131', name: 'Yulu Ka(Bukay A)', user_id: User.first.id, extension_id: 125 },
  { id: '3132', name: 'Yulu Kha(Bukay B)', user_id: User.first.id, extension_id: 125 },
  { id: '3133', name: 'Bugtognang(Bukkay)', user_id: User.first.id, extension_id: 125 },
  { id: '3134', name: 'Chhirlogsa(Chiloo)', user_id: User.first.id, extension_id: 125 },
  { id: '3135', name: 'Dungkharling(Choilicoop)', user_id: User.first.id, extension_id: 125 },
  { id: '3136', name: 'Yugo(Daragoan)', user_id: User.first.id, extension_id: 125 },
  { id: '3137', name: 'Satshamchhu(Duarpani)', user_id: User.first.id, extension_id: 125 },
  { id: '3138', name: 'Norbuling(Gairigoan)', user_id: User.first.id, extension_id: 125 },
  { id: '3139', name: 'Goenpazor(Gombadara)', user_id: User.first.id, extension_id: 125 },
  { id: '3140', name: 'Serthang(Khalingtar)', user_id: User.first.id, extension_id: 125 },
  { id: '3141', name: 'Lamaithang(Lamatar)', user_id: User.first.id, extension_id: 125 },
  { id: '3142', name: 'Lingmaithang(Lamitar)', user_id: User.first.id, extension_id: 125 },
  { id: '3143', name: 'Tshongzom(Malabasey)', user_id: User.first.id, extension_id: 125 },
  { id: '3144', name: 'Lhakhanpong(Manderi)', user_id: User.first.id, extension_id: 125 },
  { id: '3145', name: 'Manderni', user_id: User.first.id, extension_id: 125 },
  { id: '3146', name: 'Khandothang(Mechetar)', user_id: User.first.id, extension_id: 125 },
  { id: '3147', name: 'Samtse', user_id: User.first.id, extension_id: 125 },
  { id: '3148', name: 'Chathakgang(Sangla)', user_id: User.first.id, extension_id: 125 },
  { id: '3149', name: 'Ninmaling(Saureni)', user_id: User.first.id, extension_id: 125 },
  { id: '3150', name: 'Gawadong(Sukraty)', user_id: User.first.id, extension_id: 125 },
  { id: '3151', name: 'Kipadong(Sukraty/Bauwandara)', user_id: User.first.id, extension_id: 125 },
  { id: '3152', name: 'Taserpo(Tasim)', user_id: User.first.id, extension_id: 125 },
  { id: '3153', name: 'Jangchhogling(Uttary)', user_id: User.first.id, extension_id: 125 },

  # Tading
  { id: 5010, name: 'Domtshang(Balukoray)', user_id: User.first.id, extension_id: 127 },
  { id: 5011, name: 'Dangreybug(Beachgaon)', user_id: User.first.id, extension_id: 127 },
  { id: 5012, name: 'Tobchenthang(Borbotey)', user_id: User.first.id, extension_id: 127 },
  { id: 5013, name: 'Bugkha(Bucca)', user_id: User.first.id, extension_id: 127 },
  { id: 5014, name: 'Gangtokha(Daragaon)', user_id: User.first.id, extension_id: 127 },
  { id: 5015, name: 'Jinpathang(Deotey)', user_id: User.first.id, extension_id: 127 },
  { id: 5016, name: 'Norjangsa Nyipa(Gairigaon Dhue Number)', user_id: User.first.id, extension_id: 127 },
  { id: 5017, name: 'Norjangsa Dangpa(Gairigaon Ek Number)', user_id: User.first.id, extension_id: 127 },
  { id: 5018, name: 'Sherabling(Jenchu Gaon)', user_id: User.first.id, extension_id: 127 },
  { id: 5019, name: 'Dugpoling(Kamai Banjang)', user_id: User.first.id, extension_id: 127 },
  { id: 5020, name: 'Khempagang(Khempa Gaon)', user_id: User.first.id, extension_id: 127 },
  { id: 5021, name: 'Lapchakha', user_id: User.first.id, extension_id: 127 },
  { id: 5022, name: 'Panzhingn Wogma(Lower Panbari)', user_id: User.first.id, extension_id: 127 },
  { id: 5023, name: 'Nindulakha', user_id: User.first.id, extension_id: 127 },
  { id: 5024, name: 'Thongsa(Ramtey)', user_id: User.first.id, extension_id: 127 },
  { id: 5025, name: 'Zochhaling(Sisney)', user_id: User.first.id, extension_id: 127 },
  { id: 5026, name: 'Tababgang(Tabagaon)', user_id: User.first.id, extension_id: 127 },
  { id: 5027, name: 'Tading', user_id: User.first.id, extension_id: 127 },
  { id: 5028, name: 'Damzhagsa(Thunuwa)', user_id: User.first.id, extension_id: 127 },
  { id: 5029, name: 'Tenpaling(Titiring)', user_id: User.first.id, extension_id: 127 },
  { id: 5030, name: 'Panzhing Gogma(Upper Panbari)', user_id: User.first.id, extension_id: 127 },

  # Tendruk
  { id: '3190', name: 'Silwaithang(Bakbakey)', user_id: User.first.id, extension_id: 128 },
  { id: '3191', name: 'Domdangsa(Balukhop)', user_id: User.first.id, extension_id: 128 },
  { id: '3192', name: 'Dangreybug(Bichgaon)', user_id: User.first.id, extension_id: 128 },
  { id: '3193', name: 'Khangzhima(Chargarey)', user_id: User.first.id, extension_id: 128 },
  { id: '3194', name: 'Soeltapsa(D. Bindu)', user_id: User.first.id, extension_id: 128 },
  { id: '3195', name: 'Thagpzosa(Dhoreni)', user_id: User.first.id, extension_id: 128 },
  { id: '3196', name: 'Chhermaling(Fita)', user_id: User.first.id, extension_id: 128 },
  { id: '3197', name: 'Rangthagling(Jatey)', user_id: User.first.id, extension_id: 128 },
  { id: '3198', name: 'Dawathang(Jumsatar)', user_id: User.first.id, extension_id: 128 },
  { id: '3199', name: 'Dawthongsa(Jumsiligaon)', user_id: User.first.id, extension_id: 128 },
  { id: '3200', name: 'Kachhen(Kachin)', user_id: User.first.id, extension_id: 128 },
  { id: '3201', name: 'Khentong(Khengtong)', user_id: User.first.id, extension_id: 128 },
  { id: '3202', name: 'Kuchengang(Kuchin Pakha)', user_id: User.first.id, extension_id: 128 },
  { id: '3203', name: 'Kuchenthang(Kuchin Tar)', user_id: User.first.id, extension_id: 128 },
  { id: '3204', name: 'Kuchentoe(Kuchin Upper)', user_id: User.first.id, extension_id: 128 },
  { id: '3205', name: 'Miglamthang(N. Bindu)', user_id: User.first.id, extension_id: 128 },
  { id: '3206', name: 'Nizergang(Ningalay)', user_id: User.first.id, extension_id: 128 },
  { id: '3207', name: 'Terkothang(Okhar Botey)', user_id: User.first.id, extension_id: 128 },
  { id: '3208', name: 'Kuengaling(Pakpay)', user_id: User.first.id, extension_id: 128 },
  { id: '3209', name: 'Denpajong(Soureney)', user_id: User.first.id, extension_id: 128 },
  { id: '3210', name: 'Tendu', user_id: User.first.id, extension_id: 128 },
  { id: '3211', name: 'Tenduthang(Tendu Tar)', user_id: User.first.id, extension_id: 128 },
  { id: '3212', name: 'Dzongsar', user_id: User.first.id, extension_id: 128 },

  # Ugyentse (Nainital)
  { id: '3081', name: 'Dangkharling(BahunGaon)', user_id: User.first.id, extension_id: 129 },
  { id: '3082', name: 'Serigang(Bhotaykharka)', user_id: User.first.id, extension_id: 129 },
  { id: '3083', name: 'Dangreybug Ka(BichGaon A)', user_id: User.first.id, extension_id: 129 },
  { id: '3084', name: 'BichGaon A /Jangsa', user_id: User.first.id, extension_id: 129 },
  { id: '3085', name: 'BichGaon A /Khar', user_id: User.first.id, extension_id: 129 },
  { id: '3086', name: 'BichGaon A /Tashiding', user_id: User.first.id, extension_id: 129 },
  { id: '3087', name: 'Dangreybug Kha(BichGaon B)', user_id: User.first.id, extension_id: 129 },
  { id: '3088', name: 'Nimalung(BotayKharka)', user_id: User.first.id, extension_id: 129 },
  { id: '3089', name: 'Jarithang Ka(Jarip A)', user_id: User.first.id, extension_id: 129 },
  { id: '3090', name: 'Jarithang Kha(Jarip B)', user_id: User.first.id, extension_id: 129 },
  { id: '3091', name: 'Jarithang  Ga(Jarip C)', user_id: User.first.id, extension_id: 129 },
  { id: '3092', name: 'Jarip C /Ngatshang', user_id: User.first.id, extension_id: 129 },
  { id: '3093', name: 'Jyamirkot', user_id: User.first.id, extension_id: 129 },
  { id: '3094', name: 'Kardo Ka(Kado A)', user_id: User.first.id, extension_id: 129 },
  { id: '3095', name: 'Kardo Kha(Kado B)', user_id: User.first.id, extension_id: 129 },
  { id: '3096', name: 'Kardo Ga(Kado C)', user_id: User.first.id, extension_id: 129 },
  { id: '3097', name: 'Tharpaling(Majuwa)', user_id: User.first.id, extension_id: 129 },
  { id: '3098', name: 'Dechhengang(RaiGaon)', user_id: User.first.id, extension_id: 129 },
  { id: '3099', name: 'Rigpaling(Schooldara)', user_id: User.first.id, extension_id: 129 },
  { id: '3100', name: 'Schooldara /Tashiding', user_id: User.first.id, extension_id: 129 },
  { id: '3101', name: 'Lhendupling(Thakurigaon)', user_id: User.first.id, extension_id: 129 }
].each do |v|
  Village.find_or_create_by!(v)
end
