# frozen_string_literal: true

puts 'Seeding villages pf Sarpang...'
[
  # Chhuzanggang
  { id: '3221', name: 'Barthang', user_id: User.first.id, extension_id: 133 },
  { id: '3222', name: 'Barthang/Daragaon', user_id: User.first.id, extension_id: 133 },
  { id: '3223', name: 'Chaskhar', user_id: User.first.id, extension_id: 133 },
  { id: '3224', name: 'Chaskhar/Danabari', user_id: User.first.id, extension_id: 133 },
  { id: '3225', name: 'Chaskhar/Daragaon', user_id: User.first.id, extension_id: 133 },
  { id: '3226', name: 'Chaskhar/Dawathang', user_id: User.first.id, extension_id: 133 },
  { id: '3227', name: 'Chaskhar/Kalikhola', user_id: User.first.id, extension_id: 133 },
  { id: '3228', name: 'Chaskhar/Limbutar', user_id: User.first.id, extension_id: 133 },
  { id: '3229', name: 'Chaskhar/Somitar', user_id: User.first.id, extension_id: 133 },
  { id: '3230', name: 'Chaskhar/Thewar', user_id: User.first.id, extension_id: 133 },
  { id: '3231', name: 'Nimaling', user_id: User.first.id, extension_id: 133 },
  { id: '3232', name: 'Nimaling/Daragaon', user_id: User.first.id, extension_id: 133 },
  { id: '3233', name: 'Nimaling/Lower Phanphaney', user_id: User.first.id, extension_id: 133 },
  { id: '3234', name: 'Pangzor', user_id: User.first.id, extension_id: 133 },
  { id: '3235', name: 'Pangzor/Danabari', user_id: User.first.id, extension_id: 133 },
  { id: '3236', name: 'Pangzor/Daragaon', user_id: User.first.id, extension_id: 133 },
  { id: '3237', name: 'Pangzor/Kalikhola', user_id: User.first.id, extension_id: 133 },
  { id: '3238', name: 'Pangzor/Lower Phanphaney', user_id: User.first.id, extension_id: 133 },
  { id: '3239', name: 'Pangzor/Upper Phanphaney', user_id: User.first.id, extension_id: 133 },
  { id: '3240', name: 'Shawapong', user_id: User.first.id, extension_id: 133 },
  { id: '3241', name: 'Shawapong/Daragaon', user_id: User.first.id, extension_id: 133 },
  { id: '3242', name: 'Shawapong/Lower Phanphaney', user_id: User.first.id, extension_id: 133 },
  { id: '3243', name: 'Thongjabi', user_id: User.first.id, extension_id: 133 },
  { id: '3244', name: 'Thongjabi/Danabari', user_id: User.first.id, extension_id: 133 },
  { id: '3245', name: 'Thongjabi/Daragaon', user_id: User.first.id, extension_id: 133 },
  { id: '3246', name: 'Thongjabi/Lower Phanphaney', user_id: User.first.id, extension_id: 133 },
  { id: '3247', name: 'Tshojan', user_id: User.first.id, extension_id: 133 },
  { id: '3248', name: 'Tshojan/Lower Phanphaney', user_id: User.first.id, extension_id: 133 },
  { id: '3249', name: 'Yueling', user_id: User.first.id, extension_id: 133 },
  { id: '3250', name: 'Yueling/Danabari', user_id: User.first.id, extension_id: 133 },
  { id: '3251', name: 'Yueling/Daragaon', user_id: User.first.id, extension_id: 133 },
  { id: '3252', name: 'Yueling/Lower Phanphaney', user_id: User.first.id, extension_id: 133 },
  { id: '3253', name: 'Zombabi', user_id: User.first.id, extension_id: 133 },
  { id: '3254', name: 'Zombabi/Danabari', user_id: User.first.id, extension_id: 133 },
  { id: '3255', name: 'Zombabi/Daragaon', user_id: User.first.id, extension_id: 133 },

  # Chhudzom (Dovan)
  { id: '3275', name: 'Chunyethang(Baragaray)', user_id: User.first.id, extension_id: 134 },
  { id: '3276', name: 'Bachhuthang(Bechkhola)', user_id: User.first.id, extension_id: 134 },
  { id: '3277', name: 'Tsheluthang(Bhimirey)', user_id: User.first.id, extension_id: 134 },
  { id: '3278', name: 'Samtenphu(Daragaon)', user_id: User.first.id, extension_id: 134 },
  { id: '3279', name: 'Chhuzomsa(Dovan)', user_id: User.first.id, extension_id: 134 },
  { id: '3280', name: 'Rijugang(Fedi)', user_id: User.first.id, extension_id: 134 },
  { id: '3281', name: 'Chhibigang(Gairigaon)', user_id: User.first.id, extension_id: 134 },
  { id: '3282', name: 'Galegthang(Ghungring)', user_id: User.first.id, extension_id: 134 },
  { id: '3283', name: 'Norbugang(Khargaon)', user_id: User.first.id, extension_id: 134 },
  { id: '3284', name: 'Nyachhu(Machukhola)', user_id: User.first.id, extension_id: 134 },
  { id: '3285', name: 'Mautshangchhu(Maukhola)', user_id: User.first.id, extension_id: 134 },
  { id: '3286', name: 'Mongarling(Mongergaon)', user_id: User.first.id, extension_id: 134 },
  { id: '3287', name: 'Lhayul(Mougaon)', user_id: User.first.id, extension_id: 134 },
  { id: '3288', name: 'Dechenling(Nunpani)', user_id: User.first.id, extension_id: 134 },
  { id: '3289', name: 'Jangchubling(Pankhey)', user_id: User.first.id, extension_id: 134 },
  { id: '3290', name: 'Sherabling(Pathibara)', user_id: User.first.id, extension_id: 134 },
  { id: '3291', name: 'Pelrigang(Rametay)', user_id: User.first.id, extension_id: 134 },
  { id: '3292', name: 'Azhethang(Ranikhop)', user_id: User.first.id, extension_id: 134 },
  { id: '3293', name: 'Thongjabi(Tarkharkha)', user_id: User.first.id, extension_id: 134 },
  { id: '3294', name: 'Dragchhu(Tirkhola)', user_id: User.first.id, extension_id: 134 },
  { id: '3295', name: 'Hungrelthang(Torkey)', user_id: User.first.id, extension_id: 134 },

  # Dekiling
  { id: '3257', name: 'Meldrelgang(Bichpani)', user_id: User.first.id, extension_id: 135 },
  { id: '3258', name: 'Chhokhorling(Toribari)', user_id: User.first.id, extension_id: 135 },
  { id: '3259', name: 'Jigmiling(Chuwabari)', user_id: User.first.id, extension_id: 135 },
  { id: '3260', name: 'Darbithang/Sukhatar', user_id: User.first.id, extension_id: 135 },
  { id: '3261', name: 'Dekiling/Leopani', user_id: User.first.id, extension_id: 135 },
  { id: '3262', name: 'Nubgang(Dolpani)', user_id: User.first.id, extension_id: 135 },
  { id: '3263', name: 'Dolongang(Gairigoan)', user_id: User.first.id, extension_id: 135 },
  { id: '3264', name: 'Gawaithang/Kafleytar', user_id: User.first.id, extension_id: 135 },
  { id: '3265', name: 'Hamlingphu(Leokhop)', user_id: User.first.id, extension_id: 135 },
  { id: '3266', name: 'Lungtenbi/Sukhatar', user_id: User.first.id, extension_id: 135 },
  { id: '3267', name: 'Norbuthang/Kafleytar', user_id: User.first.id, extension_id: 135 },
  { id: '3268', name: 'Phurpaling(Patabari)', user_id: User.first.id, extension_id: 135 },
  { id: '3269', name: 'Menchuthang(Rateygoan)', user_id: User.first.id, extension_id: 135 },
  { id: '3270', name: 'Rateypani', user_id: User.first.id, extension_id: 135 },
  { id: '3271', name: 'Dabithang(Sukhatar)', user_id: User.first.id, extension_id: 135 },
  { id: '3272', name: 'Tashiling(Lampatey)', user_id: User.first.id, extension_id: 135 },
  { id: '3273', name: 'Yangchenphu(Kafleytar)', user_id: User.first.id, extension_id: 135 },

  # Gakiling (Hilley)
  { id: '3313', name: 'Balchhangchhu(Belkhola)', user_id: User.first.id, extension_id: 136 },
  { id: '3314', name: 'Bunakha(Bisty)', user_id: User.first.id, extension_id: 136 },
  { id: '3315', name: 'Dragphuchhen(Gangatey)', user_id: User.first.id, extension_id: 136 },
  { id: '3316', name: 'Gakiling(Hilley)', user_id: User.first.id, extension_id: 136 },
  { id: '3317', name: 'Chursini(Kagatey)', user_id: User.first.id, extension_id: 136 },
  { id: '3318', name: 'Menchhulam(Kharpani)', user_id: User.first.id, extension_id: 136 },
  { id: '3319', name: 'Omchhunang(Kwapani)', user_id: User.first.id, extension_id: 136 },
  { id: '3320', name: 'Getemkha(Laring)', user_id: User.first.id, extension_id: 136 },
  { id: '3321', name: 'Jachhu(Muga)', user_id: User.first.id, extension_id: 136 },
  { id: '3322', name: 'Rilangthang(Noonpani)', user_id: User.first.id, extension_id: 136 },
  { id: '3323', name: 'Sangkha(Rateypani)', user_id: User.first.id, extension_id: 136 },

  # Gelegphu
  { id: '3297', name: 'Dzomlingthang', user_id: User.first.id, extension_id: 137 },
  { id: '3298', name: 'Dzomlingthang/Mainatar', user_id: User.first.id, extension_id: 137 },
  { id: '3299', name: 'Lakhitar', user_id: User.first.id, extension_id: 137 },
  { id: '3300', name: 'Pelrithang', user_id: User.first.id, extension_id: 137 },
  { id: '3301', name: 'Pelrithang /Mainatar', user_id: User.first.id, extension_id: 137 },
  { id: '3302', name: 'Pelrithang/Lodrai', user_id: User.first.id, extension_id: 137 },
  { id: '3303', name: 'Pelrithang/Puranobusty', user_id: User.first.id, extension_id: 137 },
  { id: '3304', name: 'Pelrithang/Somitar', user_id: User.first.id, extension_id: 137 },
  { id: '3305', name: 'Pemathang/Somitar', user_id: User.first.id, extension_id: 137 },
  { id: '3306', name: 'Puranobusty', user_id: User.first.id, extension_id: 137 },
  { id: '3307', name: 'Puranobusty/Juprey', user_id: User.first.id, extension_id: 137 },
  { id: '3308', name: 'Puranobusty/Lodari', user_id: User.first.id, extension_id: 137 },
  { id: '3309', name: 'Puranobusty/Luckytar', user_id: User.first.id, extension_id: 137 },
  { id: '3310', name: 'Puranobusty/Mainatar', user_id: User.first.id, extension_id: 137 },
  { id: '3311', name: 'Puranobusty/Somitar', user_id: User.first.id, extension_id: 137 },

  # Jigme Chhoeling
  { id: '3325', name: 'Serbugang(Ashiney)', user_id: User.first.id, extension_id: 138 },
  { id: '3326', name: 'Tagjogang(Bagjungay)', user_id: User.first.id, extension_id: 138 },
  { id: '3327', name: 'Lungsilgang(Batasey)', user_id: User.first.id, extension_id: 138 },
  { id: '3328', name: 'Pachhakha(Beteni)', user_id: User.first.id, extension_id: 138 },
  { id: '3329', name: 'Mendelgang(Bhirgaon)', user_id: User.first.id, extension_id: 138 },
  { id: '3330', name: 'Bartsham Ka(Khatoe/Bichgaon A)', user_id: User.first.id, extension_id: 138 },
  { id: '3331', name: 'Bartsham Kha(Khamae/Bichgaon B)', user_id: User.first.id, extension_id: 138 },
  { id: '3332', name: 'Tashigatshel(Chakpai)', user_id: User.first.id, extension_id: 138 },
  { id: '3333', name: 'Chungsing', user_id: User.first.id, extension_id: 138 },
  { id: '3334', name: 'Khamed(Daragaon)', user_id: User.first.id, extension_id: 138 },
  { id: '3335', name: 'Doringphu(Dungay)', user_id: User.first.id, extension_id: 138 },
  { id: '3336', name: 'Hokaling(Gairigaon)', user_id: User.first.id, extension_id: 138 },
  { id: '3337', name: 'Galegchu(Galeychu)', user_id: User.first.id, extension_id: 138 },
  { id: '3338', name: 'Gongduegang(Gong Gaon)', user_id: User.first.id, extension_id: 138 },
  { id: '3339', name: 'Gongtsekha(Gongdara)', user_id: User.first.id, extension_id: 138 },
  { id: '3340', name: 'Khamey', user_id: User.first.id, extension_id: 138 },
  { id: '3341', name: 'Khamo', user_id: User.first.id, extension_id: 138 },
  { id: '3342', name: 'Khateo', user_id: User.first.id, extension_id: 138 },
  { id: '3343', name: 'Gakiling(Kholatar)', user_id: User.first.id, extension_id: 138 },
  { id: '3344', name: 'Monchhukha(Mongergaon)', user_id: User.first.id, extension_id: 138 },
  { id: '3345', name: 'Silsagang(Ossey)', user_id: User.first.id, extension_id: 138 },
  { id: '3346', name: 'Pemagang(Pakhey)', user_id: User.first.id, extension_id: 138 },
  { id: '3347', name: 'Shingkharthang(Samkhara)', user_id: User.first.id, extension_id: 138 },
  { id: '3348', name: 'Jungchhurgang(Saudalay)', user_id: User.first.id, extension_id: 138 },
  { id: '3349', name: 'Simkharka', user_id: User.first.id, extension_id: 138 },
  { id: '3350', name: 'Khatod(Sirangaon)', user_id: User.first.id, extension_id: 138 },
  { id: '3351', name: 'Chhotenkhar(Sukumbasi)', user_id: User.first.id, extension_id: 138 },
  { id: '3352', name: 'Tshachhu(Tatopani)', user_id: User.first.id, extension_id: 138 },
  { id: '3353', name: 'Tormaphu(Tormay)', user_id: User.first.id, extension_id: 138 },
  { id: '3354', name: 'Riti(Reti)', user_id: User.first.id, extension_id: 138 },

  # Samtenling (Bhur)
  { id: '3215', name: 'Samtenling(Bhur)', user_id: User.first.id, extension_id: 139 },
  { id: '3216', name: 'Dechenpelri(Jaruwa)', user_id: User.first.id, extension_id: 139 },
  { id: '3217', name: 'Samtenthang(Juprey)', user_id: User.first.id, extension_id: 139 },
  { id: '3218', name: 'Samtengang(Jupreydara)', user_id: User.first.id, extension_id: 139 },
  { id: '3219', name: 'Chhokhorling(Majuwa)', user_id: User.first.id, extension_id: 139 }
].each do |v|
  Village.find_or_create_by!(v)
end
