# frozen_string_literal: true

puts 'Seeding villages of Thimphu...'

[
  # Chang
  { id: '3428', name: 'Babi  Chorten', user_id: User.first.id, extension_id: 145 },
  { id: '3429', name: 'Debsi', user_id: User.first.id, extension_id: 145 },
  { id: '3430', name: 'Gangcheb', user_id: User.first.id, extension_id: 145 },
  { id: '3431', name: 'Jalungkha', user_id: User.first.id, extension_id: 145 },
  { id: '3432', name: 'Jumo', user_id: User.first.id, extension_id: 145 },
  { id: '3433', name: 'Nezeylhakhang', user_id: User.first.id, extension_id: 145 },
  { id: '3434', name: 'Rama', user_id: User.first.id, extension_id: 145 },
  { id: '3435', name: 'Sarbethang', user_id: User.first.id, extension_id: 145 },
  { id: '3436', name: 'Ngachuphaka', user_id: User.first.id, extension_id: 145 },
  { id: '3437', name: 'Hongtsho', user_id: User.first.id, extension_id: 145 },
  { id: '3438', name: 'Yoeselpang', user_id: User.first.id, extension_id: 145 },
  { id: '3439', name: 'Ngabiphu', user_id: User.first.id, extension_id: 145 },

  # Lingzhi
  { id: '3469', name: 'Chakphu', user_id: User.first.id, extension_id: 146 },
  { id: '3470', name: 'Chakphu Meseryul', user_id: User.first.id, extension_id: 146 },
  { id: '3471', name: 'Chakphu Zanglingkha', user_id: User.first.id, extension_id: 146 },
  { id: '3472', name: 'Cheybesa', user_id: User.first.id, extension_id: 146 },
  { id: '3473', name: 'Chepisa', user_id: User.first.id, extension_id: 146 },
  { id: '3474', name: 'Gangyul', user_id: User.first.id, extension_id: 146 },
  { id: '3475', name: 'Zangmithang/Chakphu', user_id: User.first.id, extension_id: 146 },

  # Soe
  { id: '3538', name: 'Changmatasa', user_id: User.first.id, extension_id: 147 },
  { id: '3539', name: 'Dangochong', user_id: User.first.id, extension_id: 147 },
  { id: '3540', name: 'Dotoepthang', user_id: User.first.id, extension_id: 147 },
  { id: '3541', name: 'Dozoten', user_id: User.first.id, extension_id: 147 },
  { id: '3542', name: 'Gadraten', user_id: User.first.id, extension_id: 147 },
  { id: '3543', name: 'Jangothang', user_id: User.first.id, extension_id: 147 },
  { id: '3544', name: 'Jomphu', user_id: User.first.id, extension_id: 147 },
  { id: '3545', name: 'Kegithang', user_id: User.first.id, extension_id: 147 },
  { id: '3546', name: 'Toepgoethang', user_id: User.first.id, extension_id: 147 },

  # Ge
  { id: '3447', name: 'Chizhi Goenpa', user_id: User.first.id, extension_id: 148 },
  { id: '3448', name: 'Geneykha', user_id: User.first.id, extension_id: 148 },
  { id: '3449', name: 'Tshocheykha', user_id: User.first.id, extension_id: 148 },
  { id: '3450', name: 'Wangbama', user_id: User.first.id, extension_id: 148 },
  { id: '3451', name: 'Zangleykha', user_id: User.first.id, extension_id: 148 },

  # Kawang
  { id: '3453', name: 'Begana', user_id: User.first.id, extension_id: 149 },
  { id: '3454', name: 'Chamina', user_id: User.first.id, extension_id: 149 },
  { id: '3455', name: 'Changdagang', user_id: User.first.id, extension_id: 149 },
  { id: '3456', name: 'Chokor', user_id: User.first.id, extension_id: 149 },
  { id: '3457', name: 'Dazhi', user_id: User.first.id, extension_id: 149 },
  { id: '3458', name: 'Dechenphu', user_id: User.first.id, extension_id: 149 },
  { id: '3459', name: 'Deling Goenpa', user_id: User.first.id, extension_id: 149 },
  { id: '3460', name: 'Dodena', user_id: User.first.id, extension_id: 149 },
  { id: '3461', name: 'Janazampa', user_id: User.first.id, extension_id: 149 },
  { id: '3462', name: 'Kabisa', user_id: User.first.id, extension_id: 149 },
  { id: '3463', name: 'Kushugchen', user_id: User.first.id, extension_id: 149 },
  { id: '3464', name: 'Phading Goenpa', user_id: User.first.id, extension_id: 149 },
  { id: '3465', name: 'Shosul', user_id: User.first.id, extension_id: 149 },
  { id: '3466', name: 'Tashiding', user_id: User.first.id, extension_id: 149 },
  { id: '3467', name: 'Wangkawog', user_id: User.first.id, extension_id: 149 },
  { id: '4729', name: 'Kuengacholing Tag', user_id: User.first.id, extension_id: 149 },

  # Maedwang
  { id: '3477', name: 'Bemegasa', user_id: User.first.id, extension_id: 150 },
  { id: '3478', name: 'Chudingkha', user_id: User.first.id, extension_id: 150 },
  { id: '3479', name: 'Dalukha', user_id: User.first.id, extension_id: 150 },
  { id: '3480', name: 'Danglo', user_id: User.first.id, extension_id: 150 },
  { id: '3481', name: 'Drokpaisa', user_id: User.first.id, extension_id: 150 },
  { id: '3482', name: 'Dolepchen', user_id: User.first.id, extension_id: 150 },
  { id: '3483', name: 'Dramesa', user_id: User.first.id, extension_id: 150 },
  { id: '3484', name: 'Gida', user_id: User.first.id, extension_id: 150 },
  { id: '3485', name: 'Goenwog', user_id: User.first.id, extension_id: 150 },
  { id: '3486', name: 'Jampel', user_id: User.first.id, extension_id: 150 },
  { id: '3487', name: 'Jemina', user_id: User.first.id, extension_id: 150 },
  { id: '3488', name: 'Kepaithang', user_id: User.first.id, extension_id: 150 },
  { id: '3489', name: 'Khasadrapchu', user_id: User.first.id, extension_id: 150 },
  { id: '3490', name: 'Khasakha', user_id: User.first.id, extension_id: 150 },
  { id: '3491', name: 'Lamwog', user_id: User.first.id, extension_id: 150 },
  { id: '3492', name: 'Langdro', user_id: User.first.id, extension_id: 150 },
  { id: '3493', name: 'Lingzhipharka', user_id: User.first.id, extension_id: 150 },
  { id: '3494', name: 'Nyenzerkha', user_id: User.first.id, extension_id: 150 },
  { id: '3495', name: 'Paga Goenpa', user_id: User.first.id, extension_id: 150 },
  { id: '3496', name: 'Patsekha', user_id: User.first.id, extension_id: 150 },
  { id: '3497', name: 'Pulena', user_id: User.first.id, extension_id: 150 },
  { id: '3498', name: 'Pungzhi', user_id: User.first.id, extension_id: 150 },
  { id: '3499', name: 'Samakha', user_id: User.first.id, extension_id: 150 },
  { id: '3500', name: 'Selaykha', user_id: User.first.id, extension_id: 150 },
  { id: '3501', name: 'Sigay', user_id: User.first.id, extension_id: 150 },
  { id: '3502', name: 'Silidraphu', user_id: User.first.id, extension_id: 150 },
  { id: '3503', name: 'Siluna', user_id: User.first.id, extension_id: 150 },
  { id: '3504', name: 'Simu', user_id: User.first.id, extension_id: 150 },
  { id: '3505', name: 'Sisina', user_id: User.first.id, extension_id: 150 },
  { id: '3506', name: 'Tshaluna', user_id: User.first.id, extension_id: 150 },
  { id: '3507', name: 'Tshaphu', user_id: User.first.id, extension_id: 150 },
  { id: '3508', name: 'Walunang', user_id: User.first.id, extension_id: 150 },
  { id: '3509', name: 'Zhingsagang', user_id: User.first.id, extension_id: 150 },
  { id: '3510', name: 'Dongkarla', user_id: User.first.id, extension_id: 150 },
  { id: '3511', name: 'Jamdo', user_id: User.first.id, extension_id: 150 },
  { id: '3512', name: 'Jamdo Goma', user_id: User.first.id, extension_id: 150 },
  { id: '3513', name: 'Jamdowoma', user_id: User.first.id, extension_id: 150 },
  { id: '3514', name: 'Karphu', user_id: User.first.id, extension_id: 150 },
  { id: '3515', name: 'Kharibji', user_id: User.first.id, extension_id: 150 },
  { id: '3516', name: 'Kharphu', user_id: User.first.id, extension_id: 150 },
  { id: '3517', name: 'Segyelna/Karphu', user_id: User.first.id, extension_id: 150 },
  { id: '3518', name: 'Chimithangka', user_id: User.first.id, extension_id: 150 },
  { id: '3519', name: 'Jadingkha', user_id: User.first.id, extension_id: 150 },

  # Naro
  { id: '3521', name: 'Barshong', user_id: User.first.id, extension_id: 151 },
  { id: '3522', name: 'Chungdulo', user_id: User.first.id, extension_id: 151 },
  { id: '3523', name: 'Gangbu', user_id: User.first.id, extension_id: 151 },
  { id: '3524', name: 'Gunglona', user_id: User.first.id, extension_id: 151 },
  { id: '3525', name: 'Gyesho', user_id: User.first.id, extension_id: 151 },
  { id: '3526', name: 'Jagoethang', user_id: User.first.id, extension_id: 151 },
  { id: '3527', name: 'Khasho', user_id: User.first.id, extension_id: 151 },
  { id: '3528', name: 'Lhayulhaetoed', user_id: User.first.id, extension_id: 151 },
  { id: '3529', name: 'Menchiphu', user_id: User.first.id, extension_id: 151 },
  { id: '3530', name: 'Pagoe', user_id: User.first.id, extension_id: 151 },
  { id: '3531', name: 'Sipchu', user_id: User.first.id, extension_id: 151 },
  { id: '3532', name: 'Taksethang', user_id: User.first.id, extension_id: 151 },
  { id: '3533', name: 'Walithang', user_id: User.first.id, extension_id: 151 },
  { id: '3534', name: 'Waza', user_id: User.first.id, extension_id: 151 },
  { id: '3535', name: 'Zhomthang', user_id: User.first.id, extension_id: 151 },
  { id: '3536', name: 'Zigu', user_id: User.first.id, extension_id: 151 },

  # Darkarla
  { id: '3441', name: 'Bjacho', user_id: User.first.id, extension_id: 152 },
  { id: '3442', name: 'Chamgang', user_id: User.first.id, extension_id: 152 },
  { id: '3443', name: 'Dungdo', user_id: User.first.id, extension_id: 152 },
  { id: '3444', name: 'Gyeltala', user_id: User.first.id, extension_id: 152 },
  { id: '3445', name: 'Wangdo', user_id: User.first.id, extension_id: 152 },

  # Thimphu Thromde
  { id: '3548', name: 'Babesa', user_id: User.first.id, extension_id: 224 },
  { id: '3549', name: 'Bangdu', user_id: User.first.id, extension_id: 224 },
  { id: '3550', name: 'Bapa Samling', user_id: User.first.id, extension_id: 224 },
  { id: '3551', name: 'Barp Gochukha', user_id: User.first.id, extension_id: 224 },
  { id: '3552', name: 'Barp Jyalbkha', user_id: User.first.id, extension_id: 224 },
  { id: '3553', name: 'Barp Lhakhang', user_id: User.first.id, extension_id: 224 },
  { id: '3554', name: 'Changangkha', user_id: User.first.id, extension_id: 224 },
  { id: '3555', name: 'Changzamtok', user_id: User.first.id, extension_id: 224 },
  { id: '3556', name: 'Deling', user_id: User.first.id, extension_id: 224 },
  { id: '3557', name: 'Deling Dangtoe', user_id: User.first.id, extension_id: 224 },
  { id: '3558', name: 'Gidhaphu', user_id: User.first.id, extension_id: 224 },
  { id: '3559', name: 'Hejo', user_id: User.first.id, extension_id: 224 },
  { id: '3560', name: 'Jalung', user_id: User.first.id, extension_id: 224 },
  { id: '3561', name: 'Jalungkha', user_id: User.first.id, extension_id: 224 },
  { id: '3562', name: 'Jibjokha', user_id: User.first.id, extension_id: 224 },
  { id: '3563', name: 'Jiji', user_id: User.first.id, extension_id: 224 },
  { id: '3564', name: 'Jiji Donglo', user_id: User.first.id, extension_id: 224 },
  { id: '3565', name: 'Jungshina', user_id: User.first.id, extension_id: 224 },
  { id: '3566', name: 'Langjophakha', user_id: User.first.id, extension_id: 224 },
  { id: '3567', name: 'Lhundrupling', user_id: User.first.id, extension_id: 224 },
  { id: '3568', name: 'Lutoe', user_id: User.first.id, extension_id: 224 },
  { id: '3569', name: 'Motithang', user_id: User.first.id, extension_id: 224 },
  { id: '3570', name: 'Norbuling Simtokha', user_id: User.first.id, extension_id: 224 },
  { id: '3571', name: 'Olakha', user_id: User.first.id, extension_id: 224 },
  { id: '3572', name: 'Pamtsho', user_id: User.first.id, extension_id: 224 },
  { id: '3573', name: 'Samazingkha', user_id: User.first.id, extension_id: 224 },
  { id: '3574', name: 'Simtokha', user_id: User.first.id, extension_id: 224 },
  { id: '3575', name: 'Taba', user_id: User.first.id, extension_id: 224 },
  { id: '3576', name: 'Thim Throm', user_id: User.first.id, extension_id: 224 },
  { id: '3577', name: 'Tshalimaphel', user_id: User.first.id, extension_id: 224 },
  { id: '3578', name: 'Zilukha', user_id: User.first.id, extension_id: 224 }
].each do |v|
  Village.find_or_create_by!(v)
end
