# frozen_string_literal: true

puts 'Seeding villages of Trashigang...'
[
  # Bartsham
  { id: '3581', name: 'Bargoen', user_id: User.first.id, extension_id: 153 },
  { id: '3582', name: 'Baynangkhar', user_id: User.first.id, extension_id: 153 },
  { id: '3583', name: 'Bumling', user_id: User.first.id, extension_id: 153 },
  { id: '3584', name: 'Chado Lhakhang Wog', user_id: User.first.id, extension_id: 153 },
  { id: '3585', name: 'Dzong Goen', user_id: User.first.id, extension_id: 153 },
  { id: '3586', name: 'Dzong Thong', user_id: User.first.id, extension_id: 153 },
  { id: '3587', name: 'Jamung', user_id: User.first.id, extension_id: 153 },
  { id: '3588', name: 'Keypung', user_id: User.first.id, extension_id: 153 },
  { id: '3589', name: 'Kumung', user_id: User.first.id, extension_id: 153 },
  { id: '3590', name: 'Majadung', user_id: User.first.id, extension_id: 153 },
  { id: '3591', name: 'Menchari', user_id: User.first.id, extension_id: 153 },
  { id: '3592', name: 'Mentshang', user_id: User.first.id, extension_id: 153 },
  { id: '3593', name: 'Mugkhar', user_id: User.first.id, extension_id: 153 },
  { id: '3594', name: 'Naktshang', user_id: User.first.id, extension_id: 153 },
  { id: '3595', name: 'Nangkhar', user_id: User.first.id, extension_id: 153 },
  { id: '3596', name: 'Ngalung', user_id: User.first.id, extension_id: 153 },
  { id: '3597', name: 'Ngalung Gang', user_id: User.first.id, extension_id: 153 },
  { id: '3598', name: 'Pam', user_id: User.first.id, extension_id: 153 },
  { id: '3599', name: 'Pangthang', user_id: User.first.id, extension_id: 153 },
  { id: '3600', name: 'Rephung', user_id: User.first.id, extension_id: 153 },
  { id: '3601', name: 'Resengma', user_id: User.first.id, extension_id: 153 },
  { id: '3602', name: 'Reygang', user_id: User.first.id, extension_id: 153 },
  { id: '3603', name: 'Serhsing', user_id: User.first.id, extension_id: 153 },
  { id: '3604', name: 'Tashi Teng', user_id: User.first.id, extension_id: 153 },
  { id: '3605', name: 'Thangchey', user_id: User.first.id, extension_id: 153 },
  { id: '3606', name: 'Trashang', user_id: User.first.id, extension_id: 153 },
  { id: '3607', name: 'Yangkhar', user_id: User.first.id, extension_id: 153 },
  { id: '3608', name: 'Zhingom', user_id: User.first.id, extension_id: 153 },
  { id: '3609', name: 'Zoor', user_id: User.first.id, extension_id: 153 },
  { id: '3610', name: 'Zoortshong', user_id: User.first.id, extension_id: 153 },

  # Bidoong
  { id: '3612', name: 'Bargoen', user_id: User.first.id, extension_id: 154 },
  { id: '3613', name: 'Dodom', user_id: User.first.id, extension_id: 154 },
  { id: '3614', name: 'Dori', user_id: User.first.id, extension_id: 154 },
  { id: '3615', name: 'Gaygoen', user_id: User.first.id, extension_id: 154 },
  { id: '3616', name: 'Jalung', user_id: User.first.id, extension_id: 154 },
  { id: '3617', name: 'Kakanay Wog', user_id: User.first.id, extension_id: 154 },
  { id: '3618', name: 'Khairi', user_id: User.first.id, extension_id: 154 },
  { id: '3619', name: 'Lemphang', user_id: User.first.id, extension_id: 154 },
  { id: '3620', name: 'Parthong', user_id: User.first.id, extension_id: 154 },
  { id: '3621', name: 'Retsang Pek', user_id: User.first.id, extension_id: 154 },
  { id: '3622', name: 'Saling', user_id: User.first.id, extension_id: 154 },
  { id: '3623', name: 'Takseri', user_id: User.first.id, extension_id: 154 },
  { id: '3624', name: 'Tshekhar', user_id: User.first.id, extension_id: 154 },
  { id: '3625', name: 'Tshigdum', user_id: User.first.id, extension_id: 154 },

  # Kanglung
  { id: '3627', name: 'Menthong', user_id: User.first.id, extension_id: 155 },
  { id: '3628', name: 'Mertsham', user_id: User.first.id, extension_id: 155 },
  { id: '3629', name: 'Pangthang', user_id: User.first.id, extension_id: 155 },
  { id: '3630', name: 'Ritsangdung', user_id: User.first.id, extension_id: 155 },
  { id: '3631', name: 'Rongthung', user_id: User.first.id, extension_id: 155 },
  { id: '3632', name: 'Shingchen Geonpa', user_id: User.first.id, extension_id: 155 },
  { id: '3633', name: 'Thragom', user_id: User.first.id, extension_id: 155 },
  { id: '3634', name: 'Yanphupam', user_id: User.first.id, extension_id: 155 },
  { id: '3635', name: 'Yonphula', user_id: User.first.id, extension_id: 155 },

  # Khaling
  { id: '3660', name: 'Barshong', user_id: User.first.id, extension_id: 157 },
  { id: '3661', name: 'Bayphu', user_id: User.first.id, extension_id: 157 },
  { id: '3662', name: 'Bayphu Sherig', user_id: User.first.id, extension_id: 157 },
  { id: '3663', name: 'Brekha', user_id: User.first.id, extension_id: 157 },
  { id: '3664', name: 'Brekha Dungtshopay', user_id: User.first.id, extension_id: 157 },
  { id: '3665', name: 'Daksa', user_id: User.first.id, extension_id: 157 },
  { id: '3666', name: 'Daktsheng', user_id: User.first.id, extension_id: 157 },
  { id: '3667', name: 'Dangre', user_id: User.first.id, extension_id: 157 },
  { id: '3668', name: 'Dauzor', user_id: User.first.id, extension_id: 157 },
  { id: '3669', name: 'Dregoen', user_id: User.first.id, extension_id: 157 },
  { id: '3670', name: 'Dreywung', user_id: User.first.id, extension_id: 157 },
  { id: '3671', name: 'Dungtshopay', user_id: User.first.id, extension_id: 157 },
  { id: '3672', name: 'Goenpa', user_id: User.first.id, extension_id: 157 },
  { id: '3673', name: 'Gomchu', user_id: User.first.id, extension_id: 157 },
  { id: '3674', name: 'Jeri', user_id: User.first.id, extension_id: 157 },
  { id: '3675', name: 'Jibechu', user_id: User.first.id, extension_id: 157 },
  { id: '3676', name: 'Khochiphaye', user_id: User.first.id, extension_id: 157 },
  { id: '3677', name: 'Khordung', user_id: User.first.id, extension_id: 157 },
  { id: '3678', name: 'Lemang', user_id: User.first.id, extension_id: 157 },
  { id: '3679', name: 'Lemi', user_id: User.first.id, extension_id: 157 },
  { id: '3680', name: 'Lemi Chamzor', user_id: User.first.id, extension_id: 157 },
  { id: '3681', name: 'Leza', user_id: User.first.id, extension_id: 157 },
  { id: '3682', name: 'Merengzor', user_id: User.first.id, extension_id: 157 },
  { id: '3683', name: 'Mongkhorla', user_id: User.first.id, extension_id: 157 },
  { id: '3684', name: 'Rashung', user_id: User.first.id, extension_id: 157 },
  { id: '3685', name: 'Thimkhar', user_id: User.first.id, extension_id: 157 },
  { id: '3686', name: 'Thripang Goenpa', user_id: User.first.id, extension_id: 157 },
  { id: '3687', name: 'Tokaphu', user_id: User.first.id, extension_id: 157 },
  { id: '3688', name: 'Tshangpo', user_id: User.first.id, extension_id: 157 },
  { id: '3689', name: 'Wungachema', user_id: User.first.id, extension_id: 157 },

  # Lumang
  { id: '3691', name: 'Bamshing', user_id: User.first.id, extension_id: 158 },
  { id: '3692', name: 'Bargoepa', user_id: User.first.id, extension_id: 158 },
  { id: '3693', name: 'Beamri', user_id: User.first.id, extension_id: 158 },
  { id: '3694', name: 'Chengri', user_id: User.first.id, extension_id: 158 },
  { id: '3695', name: 'Darnang', user_id: User.first.id, extension_id: 158 },
  { id: '3696', name: 'Darung', user_id: User.first.id, extension_id: 158 },
  { id: '3697', name: 'Darung Wadrangzor', user_id: User.first.id, extension_id: 158 },
  { id: '3698', name: 'Deno', user_id: User.first.id, extension_id: 158 },
  { id: '3699', name: 'Dori', user_id: User.first.id, extension_id: 158 },
  { id: '3700', name: 'Dori Tsano', user_id: User.first.id, extension_id: 158 },
  { id: '3701', name: 'Dungmanma', user_id: User.first.id, extension_id: 158 },
  { id: '3702', name: 'Dupkhang', user_id: User.first.id, extension_id: 158 },
  { id: '3703', name: 'Dupkhang Goenpa', user_id: User.first.id, extension_id: 158 },
  { id: '3704', name: 'Gaphu', user_id: User.first.id, extension_id: 158 },
  { id: '3705', name: 'Goenzor', user_id: User.first.id, extension_id: 158 },
  { id: '3706', name: 'Habla', user_id: User.first.id, extension_id: 158 },
  { id: '3707', name: 'Jabgoen', user_id: User.first.id, extension_id: 158 },
  { id: '3708', name: 'Jabgoenpa', user_id: User.first.id, extension_id: 158 },
  { id: '3709', name: 'Khaphe', user_id: User.first.id, extension_id: 158 },
  { id: '3710', name: 'Khargoen', user_id: User.first.id, extension_id: 158 },
  { id: '3711', name: 'Kharphu', user_id: User.first.id, extension_id: 158 },
  { id: '3712', name: 'Kharphugoenpa', user_id: User.first.id, extension_id: 158 },
  { id: '3713', name: 'Kheri', user_id: User.first.id, extension_id: 158 },
  { id: '3714', name: 'Kheshing', user_id: User.first.id, extension_id: 158 },
  { id: '3715', name: 'Kheshing Reserbu', user_id: User.first.id, extension_id: 158 },
  { id: '3716', name: 'Kheshing Roamzor', user_id: User.first.id, extension_id: 158 },
  { id: '3717', name: 'Kheshingserbu', user_id: User.first.id, extension_id: 158 },
  { id: '3718', name: 'Khinying Manma', user_id: User.first.id, extension_id: 158 },
  { id: '3719', name: 'Khomin', user_id: User.first.id, extension_id: 158 },
  { id: '3720', name: 'Kurchilo', user_id: User.first.id, extension_id: 158 },
  { id: '3721', name: 'Lumang', user_id: User.first.id, extension_id: 158 },
  { id: '3722', name: 'Lumang Goenzor', user_id: User.first.id, extension_id: 158 },
  { id: '3723', name: 'Lumang Gomtshang', user_id: User.first.id, extension_id: 158 },
  { id: '3724', name: 'Lumang Shachari', user_id: User.first.id, extension_id: 158 },
  { id: '3725', name: 'Muchu', user_id: User.first.id, extension_id: 158 },
  { id: '3726', name: 'Omshari', user_id: User.first.id, extension_id: 158 },
  { id: '3727', name: 'Ragea', user_id: User.first.id, extension_id: 158 },
  { id: '3728', name: 'Reserbu', user_id: User.first.id, extension_id: 158 },
  { id: '3729', name: 'Rizang', user_id: User.first.id, extension_id: 158 },
  { id: '3730', name: 'Rushingye', user_id: User.first.id, extension_id: 158 },
  { id: '3731', name: 'Sangmari', user_id: User.first.id, extension_id: 158 },
  { id: '3732', name: 'Sayuel', user_id: User.first.id, extension_id: 158 },
  { id: '3733', name: 'Sethang', user_id: User.first.id, extension_id: 158 },
  { id: '3734', name: 'Shachari', user_id: User.first.id, extension_id: 158 },
  { id: '3735', name: 'Tashichoeding', user_id: User.first.id, extension_id: 158 },
  { id: '3736', name: 'Thrimla', user_id: User.first.id, extension_id: 158 },
  { id: '3737', name: 'Thrumnang', user_id: User.first.id, extension_id: 158 },
  { id: '3738', name: 'Thrumnang Lishingzor', user_id: User.first.id, extension_id: 158 },
  { id: '3739', name: 'Tsano', user_id: User.first.id, extension_id: 158 },
  { id: '3740', name: 'Tshangpo', user_id: User.first.id, extension_id: 158 },
  { id: '3741', name: 'Wadrangzor', user_id: User.first.id, extension_id: 158 },
  { id: '3742', name: 'Wamrong', user_id: User.first.id, extension_id: 158 },
  { id: '3743', name: 'Wungang', user_id: User.first.id, extension_id: 158 },
  { id: '3744', name: 'Mukazor', user_id: User.first.id, extension_id: 158 }
].each do |v|
  Village.find_or_create_by!(v)
end
