# frozen_string_literal: true

puts 'Seeding villages of Tashi Yangtse...'

[
  # Boomdeling
  { id: '3885', name: 'Bamdir', user_id: User.first.id, extension_id: 169 },
  { id: '3886', name: 'Baytsamang', user_id: User.first.id, extension_id: 169 },
  { id: '3887', name: 'Gangkhardung', user_id: User.first.id, extension_id: 169 },
  { id: '3888', name: 'Ngalemang', user_id: User.first.id, extension_id: 169 },
  { id: '3889', name: 'Panglewog', user_id: User.first.id, extension_id: 169 },
  { id: '3890', name: 'Phenteng', user_id: User.first.id, extension_id: 169 },
  { id: '3891', name: 'Tarphel', user_id: User.first.id, extension_id: 169 },
  { id: '3892', name: 'Tshaleng', user_id: User.first.id, extension_id: 169 },
  { id: '3893', name: 'Wogmanamg', user_id: User.first.id, extension_id: 169 },
  { id: '3894', name: 'Wogmanang', user_id: User.first.id, extension_id: 169 },
  { id: '3895', name: 'Pangkhar', user_id: User.first.id, extension_id: 169 },

  # Jamkhar
  { id: '3897', name: 'Chayma', user_id: User.first.id, extension_id: 170 },
  { id: '3898', name: 'Domshing', user_id: User.first.id, extension_id: 170 },
  { id: '3899', name: 'Larjab', user_id: User.first.id, extension_id: 170 },
  { id: '3900', name: 'Neda', user_id: User.first.id, extension_id: 170 },
  { id: '3901', name: 'Pachu', user_id: User.first.id, extension_id: 170 },
  { id: '3902', name: 'Rejung', user_id: User.first.id, extension_id: 170 },
  { id: '3903', name: 'Shingkhar', user_id: User.first.id, extension_id: 170 },
  { id: '3904', name: 'Tak Chayma', user_id: User.first.id, extension_id: 170 },
  { id: '3905', name: 'Tongla', user_id: User.first.id, extension_id: 170 },
  { id: '3906', name: 'Yub', user_id: User.first.id, extension_id: 170 },
  { id: '3907', name: 'Zor', user_id: User.first.id, extension_id: 170 },

  # Khamdang
  { id: '3909', name: 'Daka', user_id: User.first.id, extension_id: 171 },
  { id: '3910', name: 'Denglum', user_id: User.first.id, extension_id: 171 },
  { id: '3911', name: 'Dolepchen', user_id: User.first.id, extension_id: 171 },
  { id: '3912', name: 'Domchang', user_id: User.first.id, extension_id: 171 },
  { id: '3913', name: 'Gardung', user_id: User.first.id, extension_id: 171 },
  { id: '3914', name: 'Karmazom', user_id: User.first.id, extension_id: 171 },
  { id: '3915', name: 'Kencholing', user_id: User.first.id, extension_id: 171 },
  { id: '3916', name: 'Khamdang', user_id: User.first.id, extension_id: 171 },
  { id: '3917', name: 'Kilkhorchen', user_id: User.first.id, extension_id: 171 },
  { id: '3918', name: 'Longkhar', user_id: User.first.id, extension_id: 171 },
  { id: '3919', name: 'Ngalamo', user_id: User.first.id, extension_id: 171 },
  { id: '3920', name: 'Nomaring', user_id: User.first.id, extension_id: 171 },
  { id: '3921', name: 'Pam', user_id: User.first.id, extension_id: 171 },
  { id: '3922', name: 'Paychateng', user_id: User.first.id, extension_id: 171 },
  { id: '3923', name: 'Rabdeling', user_id: User.first.id, extension_id: 171 },
  { id: '3924', name: 'Serpang', user_id: User.first.id, extension_id: 171 },
  { id: '3925', name: 'Shakshong', user_id: User.first.id, extension_id: 171 },
  { id: '3926', name: 'Shale', user_id: User.first.id, extension_id: 171 },
  { id: '3927', name: 'Shazam', user_id: User.first.id, extension_id: 171 },
  { id: '3928', name: 'Zharchi', user_id: User.first.id, extension_id: 171 },

  # Ramjar
  { id: '3930', name: 'Aringborang', user_id: User.first.id, extension_id: 172 },
  { id: '3931', name: 'Bainangreb', user_id: User.first.id, extension_id: 172 },
  { id: '3932', name: 'Bardzong', user_id: User.first.id, extension_id: 172 },
  { id: '3933', name: 'Bawong', user_id: User.first.id, extension_id: 172 },
  { id: '3934', name: 'Domtsang', user_id: User.first.id, extension_id: 172 },
  { id: '3935', name: 'Dungmen', user_id: User.first.id, extension_id: 172 },
  { id: '3936', name: 'Gocha', user_id: User.first.id, extension_id: 172 },
  { id: '3937', name: 'Goenpa', user_id: User.first.id, extension_id: 172 },
  { id: '3938', name: 'Gongshing', user_id: User.first.id, extension_id: 172 },
  { id: '3939', name: 'Kakaney', user_id: User.first.id, extension_id: 172 },
  { id: '3940', name: 'Khala Pangthang', user_id: User.first.id, extension_id: 172 },
  { id: '3941', name: 'Kheri', user_id: User.first.id, extension_id: 172 },
  { id: '3942', name: 'Lalam', user_id: User.first.id, extension_id: 172 },
  { id: '3943', name: 'Laybari', user_id: User.first.id, extension_id: 172 },
  { id: '3944', name: 'Lemnang', user_id: User.first.id, extension_id: 172 },
  { id: '3945', name: 'Lengbartang', user_id: User.first.id, extension_id: 172 },
  { id: '3946', name: 'Lushing', user_id: User.first.id, extension_id: 172 },
  { id: '3947', name: 'Menshing', user_id: User.first.id, extension_id: 172 },
  { id: '3948', name: 'Naktshang', user_id: User.first.id, extension_id: 172 },
  { id: '3949', name: 'Pangthang', user_id: User.first.id, extension_id: 172 },
  { id: '3950', name: 'Phairawa', user_id: User.first.id, extension_id: 172 },
  { id: '3951', name: 'Romang', user_id: User.first.id, extension_id: 172 },
  { id: '3952', name: 'Shangthang', user_id: User.first.id, extension_id: 172 },
  { id: '3953', name: 'Tadzong', user_id: User.first.id, extension_id: 172 },
  { id: '3954', name: 'Thongzor', user_id: User.first.id, extension_id: 172 },
  { id: '3955', name: 'Tsangrong', user_id: User.first.id, extension_id: 172 },
  { id: '3956', name: 'Tsenkang', user_id: User.first.id, extension_id: 172 },
  { id: '3957', name: 'Tshotsang', user_id: User.first.id, extension_id: 172 },
  { id: '3958', name: 'Tshurkhar', user_id: User.first.id, extension_id: 172 },
  { id: '3959', name: 'Tsushing', user_id: User.first.id, extension_id: 172 },
  { id: '3960', name: 'Wongkhar', user_id: User.first.id, extension_id: 172 },
  { id: '3961', name: 'Zor', user_id: User.first.id, extension_id: 172 },
  { id: '3962', name: 'Zorthung', user_id: User.first.id, extension_id: 172 },

  # Toedtsho
  { id: '3964', name: 'Bakpa', user_id: User.first.id, extension_id: 173 },
  { id: '3965', name: 'Bangkhabchen', user_id: User.first.id, extension_id: 173 },
  { id: '3966', name: 'Chaymkhar', user_id: User.first.id, extension_id: 173 },
  { id: '3967', name: 'Choklabtsa', user_id: User.first.id, extension_id: 173 },
  { id: '3968', name: 'Daktsa', user_id: User.first.id, extension_id: 173 },
  { id: '3969', name: 'Dumang', user_id: User.first.id, extension_id: 173 },
  { id: '3970', name: 'Dungtse', user_id: User.first.id, extension_id: 173 },
  { id: '3971', name: 'Jangphutse', user_id: User.first.id, extension_id: 173 },
  { id: '3972', name: 'Khenel', user_id: User.first.id, extension_id: 173 },
  { id: '3973', name: 'Khoblakhar', user_id: User.first.id, extension_id: 173 },
  { id: '3974', name: 'Manam', user_id: User.first.id, extension_id: 173 },
  { id: '3975', name: 'Meldung', user_id: User.first.id, extension_id: 173 },
  { id: '3976', name: 'Nangkhar Goenpa', user_id: User.first.id, extension_id: 173 },
  { id: '3977', name: 'Omba', user_id: User.first.id, extension_id: 173 },
  { id: '3978', name: 'Pajab', user_id: User.first.id, extension_id: 173 },
  { id: '3979', name: 'Pangthang Goenpa', user_id: User.first.id, extension_id: 173 },
  { id: '3980', name: 'Pungthung', user_id: User.first.id, extension_id: 173 },
  { id: '3981', name: 'Seb', user_id: User.first.id, extension_id: 173 },
  { id: '3982', name: 'Sengphu', user_id: User.first.id, extension_id: 173 },
  { id: '3983', name: 'Sertsho', user_id: User.first.id, extension_id: 173 },
  { id: '3984', name: 'Thangdang', user_id: User.first.id, extension_id: 173 },
  { id: '3985', name: 'Tokshing', user_id: User.first.id, extension_id: 173 },
  { id: '3986', name: 'Tshengang', user_id: User.first.id, extension_id: 173 },

  # Tongmijangsa
  { id: '3988', name: 'Bainangkhar', user_id: User.first.id, extension_id: 174 },
  { id: '3989', name: 'Bakpa', user_id: User.first.id, extension_id: 174 },
  { id: '3990', name: 'Changmadung', user_id: User.first.id, extension_id: 174 },
  { id: '3991', name: 'Dongkashing', user_id: User.first.id, extension_id: 174 },
  { id: '3992', name: 'Dongshing', user_id: User.first.id, extension_id: 174 },
  { id: '3993', name: 'Dongtoe', user_id: User.first.id, extension_id: 174 },
  { id: '3994', name: 'Gomkor', user_id: User.first.id, extension_id: 174 },
  { id: '3995', name: 'Gorzhing', user_id: User.first.id, extension_id: 174 },
  { id: '3996', name: 'Kenmong', user_id: User.first.id, extension_id: 174 },
  { id: '3997', name: 'Kinzangling', user_id: User.first.id, extension_id: 174 },
  { id: '3998', name: 'Lhawshing', user_id: User.first.id, extension_id: 174 },
  { id: '3999', name: 'Maymung', user_id: User.first.id, extension_id: 174 },
  { id: '4000', name: 'Menchu', user_id: User.first.id, extension_id: 174 },
  { id: '4001', name: 'Pang', user_id: User.first.id, extension_id: 174 },
  { id: '4002', name: 'Toka', user_id: User.first.id, extension_id: 174 },
  { id: '4003', name: 'Tsangdung', user_id: User.first.id, extension_id: 174 },
  { id: '4004', name: 'Wogkhar', user_id: User.first.id, extension_id: 174 },

  # Yangtse
  { id: '4018', name: 'Baney', user_id: User.first.id, extension_id: 175 },
  { id: '4019', name: 'Bayling', user_id: User.first.id, extension_id: 175 },
  { id: '4020', name: 'Bimkhar', user_id: User.first.id, extension_id: 175 },
  { id: '4021', name: 'Choekor', user_id: User.first.id, extension_id: 175 },
  { id: '4022', name: 'Gangkhar', user_id: User.first.id, extension_id: 175 },
  { id: '4023', name: 'Lechen', user_id: User.first.id, extension_id: 175 },
  { id: '4024', name: 'Rabti', user_id: User.first.id, extension_id: 175 },

  # Yalang
  { id: '4006', name: 'Bamchang', user_id: User.first.id, extension_id: 176 },
  { id: '4007', name: 'Chayma', user_id: User.first.id, extension_id: 176 },
  { id: '4008', name: 'Dukti', user_id: User.first.id, extension_id: 176 },
  { id: '4009', name: 'Melongkhar', user_id: User.first.id, extension_id: 176 },
  { id: '4010', name: 'Namthi', user_id: User.first.id, extension_id: 176 },
  { id: '4011', name: 'Phungyang', user_id: User.first.id, extension_id: 176 },
  { id: '4012', name: 'Rinzin Tenpang', user_id: User.first.id, extension_id: 176 },
  { id: '4013', name: 'Rolam', user_id: User.first.id, extension_id: 176 },
  { id: '4014', name: 'Thragom', user_id: User.first.id, extension_id: 176 },
  { id: '4015', name: 'Yalang', user_id: User.first.id, extension_id: 176 },
  { id: '4016', name: 'Yerphel', user_id: User.first.id, extension_id: 176 },

  # Trashi Yangtse Thromde
  { id: '4017', name: 'Trashi Yangtse Thromde', user_id: User.first.id, extension_id: 177 }
].each do |v|
  Village.find_or_create_by!(v)
end
