# frozen_string_literal: true

[
  # Kangpar
  { id: '3637', name: 'Bedingphu', user_id: User.first.id, extension_id: 156 },
  { id: '3638', name: 'Chorphu', user_id: User.first.id, extension_id: 156 },
  { id: '3639', name: 'Dangna', user_id: User.first.id, extension_id: 156 },
  { id: '3640', name: 'Doyam Chema', user_id: User.first.id, extension_id: 156 },
  { id: '3641', name: 'Gangpar', user_id: User.first.id, extension_id: 156 },
  { id: '3642', name: 'Jumshari', user_id: User.first.id, extension_id: 156 },
  { id: '3643', name: 'Kheri', user_id: User.first.id, extension_id: 156 },
  { id: '3644', name: 'Kheshing', user_id: User.first.id, extension_id: 156 },
  { id: '3645', name: 'Laden', user_id: User.first.id, extension_id: 156 },
  { id: '3646', name: 'Lagoen', user_id: User.first.id, extension_id: 156 },
  { id: '3647', name: 'Lamyong', user_id: User.first.id, extension_id: 156 },
  { id: '3648', name: 'Langnang', user_id: User.first.id, extension_id: 156 },
  { id: '3649', name: 'Madeywa', user_id: User.first.id, extension_id: 156 },
  { id: '3650', name: 'Merda', user_id: User.first.id, extension_id: 156 },
  { id: '3651', name: 'Neyling', user_id: User.first.id, extension_id: 156 },
  { id: '3652', name: 'Passangphu', user_id: User.first.id, extension_id: 156 },
  { id: '3653', name: 'Pedung', user_id: User.first.id, extension_id: 156 },
  { id: '3654', name: 'Ribalingmi', user_id: User.first.id, extension_id: 156 },
  { id: '3655', name: 'Sarong', user_id: User.first.id, extension_id: 156 },
  { id: '3656', name: 'Threlphu', user_id: User.first.id, extension_id: 156 },
  { id: '3657', name: 'Yungney', user_id: User.first.id, extension_id: 156 },
  { id: '3658', name: 'Zerdung', user_id: User.first.id, extension_id: 156 },

  # Merag
  { id: '3746', name: 'Chelephu', user_id: User.first.id, extension_id: 159 },
  { id: '3747', name: 'Gyengo', user_id: User.first.id, extension_id: 159 },
  { id: '3748', name: 'Khashateng', user_id: User.first.id, extension_id: 159 },
  { id: '3749', name: 'Khelephu', user_id: User.first.id, extension_id: 159 },
  { id: '3750', name: 'Merak', user_id: User.first.id, extension_id: 159 },

  # Phongmed
  { id: '3752', name: 'Banyalting', user_id: User.first.id, extension_id: 160 },
  { id: '3753', name: 'Bargoenpa', user_id: User.first.id, extension_id: 160 },
  { id: '3754', name: 'Bumtang', user_id: User.first.id, extension_id: 160 },
  { id: '3755', name: 'Demkhar', user_id: User.first.id, extension_id: 160 },
  { id: '3756', name: 'Dorshing', user_id: User.first.id, extension_id: 160 },
  { id: '3757', name: 'Gadzari', user_id: User.first.id, extension_id: 160 },
  { id: '3758', name: 'Janyema', user_id: User.first.id, extension_id: 160 },
  { id: '3759', name: 'Karma Geonpa', user_id: User.first.id, extension_id: 160 },
  { id: '3760', name: 'Kharpa', user_id: User.first.id, extension_id: 160 },
  { id: '3761', name: 'Langchim', user_id: User.first.id, extension_id: 160 },
  { id: '3762', name: 'Lem', user_id: User.first.id, extension_id: 160 },
  { id: '3763', name: 'Lhakhang', user_id: User.first.id, extension_id: 160 },
  { id: '3764', name: 'Momnangkhar', user_id: User.first.id, extension_id: 160 },
  { id: '3765', name: 'Pengtse', user_id: User.first.id, extension_id: 160 },
  { id: '3766', name: 'Phimsong', user_id: User.first.id, extension_id: 160 },
  { id: '3767', name: 'Shingchalu', user_id: User.first.id, extension_id: 160 },
  { id: '3768', name: 'Shingringmo', user_id: User.first.id, extension_id: 160 },
  { id: '3769', name: 'Shongkang', user_id: User.first.id, extension_id: 160 },
  { id: '3770', name: 'Soelkhar', user_id: User.first.id, extension_id: 160 },
  { id: '3771', name: 'Tathrang', user_id: User.first.id, extension_id: 160 },
  { id: '3772', name: 'Thongwrong', user_id: User.first.id, extension_id: 160 },
  { id: '3773', name: 'Thrang', user_id: User.first.id, extension_id: 160 },
  { id: '3774', name: 'Yabrang', user_id: User.first.id, extension_id: 160 },
  { id: '3775', name: 'Yerchilu', user_id: User.first.id, extension_id: 160 },

  # Radhi
  { id: '3777', name: 'Bongman', user_id: User.first.id, extension_id: 161 },
  { id: '3778', name: 'Chamang', user_id: User.first.id, extension_id: 161 },
  { id: '3779', name: 'Chema', user_id: User.first.id, extension_id: 161 },
  { id: '3780', name: 'Dekiling', user_id: User.first.id, extension_id: 161 },
  { id: '3781', name: 'Deling', user_id: User.first.id, extension_id: 161 },
  { id: '3782', name: 'Dung Goen', user_id: User.first.id, extension_id: 161 },
  { id: '3783', name: 'Dungsam', user_id: User.first.id, extension_id: 161 },
  { id: '3784', name: 'Dungsing/Tshatshey', user_id: User.first.id, extension_id: 161 },
  { id: '3785', name: 'Joenla', user_id: User.first.id, extension_id: 161 },
  { id: '3786', name: 'Joenla Tshetshe', user_id: User.first.id, extension_id: 161 },
  { id: '3787', name: 'Joenlapam', user_id: User.first.id, extension_id: 161 },
  { id: '3788', name: 'Kadam', user_id: User.first.id, extension_id: 161 },
  { id: '3789', name: 'Khudumpang', user_id: User.first.id, extension_id: 161 },
  { id: '3790', name: 'Langteng', user_id: User.first.id, extension_id: 161 },
  { id: '3791', name: 'Melongkhar', user_id: User.first.id, extension_id: 161 },
  { id: '3792', name: 'Pakaling', user_id: User.first.id, extension_id: 161 },
  { id: '3793', name: 'Pangthang', user_id: User.first.id, extension_id: 161 },
  { id: '3794', name: 'Radhi Pangthang', user_id: User.first.id, extension_id: 161 },
  { id: '3795', name: 'Ranjung Yodselchholing', user_id: User.first.id, extension_id: 161 },
  { id: '3796', name: 'Tangthrang', user_id: User.first.id, extension_id: 161 },
  { id: '3797', name: 'Tongling Kadam', user_id: User.first.id, extension_id: 161 },
  { id: '3798', name: 'Tongling Khatoe', user_id: User.first.id, extension_id: 161 },
  { id: '3799', name: 'Tongling Pam', user_id: User.first.id, extension_id: 161 },
  { id: '3800', name: 'Tongling Pangthang', user_id: User.first.id, extension_id: 161 },
  { id: '3801', name: 'Tongling Tangthrang', user_id: User.first.id, extension_id: 161 },
  { id: '3802', name: 'Tongling Thrang', user_id: User.first.id, extension_id: 161 },
  { id: '3803', name: 'Tsangkhar', user_id: User.first.id, extension_id: 161 },
  { id: '3804', name: 'Naktshang', user_id: User.first.id, extension_id: 161 },
  { id: '3805', name: 'Phajogeonpa', user_id: User.first.id, extension_id: 161 },
  { id: '3806', name: 'Tokshingmang', user_id: User.first.id, extension_id: 161 },

  # Sagteng
  { id: '3808', name: 'Borangmang', user_id: User.first.id, extension_id: 162 },
  { id: '3809', name: 'Borangtse', user_id: User.first.id, extension_id: 162 },
  { id: '3810', name: 'Bumlog', user_id: User.first.id, extension_id: 162 },
  { id: '3811', name: 'Melam Thung', user_id: User.first.id, extension_id: 162 },
  { id: '3812', name: 'Murbee', user_id: User.first.id, extension_id: 162 },
  { id: '3813', name: 'Sakteng', user_id: User.first.id, extension_id: 162 },
  { id: '3814', name: 'Sakteng Jyenkhar', user_id: User.first.id, extension_id: 162 },
  { id: '3815', name: 'Sakteng Manirong', user_id: User.first.id, extension_id: 162 },
  { id: '3816', name: 'Sakteng Pusa', user_id: User.first.id, extension_id: 162 },
  { id: '3817', name: 'Sakteng Tengmang', user_id: User.first.id, extension_id: 162 },
  { id: '3818', name: 'Sakteng Thrak Thri', user_id: User.first.id, extension_id: 162 },
  { id: '3819', name: 'Tholong', user_id: User.first.id, extension_id: 162 },
  { id: '3820', name: 'Youngbazor', user_id: User.first.id, extension_id: 162 },

  # Samkhar
  { id: '3822', name: 'Bikhar', user_id: User.first.id, extension_id: 163 },
  { id: '3823', name: 'Khabti', user_id: User.first.id, extension_id: 163 },
  { id: '3824', name: 'Malphel', user_id: User.first.id, extension_id: 163 },
  { id: '3825', name: 'Pam', user_id: User.first.id, extension_id: 163 },
  { id: '3826', name: 'Rangshikhar', user_id: User.first.id, extension_id: 163 },
  { id: '3827', name: 'Samkhar', user_id: User.first.id, extension_id: 163 },
  { id: '3828', name: 'Trashigang Throm', user_id: User.first.id, extension_id: 163 },

  # Shongphu
  { id: '3830', name: 'Chaling', user_id: User.first.id, extension_id: 164 },
  { id: '3831', name: 'Changme', user_id: User.first.id, extension_id: 164 },
  { id: '3832', name: 'Ghaling', user_id: User.first.id, extension_id: 164 },
  { id: '3833', name: 'Gongtshe Phangma', user_id: User.first.id, extension_id: 164 },
  { id: '3834', name: 'Rangjung', user_id: User.first.id, extension_id: 164 },
  { id: '3835', name: 'Shongphu', user_id: User.first.id, extension_id: 164 },
  { id: '3836', name: 'Yobenang', user_id: User.first.id, extension_id: 164 },

  # Thrimshing
  { id: '3838', name: 'Bayphu', user_id: User.first.id, extension_id: 165 },
  { id: '3839', name: 'Berdungma', user_id: User.first.id, extension_id: 165 },
  { id: '3840', name: 'Bongzor', user_id: User.first.id, extension_id: 165 },
  { id: '3841', name: 'Lam Pangthang', user_id: User.first.id, extension_id: 165 },
  { id: '3842', name: 'Lhakhang Jab', user_id: User.first.id, extension_id: 165 },
  { id: '3843', name: 'Phakpari', user_id: User.first.id, extension_id: 165 },
  { id: '3844', name: 'Phungsing', user_id: User.first.id, extension_id: 165 },
  { id: '3845', name: 'Ramchong Ma', user_id: User.first.id, extension_id: 165 },
  { id: '3846', name: 'Ramchongma', user_id: User.first.id, extension_id: 165 },
  { id: '3847', name: 'Sako', user_id: User.first.id, extension_id: 165 },
  { id: '3848', name: 'Thrimshing', user_id: User.first.id, extension_id: 165 },
  { id: '3849', name: 'Thungkhar', user_id: User.first.id, extension_id: 165 },
  { id: '3850', name: 'Tsangpo', user_id: User.first.id, extension_id: 165 },
  { id: '3851', name: 'Yemkhar', user_id: User.first.id, extension_id: 165 },
  { id: '3852', name: 'Yongdhir', user_id: User.first.id, extension_id: 165 },

  # Udzorong
  { id: '3854', name: 'Barkazor', user_id: User.first.id, extension_id: 166 },
  { id: '3855', name: 'Baypum', user_id: User.first.id, extension_id: 166 },
  { id: '3856', name: 'Benshingmo', user_id: User.first.id, extension_id: 166 },
  { id: '3857', name: 'Cheaya', user_id: User.first.id, extension_id: 166 },
  { id: '3858', name: 'Dangrong', user_id: User.first.id, extension_id: 166 },
  { id: '3859', name: 'Dayphu', user_id: User.first.id, extension_id: 166 },
  { id: '3860', name: 'Deng Tshalo', user_id: User.first.id, extension_id: 166 },
  { id: '3861', name: 'Geangkhar', user_id: User.first.id, extension_id: 166 },
  { id: '3862', name: 'Gongtsheri', user_id: User.first.id, extension_id: 166 },
  { id: '3863', name: 'Jomtshang', user_id: User.first.id, extension_id: 166 },
  { id: '3864', name: 'Lenche', user_id: User.first.id, extension_id: 166 },
  { id: '3865', name: 'Menkhar', user_id: User.first.id, extension_id: 166 },
  { id: '3866', name: 'Mongka', user_id: User.first.id, extension_id: 166 },
  { id: '3867', name: 'Mongyea', user_id: User.first.id, extension_id: 166 },
  { id: '3868', name: 'Rizor', user_id: User.first.id, extension_id: 166 },
  { id: '3869', name: 'Tshedung', user_id: User.first.id, extension_id: 166 },
  { id: '3870', name: 'Yaerchelo', user_id: User.first.id, extension_id: 166 },

  # Yangnyer
  { id: '3872', name: 'Changzoe', user_id: User.first.id, extension_id: 167 },
  { id: '3873', name: 'Daliphang', user_id: User.first.id, extension_id: 167 },
  { id: '3874', name: 'Dambinang', user_id: User.first.id, extension_id: 167 },
  { id: '3875', name: 'Darjayling', user_id: User.first.id, extension_id: 167 },
  { id: '3876', name: 'Demkhar', user_id: User.first.id, extension_id: 167 },
  { id: '3877', name: 'Durung', user_id: User.first.id, extension_id: 167 },
  { id: '3878', name: 'Khardza', user_id: User.first.id, extension_id: 167 },
  { id: '3879', name: 'Kharthung', user_id: User.first.id, extension_id: 167 },
  { id: '3880', name: 'Kheri', user_id: User.first.id, extension_id: 167 },
  { id: '3881', name: 'Leyphu', user_id: User.first.id, extension_id: 167 },
  { id: '3882', name: 'Shokang', user_id: User.first.id, extension_id: 167 },

  # Trashigang Thromde
  { id: '3883', name: 'Shokang', user_id: User.first.id, extension_id: 168 }
].each do |v|
  Village.find_or_create_by!(v)
end
