# frozen_string_literal: true

puts 'Seeding villages of Trongsa...'

[
  # Draagteng
  { id: '4027', name: 'Changray', user_id: User.first.id, extension_id: 178 },
  { id: '4028', name: 'Drakten', user_id: User.first.id, extension_id: 178 },
  { id: '4029', name: 'Kinga Rabten', user_id: User.first.id, extension_id: 178 },
  { id: '4030', name: 'Kinga Rabten Goenpa', user_id: User.first.id, extension_id: 178 },
  { id: '4031', name: 'Phelchung', user_id: User.first.id, extension_id: 178 },
  { id: '4032', name: 'Reyphel', user_id: User.first.id, extension_id: 178 },
  { id: '4033', name: 'Samcholing', user_id: User.first.id, extension_id: 178 },
  { id: '4034', name: 'Samling Chala', user_id: User.first.id, extension_id: 178 },
  { id: '4035', name: 'Samling Churak', user_id: User.first.id, extension_id: 178 },
  { id: '4036', name: 'Samling Churatak', user_id: User.first.id, extension_id: 178 },
  { id: '4037', name: 'Samling Dangrey', user_id: User.first.id, extension_id: 178 },
  { id: '4038', name: 'Samling Dara', user_id: User.first.id, extension_id: 178 },
  { id: '4039', name: 'Samling Gormola', user_id: User.first.id, extension_id: 178 },
  { id: '4040', name: 'Samling Khamey', user_id: User.first.id, extension_id: 178 },
  { id: '4041', name: 'Samling Kikhornang', user_id: User.first.id, extension_id: 178 },
  { id: '4042', name: 'Samling Kingacholing', user_id: User.first.id, extension_id: 178 },
  { id: '4043', name: 'Samling Kormey', user_id: User.first.id, extension_id: 178 },
  { id: '4044', name: 'Samling Kurbi', user_id: User.first.id, extension_id: 178 },
  { id: '4045', name: 'Samling Lhakhangjab', user_id: User.first.id, extension_id: 178 },
  { id: '4046', name: 'Samling Lhakhangtak', user_id: User.first.id, extension_id: 178 },
  { id: '4047', name: 'Samling Lhakhangwog', user_id: User.first.id, extension_id: 178 },
  { id: '4048', name: 'Samling Majaling', user_id: User.first.id, extension_id: 178 },
  { id: '4049', name: 'Samling Maling', user_id: User.first.id, extension_id: 178 },
  { id: '4050', name: 'Samling Malingbung', user_id: User.first.id, extension_id: 178 },
  { id: '4051', name: 'Samling Malingjug', user_id: User.first.id, extension_id: 178 },
  { id: '4052', name: 'Samling Marzhing', user_id: User.first.id, extension_id: 178 },
  { id: '4053', name: 'Samling Pesinang', user_id: User.first.id, extension_id: 178 },
  { id: '4054', name: 'Samling Phokchen', user_id: User.first.id, extension_id: 178 },
  { id: '4055', name: 'Samling Pingkhar', user_id: User.first.id, extension_id: 178 },
  { id: '4056', name: 'Samling Pisinang', user_id: User.first.id, extension_id: 178 },
  { id: '4057', name: 'Samling Pongpa', user_id: User.first.id, extension_id: 178 },
  { id: '4058', name: 'Samling Shangthong', user_id: User.first.id, extension_id: 178 },
  { id: '4059', name: 'Samling Shangthongjab', user_id: User.first.id, extension_id: 178 },
  { id: '4060', name: 'Samling Shingkhar', user_id: User.first.id, extension_id: 178 },
  { id: '4061', name: 'Samling Ta-Dzong', user_id: User.first.id, extension_id: 178 },
  { id: '4062', name: 'Samling Tangchen', user_id: User.first.id, extension_id: 178 },
  { id: '4063', name: 'Samling Theling', user_id: User.first.id, extension_id: 178 },
  { id: '4064', name: 'Samling Tsekunang', user_id: User.first.id, extension_id: 178 },
  { id: '4065', name: 'Samling Tshajab', user_id: User.first.id, extension_id: 178 },
  { id: '4066', name: 'Samling Tshokunang', user_id: User.first.id, extension_id: 178 },
  { id: '4067', name: 'Samling Wangthang', user_id: User.first.id, extension_id: 178 },
  { id: '4068', name: 'Samling Yumchen', user_id: User.first.id, extension_id: 178 },
  { id: '4069', name: 'Samling Zarchen', user_id: User.first.id, extension_id: 178 },
  { id: '4070', name: 'Samling Zhewthang', user_id: User.first.id, extension_id: 178 },
  { id: '4071', name: 'Taktse', user_id: User.first.id, extension_id: 178 },
  { id: '4072', name: 'Tashidingkha', user_id: User.first.id, extension_id: 178 },
  { id: '4073', name: 'Yulsar', user_id: User.first.id, extension_id: 178 },

  # Korphu
  { id: '4075', name: 'Korphu', user_id: User.first.id, extension_id: 179 },
  { id: '4076', name: 'Nabee', user_id: User.first.id, extension_id: 179 },
  { id: '4077', name: 'Nimshong', user_id: User.first.id, extension_id: 179 },
  { id: '4078', name: 'Reti', user_id: User.first.id, extension_id: 179 },
  { id: '4079', name: 'Retizhongpagang', user_id: User.first.id, extension_id: 179 },

  # Langthil
  { id: '4081', name: 'Baling', user_id: User.first.id, extension_id: 180 },
  { id: '4082', name: 'Bayzam', user_id: User.first.id, extension_id: 180 },
  { id: '4083', name: 'Dangdung', user_id: User.first.id, extension_id: 180 },
  { id: '4084', name: 'Jangbee', user_id: User.first.id, extension_id: 180 },
  { id: '4085', name: 'Koshala', user_id: User.first.id, extension_id: 180 },
  { id: '4086', name: 'Langthil', user_id: User.first.id, extension_id: 180 },
  { id: '4087', name: 'Ngadak', user_id: User.first.id, extension_id: 180 },
  { id: '4088', name: 'Ngormey', user_id: User.first.id, extension_id: 180 },
  { id: '4089', name: 'Pangzor', user_id: User.first.id, extension_id: 180 },
  { id: '4090', name: 'Phuzor/Phumzor', user_id: User.first.id, extension_id: 180 },
  { id: '4091', name: 'Wangling', user_id: User.first.id, extension_id: 180 },
  { id: '4092', name: 'Yuling', user_id: User.first.id, extension_id: 180 },
  { id: '4093', name: 'Beling', user_id: User.first.id, extension_id: 180 },
  { id: '4094', name: 'Kudrak', user_id: User.first.id, extension_id: 180 },
  { id: '4095', name: 'Taktsela', user_id: User.first.id, extension_id: 180 },
  { id: '4096', name: 'Yurmo', user_id: User.first.id, extension_id: 180 },
  { id: '4097', name: 'Lingtoe', user_id: User.first.id, extension_id: 180 },
  { id: '4098', name: 'Lekpagang', user_id: User.first.id, extension_id: 180 },
  { id: '4099', name: 'Sheling', user_id: User.first.id, extension_id: 180 },

  # Nubi
  { id: '4101', name: 'Bemjee', user_id: User.first.id, extension_id: 181 },
  { id: '4102', name: 'Choethrom', user_id: User.first.id, extension_id: 181 },
  { id: '4103', name: 'Dangray', user_id: User.first.id, extension_id: 181 },
  { id: '4104', name: 'Dangzhing', user_id: User.first.id, extension_id: 181 },
  { id: '4105', name: 'Darbab', user_id: User.first.id, extension_id: 181 },
  { id: '4106', name: 'Dorgen', user_id: User.first.id, extension_id: 181 },
  { id: '4107', name: 'Gaghar', user_id: User.first.id, extension_id: 181 },
  { id: '4108', name: 'Jee', user_id: User.first.id, extension_id: 181 },
  { id: '4109', name: 'Jee Pam', user_id: User.first.id, extension_id: 181 },
  { id: '4110', name: 'Jongthang', user_id: User.first.id, extension_id: 181 },
  { id: '4111', name: 'Kabab', user_id: User.first.id, extension_id: 181 },
  { id: '4112', name: 'Karshong', user_id: User.first.id, extension_id: 181 },
  { id: '4113', name: 'Lawshong', user_id: User.first.id, extension_id: 181 },
  { id: '4114', name: 'Pang', user_id: User.first.id, extension_id: 181 },
  { id: '4115', name: 'Phuntshocholing', user_id: User.first.id, extension_id: 181 },
  { id: '4116', name: 'Poengar', user_id: User.first.id, extension_id: 181 },
  { id: '4117', name: 'Singbee', user_id: User.first.id, extension_id: 181 },
  { id: '4118', name: 'Sinphu', user_id: User.first.id, extension_id: 181 },
  { id: '4119', name: 'Chela/Tela', user_id: User.first.id, extension_id: 181 },
  { id: '4120', name: 'Yuling', user_id: User.first.id, extension_id: 181 },
  { id: '4121', name: 'Thang Ngyel', user_id: User.first.id, extension_id: 181 },
  { id: '4122', name: 'Sinphu Goenpa', user_id: User.first.id, extension_id: 181 },
  { id: '4123', name: 'Simjong', user_id: User.first.id, extension_id: 181 },
  { id: '4124', name: 'Mangdiphu', user_id: User.first.id, extension_id: 181 },
  { id: '4125', name: 'Sherubling', user_id: User.first.id, extension_id: 181 },

  # Tangsibji
  { id: '4127', name: 'Chendijee', user_id: User.first.id, extension_id: 182 },
  { id: '4128', name: 'Drangla Goenpa', user_id: User.first.id, extension_id: 182 },
  { id: '4129', name: 'Kaladrame', user_id: User.first.id, extension_id: 182 },
  { id: '4130', name: 'Kalathrelme', user_id: User.first.id, extension_id: 182 },
  { id: '4131', name: 'Nyala Goenpa', user_id: User.first.id, extension_id: 182 },
  { id: '4132', name: 'Tangsibjee', user_id: User.first.id, extension_id: 182 },
  { id: '4133', name: 'Tshangkha', user_id: User.first.id, extension_id: 182 },
  { id: '4134', name: 'Trashichoeling', user_id: User.first.id, extension_id: 182 },
  { id: '4135', name: 'Maling', user_id: User.first.id, extension_id: 182 },
  { id: '4136', name: 'Sagachelw', user_id: User.first.id, extension_id: 182 },
  { id: '4137', name: 'Langdo', user_id: User.first.id, extension_id: 182 },

  # Trongsa Thromde
  { id: '4138', name: 'Trongsa Thromde', user_id: User.first.id, extension_id: 183 }
].each do |v|
  Village.find_or_create_by!(v)
end
