# frozen_string_literal: true

[
  # Saephu
  { id: '4576', name: 'Bumpailog', user_id: User.first.id, extension_id: 208 },
  { id: '4577', name: 'Buso', user_id: User.first.id, extension_id: 208 },
  { id: '4578', name: 'Darilog', user_id: User.first.id, extension_id: 208 },
  { id: '4579', name: 'Gangchukha', user_id: User.first.id, extension_id: 208 },
  { id: '4580', name: 'Langbi', user_id: User.first.id, extension_id: 208 },
  { id: '4581', name: 'Longtey', user_id: User.first.id, extension_id: 208 },
  { id: '4582', name: 'Lubzur', user_id: User.first.id, extension_id: 208 },
  { id: '4583', name: 'Nakha', user_id: User.first.id, extension_id: 208 },
  { id: '4584', name: 'Nangkha', user_id: User.first.id, extension_id: 208 },
  { id: '4585', name: 'Raho', user_id: User.first.id, extension_id: 208 },
  { id: '4586', name: 'Riwanang', user_id: User.first.id, extension_id: 208 },
  { id: '4587', name: 'Rukubji', user_id: User.first.id, extension_id: 208 },
  { id: '4588', name: 'Serthang', user_id: User.first.id, extension_id: 208 },
  { id: '4589', name: 'Wangdue Goenpa', user_id: User.first.id, extension_id: 208 },
  { id: '4590', name: 'Zeri', user_id: User.first.id, extension_id: 208 },
  { id: '4591', name: 'Longmey', user_id: User.first.id, extension_id: 208 },

  # Ruebisa
  { id: '4511', name: 'Agokhar', user_id: User.first.id, extension_id: 210 },
  { id: '4512', name: 'Alaygang', user_id: User.first.id, extension_id: 210 },
  { id: '4513', name: 'Banelbi', user_id: User.first.id, extension_id: 210 },
  { id: '4514', name: 'Begokhar', user_id: User.first.id, extension_id: 210 },
  { id: '4515', name: 'Begongma', user_id: User.first.id, extension_id: 210 },
  { id: '4516', name: 'Chaksekha', user_id: User.first.id, extension_id: 210 },
  { id: '4517', name: 'Chakselna', user_id: User.first.id, extension_id: 210 },
  { id: '4518', name: 'Chilikha', user_id: User.first.id, extension_id: 210 },
  { id: '4519', name: 'Chumetengkha', user_id: User.first.id, extension_id: 210 },
  { id: '4520', name: 'Dagphug', user_id: User.first.id, extension_id: 210 },
  { id: '4521', name: 'Dagphugyen', user_id: User.first.id, extension_id: 210 },
  { id: '4522', name: 'Damchen', user_id: User.first.id, extension_id: 210 },
  { id: '4523', name: 'Damrukha', user_id: User.first.id, extension_id: 210 },
  { id: '4524', name: 'Deymanang', user_id: User.first.id, extension_id: 210 },
  { id: '4525', name: 'Dochungthur', user_id: User.first.id, extension_id: 210 },
  { id: '4526', name: 'Dogorchabsa', user_id: User.first.id, extension_id: 210 },
  { id: '4527', name: 'Dongmey', user_id: User.first.id, extension_id: 210 },
  { id: '4528', name: 'Dongphel', user_id: User.first.id, extension_id: 210 },
  { id: '4529', name: 'Gangkhar', user_id: User.first.id, extension_id: 210 },
  { id: '4530', name: 'Golaykhar', user_id: User.first.id, extension_id: 210 },
  { id: '4531', name: 'Jala', user_id: User.first.id, extension_id: 210 },
  { id: '4532', name: 'Jangsanang', user_id: User.first.id, extension_id: 210 },
  { id: '4533', name: 'Jaserkha', user_id: User.first.id, extension_id: 210 },
  { id: '4534', name: 'Khamzog', user_id: User.first.id, extension_id: 210 },
  { id: '4535', name: 'Khotakha', user_id: User.first.id, extension_id: 210 },
  { id: '4536', name: 'Khotakha/Dongphel', user_id: User.first.id, extension_id: 210 },
  { id: '4537', name: 'Kiblung', user_id: User.first.id, extension_id: 210 },
  { id: '4538', name: 'Kikhorthang', user_id: User.first.id, extension_id: 210 },
  { id: '4539', name: 'Langdor', user_id: User.first.id, extension_id: 210 },
  { id: '4540', name: 'Lungchunang', user_id: User.first.id, extension_id: 210 },
  { id: '4541', name: 'Lungmagang', user_id: User.first.id, extension_id: 210 },
  { id: '4542', name: 'Marpheykhar', user_id: User.first.id, extension_id: 210 },
  { id: '4543', name: 'Namling', user_id: User.first.id, extension_id: 210 },
  { id: '4544', name: 'Nego', user_id: User.first.id, extension_id: 210 },
  { id: '4545', name: 'Ngalakha', user_id: User.first.id, extension_id: 210 },
  { id: '4546', name: 'Ngegobara', user_id: User.first.id, extension_id: 210 },
  { id: '4547', name: 'Nginsergang', user_id: User.first.id, extension_id: 210 },
  { id: '4548', name: 'Omchen', user_id: User.first.id, extension_id: 210 },
  { id: '4549', name: 'Omtekhar', user_id: User.first.id, extension_id: 210 },
  { id: '4550', name: 'Palukha', user_id: User.first.id, extension_id: 210 },
  { id: '4551', name: 'Phakhar', user_id: User.first.id, extension_id: 210 },
  { id: '4552', name: 'Rambigang', user_id: User.first.id, extension_id: 210 },
  { id: '4553', name: 'Ruechenkha', user_id: User.first.id, extension_id: 210 },
  { id: '4554', name: 'Ruemeynang', user_id: User.first.id, extension_id: 210 },
  { id: '4555', name: 'Rutekha', user_id: User.first.id, extension_id: 210 },
  { id: '4556', name: 'Samdupgang', user_id: User.first.id, extension_id: 210 },
  { id: '4557', name: 'Sammakhar', user_id: User.first.id, extension_id: 210 },
  { id: '4558', name: 'Samtengoenpa', user_id: User.first.id, extension_id: 210 },
  { id: '4559', name: 'Sejarkha', user_id: User.first.id, extension_id: 210 },
  { id: '4560', name: 'Shelay', user_id: User.first.id, extension_id: 210 },
  { id: '4561', name: 'Sheltogkha', user_id: User.first.id, extension_id: 210 },
  { id: '4562', name: 'Tashidingkha', user_id: User.first.id, extension_id: 210 },
  { id: '4563', name: 'Terkanang', user_id: User.first.id, extension_id: 210 },
  { id: '4564', name: 'Toelekha', user_id: User.first.id, extension_id: 210 },
  { id: '4565', name: 'Tshamchong', user_id: User.first.id, extension_id: 210 },
  { id: '4566', name: 'Tshamonang', user_id: User.first.id, extension_id: 210 },
  { id: '4567', name: 'Tshangmukha', user_id: User.first.id, extension_id: 210 },
  { id: '4568', name: 'Ulla', user_id: User.first.id, extension_id: 210 },
  { id: '4569', name: 'Wangduena', user_id: User.first.id, extension_id: 210 },
  { id: '4570', name: 'Zamding', user_id: User.first.id, extension_id: 210 },
  { id: '4571', name: 'Zamding/Omtekha', user_id: User.first.id, extension_id: 210 },
  { id: '4572', name: 'Ngacheygelkhar', user_id: User.first.id, extension_id: 210 },
  { id: '4573', name: 'Ngalabhi', user_id: User.first.id, extension_id: 210 },
  { id: '4574', name: 'Bangteykha', user_id: User.first.id, extension_id: 210 },

  # Thedtsho
  { id: '4593', name: 'Bajo', user_id: User.first.id, extension_id: 211 },
  { id: '4594', name: 'Gangteythangka', user_id: User.first.id, extension_id: 211 },
  { id: '4595', name: 'Gawapel', user_id: User.first.id, extension_id: 211 },
  { id: '4596', name: 'Marlung', user_id: User.first.id, extension_id: 211 },
  { id: '4597', name: 'Ngacheygelkhar', user_id: User.first.id, extension_id: 211 },
  { id: '4598', name: 'Ngalakhar', user_id: User.first.id, extension_id: 211 },
  { id: '4599', name: 'Rinchengang', user_id: User.first.id, extension_id: 211 },
  { id: '4600', name: 'Somelzab', user_id: User.first.id, extension_id: 211 },
  { id: '4601', name: 'Thango', user_id: User.first.id, extension_id: 211 },
  { id: '4602', name: 'Martolungchu', user_id: User.first.id, extension_id: 211 },
  { id: '4603', name: 'Wangjokha', user_id: User.first.id, extension_id: 211 },
  { id: '4604', name: 'Lho Rinchengang', user_id: User.first.id, extension_id: 211 },
  { id: '4605', name: 'Jang Rinchengang', user_id: User.first.id, extension_id: 211 },
  { id: '4606', name: 'Throm', user_id: User.first.id, extension_id: 211 },

  # Bajo Thromde
  { id: '4712', name: 'Throm', user_id: User.first.id, extension_id: 212 }
].each do |v|
  Village.find_or_create_by!(v)
end
