# frozen_string_literal: true

[
  # Gangteng
  { id: '4370', name: 'Gangtey', user_id: User.first.id, extension_id: 201 },
  { id: '4371', name: 'Gangtey Bjena', user_id: User.first.id, extension_id: 201 },
  { id: '4372', name: 'Gangtey Dangpa', user_id: User.first.id, extension_id: 201 },
  { id: '4373', name: 'Gangtey Gangkha', user_id: User.first.id, extension_id: 201 },
  { id: '4374', name: 'Gangtey Kibjekha', user_id: User.first.id, extension_id: 201 },
  { id: '4375', name: 'Gangtey Longtshog', user_id: User.first.id, extension_id: 201 },
  { id: '4376', name: 'Gangtey Lumchey', user_id: User.first.id, extension_id: 201 },
  { id: '4377', name: 'Gangtey Pangkha', user_id: User.first.id, extension_id: 201 },
  { id: '4378', name: 'Gangtey Phatekha', user_id: User.first.id, extension_id: 201 },
  { id: '4379', name: 'Gangtey Samchalog', user_id: User.first.id, extension_id: 201 },
  { id: '4380', name: 'Gangtey Tawaiteng', user_id: User.first.id, extension_id: 201 },
  { id: '4381', name: 'Geyla', user_id: User.first.id, extension_id: 201 },
  { id: '4382', name: 'Gorgoen', user_id: User.first.id, extension_id: 201 },
  { id: '4383', name: 'Kumbu', user_id: User.first.id, extension_id: 201 },
  { id: '4384', name: 'Taphug', user_id: User.first.id, extension_id: 201 },
  { id: '4385', name: 'Zigzee', user_id: User.first.id, extension_id: 201 },
  { id: '4386', name: 'Jangchen', user_id: User.first.id, extension_id: 201 },
  { id: '4387', name: 'Mang', user_id: User.first.id, extension_id: 201 },
  { id: '4388', name: 'Sangtena', user_id: User.first.id, extension_id: 201 },
  { id: '4389', name: 'Yusar', user_id: User.first.id, extension_id: 201 },
  { id: '4390', name: 'Pangkarpo', user_id: User.first.id, extension_id: 201 },
  { id: '4391', name: 'Damchenlhakhang', user_id: User.first.id, extension_id: 201 },
  { id: '4392', name: 'Beta', user_id: User.first.id, extension_id: 201 },
  { id: '4393', name: 'Boshonang', user_id: User.first.id, extension_id: 201 },
  { id: '4394', name: 'Gangtsawa', user_id: User.first.id, extension_id: 201 },
  { id: '4395', name: 'Mangthangka', user_id: User.first.id, extension_id: 201 },
  { id: '4396', name: 'Semchubara', user_id: User.first.id, extension_id: 201 },
  { id: '4397', name: 'Tokha', user_id: User.first.id, extension_id: 201 },
  { id: '4398', name: 'Yaekorwog', user_id: User.first.id, extension_id: 201 },
  { id: '4399', name: 'Rangjag', user_id: User.first.id, extension_id: 201 },

  # Kazhi
  { id: '4430', name: 'Beldo', user_id: User.first.id, extension_id: 202 },
  { id: '4431', name: 'Belpa', user_id: User.first.id, extension_id: 202 },
  { id: '4432', name: 'Chagip', user_id: User.first.id, extension_id: 202 },
  { id: '4433', name: 'Gyendeb', user_id: User.first.id, extension_id: 202 },
  { id: '4434', name: 'Kazhi', user_id: User.first.id, extension_id: 202 },
  { id: '4435', name: 'Komathang', user_id: User.first.id, extension_id: 202 },
  { id: '4436', name: 'Lenbi', user_id: User.first.id, extension_id: 202 },

  # Gase Tshogongm
  { id: '4401', name: 'Changchey', user_id: User.first.id, extension_id: 203 },
  { id: '4402', name: 'Dabchekha', user_id: User.first.id, extension_id: 203 },
  { id: '4403', name: 'Dung/Changzam', user_id: User.first.id, extension_id: 203 },
  { id: '4404', name: 'Dung/Khamena', user_id: User.first.id, extension_id: 203 },
  { id: '4405', name: 'Dung/Thoukha', user_id: User.first.id, extension_id: 203 },
  { id: '4406', name: 'Khateykha', user_id: User.first.id, extension_id: 203 },
  { id: '4407', name: 'Matshikha', user_id: User.first.id, extension_id: 203 },
  { id: '4408', name: 'Matshipoto', user_id: User.first.id, extension_id: 203 },
  { id: '4409', name: 'Tongzhong', user_id: User.first.id, extension_id: 203 },
  { id: '4410', name: 'Changkha', user_id: User.first.id, extension_id: 203 },
  { id: '4411', name: 'Pasakha', user_id: User.first.id, extension_id: 203 },
  { id: '4412', name: 'Ternga', user_id: User.first.id, extension_id: 203 },
  { id: '4413', name: 'Khamena', user_id: User.first.id, extension_id: 203 },
  { id: '4414', name: 'Langlu', user_id: User.first.id, extension_id: 203 },
  { id: '4415', name: 'Lashigang', user_id: User.first.id, extension_id: 203 },
  { id: '4416', name: 'Thoukha', user_id: User.first.id, extension_id: 203 },

  # Gase Tshowogm
  { id: '4418', name: 'Bjikha', user_id: User.first.id, extension_id: 204 },
  { id: '4419', name: 'Changkha', user_id: User.first.id, extension_id: 204 },
  { id: '4420', name: 'Hebesa', user_id: User.first.id, extension_id: 204 },
  { id: '4421', name: 'Heytshokha', user_id: User.first.id, extension_id: 204 },
  { id: '4422', name: 'Mebesa', user_id: User.first.id, extension_id: 204 },
  { id: '4423', name: 'Pasakha', user_id: User.first.id, extension_id: 204 },
  { id: '4424', name: 'Shingkhey', user_id: User.first.id, extension_id: 204 },
  { id: '4425', name: 'Tapchakha', user_id: User.first.id, extension_id: 204 },
  { id: '4426', name: 'Ternga', user_id: User.first.id, extension_id: 204 },
  { id: '4427', name: 'Shingkhey Khatoe', user_id: User.first.id, extension_id: 204 },
  { id: '4428', name: 'Shingkhey Khamey', user_id: User.first.id, extension_id: 204 },

  # Nyishog
  { id: '4446', name: 'Chebakha', user_id: User.first.id, extension_id: 205 },
  { id: '4447', name: 'Gangjab', user_id: User.first.id, extension_id: 205 },
  { id: '4448', name: 'Geylingkha', user_id: User.first.id, extension_id: 205 },
  { id: '4449', name: 'Gyensar', user_id: User.first.id, extension_id: 205 },
  { id: '4450', name: 'Kunzangling', user_id: User.first.id, extension_id: 205 },
  { id: '4451', name: 'Nyishokha', user_id: User.first.id, extension_id: 205 },
  { id: '4452', name: 'Samtengang', user_id: User.first.id, extension_id: 205 },
  { id: '4453', name: 'Chedalo', user_id: User.first.id, extension_id: 205 },
  { id: '4454', name: 'Chitokha', user_id: User.first.id, extension_id: 205 },
  { id: '4455', name: 'Dagsar', user_id: User.first.id, extension_id: 205 },
  { id: '4456', name: 'Zampa', user_id: User.first.id, extension_id: 205 },
  { id: '4457', name: 'Pangkha', user_id: User.first.id, extension_id: 205 },
  { id: '4458', name: 'Pangzhikhar', user_id: User.first.id, extension_id: 205 },
  { id: '4459', name: 'Chemtsheling', user_id: User.first.id, extension_id: 205 },
  { id: '4460', name: 'Chuzomsa', user_id: User.first.id, extension_id: 205 },
  { id: '4461', name: 'Dungdungnesa', user_id: User.first.id, extension_id: 205 },

  # Nahi
  { id: '4438', name: 'Halue', user_id: User.first.id, extension_id: 206 },
  { id: '4439', name: 'Hebesa', user_id: User.first.id, extension_id: 206 },
  { id: '4440', name: 'Khujunla', user_id: User.first.id, extension_id: 206 },
  { id: '4441', name: 'Nabisha', user_id: User.first.id, extension_id: 206 },
  { id: '4442', name: 'Pangshong', user_id: User.first.id, extension_id: 206 },
  { id: '4443', name: 'Yusagom', user_id: User.first.id, extension_id: 206 },
  { id: '4444', name: 'Yusawom', user_id: User.first.id, extension_id: 206 },

  # Phangyuel
  { id: '4463', name: 'Chunggoen', user_id: User.first.id, extension_id: 207 },
  { id: '4464', name: 'Chungserkha', user_id: User.first.id, extension_id: 207 },
  { id: '4465', name: 'Domkhar', user_id: User.first.id, extension_id: 207 },
  { id: '4466', name: 'Gyenkhar', user_id: User.first.id, extension_id: 207 },
  { id: '4467', name: 'Kumchi', user_id: User.first.id, extension_id: 207 },
  { id: '4468', name: 'Phangyul', user_id: User.first.id, extension_id: 207 },
  { id: '4469', name: 'Whanbekhar', user_id: User.first.id, extension_id: 207 },

  # Phobji
  { id: '4471', name: 'Chaji', user_id: User.first.id, extension_id: 209 },
  { id: '4472', name: 'Chemdo', user_id: User.first.id, extension_id: 209 },
  { id: '4473', name: 'Chumechen', user_id: User.first.id, extension_id: 209 },
  { id: '4474', name: 'Damcholhakhang', user_id: User.first.id, extension_id: 209 },
  { id: '4475', name: 'Dangpa', user_id: User.first.id, extension_id: 209 },
  { id: '4476', name: 'Dangsar', user_id: User.first.id, extension_id: 209 },
  { id: '4477', name: 'Darjeyjab', user_id: User.first.id, extension_id: 209 },
  { id: '4478', name: 'Dokselnang', user_id: User.first.id, extension_id: 209 },
  { id: '4479', name: 'Gangphel', user_id: User.first.id, extension_id: 209 },
  { id: '4480', name: 'Gangyed', user_id: User.first.id, extension_id: 209 },
  { id: '4481', name: 'Gorphu', user_id: User.first.id, extension_id: 209 },
  { id: '4482', name: 'Hapa', user_id: User.first.id, extension_id: 209 },
  { id: '4483', name: 'Jangchubgoenpa', user_id: User.first.id, extension_id: 209 },
  { id: '4484', name: 'Khendo', user_id: User.first.id, extension_id: 209 },
  { id: '4485', name: 'Khenwa', user_id: User.first.id, extension_id: 209 },
  { id: '4486', name: 'Kikhorthang', user_id: User.first.id, extension_id: 209 },
  { id: '4487', name: 'Kilthang', user_id: User.first.id, extension_id: 209 },
  { id: '4488', name: 'Lokchen', user_id: User.first.id, extension_id: 209 },
  { id: '4489', name: 'Mang', user_id: User.first.id, extension_id: 209 },
  { id: '4490', name: 'Mangchibor', user_id: User.first.id, extension_id: 209 },
  { id: '4491', name: 'Nenphel', user_id: User.first.id, extension_id: 209 },
  { id: '4492', name: 'Nimdosa', user_id: User.first.id, extension_id: 209 },
  { id: '4493', name: 'Pangsa', user_id: User.first.id, extension_id: 209 },
  { id: '4494', name: 'Poelam', user_id: User.first.id, extension_id: 209 },
  { id: '4495', name: 'Ramsarp', user_id: User.first.id, extension_id: 209 },
  { id: '4496', name: 'Sangtana', user_id: User.first.id, extension_id: 209 },
  { id: '4497', name: 'Tagphu', user_id: User.first.id, extension_id: 209 },
  { id: '4498', name: 'Talachen', user_id: User.first.id, extension_id: 209 },
  { id: '4499', name: 'Taphug', user_id: User.first.id, extension_id: 209 },
  { id: '4500', name: 'Tarchen', user_id: User.first.id, extension_id: 209 },
  { id: '4501', name: 'Tawa', user_id: User.first.id, extension_id: 209 },
  { id: '4502', name: 'Tengkhageyray', user_id: User.first.id, extension_id: 209 },
  { id: '4503', name: 'Tsheldar', user_id: User.first.id, extension_id: 209 },
  { id: '4504', name: 'Yulgo', user_id: User.first.id, extension_id: 209 },
  { id: '4505', name: 'Zhebar', user_id: User.first.id, extension_id: 209 },
  { id: '4506', name: 'Zhelam', user_id: User.first.id, extension_id: 209 },
  { id: '4507', name: 'Zhephug', user_id: User.first.id, extension_id: 209 },
  { id: '4508', name: 'Zhugar', user_id: User.first.id, extension_id: 209 },
  { id: '4509', name: 'Zigzee', user_id: User.first.id, extension_id: 209 }
].each do |v|
  Village.find_or_create_by!(v)
end
