# frozen_string_literal: true

puts 'Seeding villages of Wangdue Phodrang...'

[
  # Athang
  { id: '4239', name: 'Jarigang', user_id: User.first.id, extension_id: 197 },
  { id: '4240', name: 'Kago', user_id: User.first.id, extension_id: 197 },
  { id: '4241', name: 'Lamga', user_id: User.first.id, extension_id: 197 },
  { id: '4242', name: 'Lawa', user_id: User.first.id, extension_id: 197 },
  { id: '4243', name: 'Lomtshokha', user_id: User.first.id, extension_id: 197 },
  { id: '4244', name: 'Lophokha', user_id: User.first.id, extension_id: 197 },
  { id: '4245', name: 'Nangshina', user_id: User.first.id, extension_id: 197 },
  { id: '4246', name: 'Phaktakha', user_id: User.first.id, extension_id: 197 },
  { id: '4247', name: 'Rukha', user_id: User.first.id, extension_id: 197 },
  { id: '4248', name: 'Samthang', user_id: User.first.id, extension_id: 197 },
  { id: '4249', name: 'Taragangkha', user_id: User.first.id, extension_id: 197 },
  { id: '4250', name: 'Zawa', user_id: User.first.id, extension_id: 197 },
  { id: '4251', name: 'Migtana', user_id: User.first.id, extension_id: 197 },
  { id: '4252', name: 'Kashicheko', user_id: User.first.id, extension_id: 197 },

  # Bjenag
  { id: '4254', name: 'Bakakha', user_id: User.first.id, extension_id: 198 },
  { id: '4255', name: 'Balakhar', user_id: User.first.id, extension_id: 198 },
  { id: '4256', name: 'Bjashikhar', user_id: User.first.id, extension_id: 198 },
  { id: '4257', name: 'Bjenalumpa', user_id: User.first.id, extension_id: 198 },
  { id: '4258', name: 'Daku', user_id: User.first.id, extension_id: 198 },
  { id: '4259', name: 'Damzhingkhar', user_id: User.first.id, extension_id: 198 },
  { id: '4260', name: 'Darjeegang', user_id: User.first.id, extension_id: 198 },
  { id: '4261', name: 'Dekiling', user_id: User.first.id, extension_id: 198 },
  { id: '4262', name: 'Dongchen', user_id: User.first.id, extension_id: 198 },
  { id: '4263', name: 'Gangchukhar', user_id: User.first.id, extension_id: 198 },
  { id: '4264', name: 'Gangmakhar', user_id: User.first.id, extension_id: 198 },
  { id: '4265', name: 'Gangsimi', user_id: User.first.id, extension_id: 198 },
  { id: '4266', name: 'Garsikhar', user_id: User.first.id, extension_id: 198 },
  { id: '4267', name: 'Geyten', user_id: User.first.id, extension_id: 198 },
  { id: '4268', name: 'Gholaykhar', user_id: User.first.id, extension_id: 198 },
  { id: '4269', name: 'Ghuminang', user_id: User.first.id, extension_id: 198 },
  { id: '4270', name: 'Gogonang', user_id: User.first.id, extension_id: 198 },
  { id: '4271', name: 'Gonalu', user_id: User.first.id, extension_id: 198 },
  { id: '4272', name: 'Gongthangkha', user_id: User.first.id, extension_id: 198 },
  { id: '4273', name: 'Jagarlingchu', user_id: User.first.id, extension_id: 198 },
  { id: '4274', name: 'Jangsegang', user_id: User.first.id, extension_id: 198 },
  { id: '4275', name: 'Jayebamo', user_id: User.first.id, extension_id: 198 },
  { id: '4276', name: 'Kangtheytewa', user_id: User.first.id, extension_id: 198 },
  { id: '4277', name: 'Khametey', user_id: User.first.id, extension_id: 198 },
  { id: '4278', name: 'Khangminang', user_id: User.first.id, extension_id: 198 },
  { id: '4279', name: 'Khatangkhar', user_id: User.first.id, extension_id: 198 },
  { id: '4280', name: 'Khelakhar', user_id: User.first.id, extension_id: 198 },
  { id: '4281', name: 'Kokoju', user_id: User.first.id, extension_id: 198 },
  { id: '4282', name: 'Kokokhar', user_id: User.first.id, extension_id: 198 },
  { id: '4283', name: 'Kokotey', user_id: User.first.id, extension_id: 198 },
  { id: '4284', name: 'Kucheykhar', user_id: User.first.id, extension_id: 198 },
  { id: '4285', name: 'Lamdogkha', user_id: User.first.id, extension_id: 198 },
  { id: '4286', name: 'Lhakhangchen', user_id: User.first.id, extension_id: 198 },
  { id: '4287', name: 'Lhamikhar', user_id: User.first.id, extension_id: 198 },
  { id: '4288', name: 'Lumpa', user_id: User.first.id, extension_id: 198 },
  { id: '4289', name: 'Lungmo', user_id: User.first.id, extension_id: 198 },
  { id: '4290', name: 'Lungphugang', user_id: User.first.id, extension_id: 198 },
  { id: '4291', name: 'Nalagang', user_id: User.first.id, extension_id: 198 },
  { id: '4292', name: 'Namgyelling', user_id: User.first.id, extension_id: 198 },
  { id: '4293', name: 'Ngawang', user_id: User.first.id, extension_id: 198 },
  { id: '4294', name: 'Okorshing', user_id: User.first.id, extension_id: 198 },
  { id: '4295', name: 'Omcheygang', user_id: User.first.id, extension_id: 198 },
  { id: '4296', name: 'Omkhag', user_id: User.first.id, extension_id: 198 },
  { id: '4297', name: 'Pangmakhar', user_id: User.first.id, extension_id: 198 },
  { id: '4298', name: 'Pangmarchu', user_id: User.first.id, extension_id: 198 },
  { id: '4299', name: 'Pangmarpo', user_id: User.first.id, extension_id: 198 },
  { id: '4300', name: 'Pangshikhar', user_id: User.first.id, extension_id: 198 },
  { id: '4301', name: 'Pelchu', user_id: User.first.id, extension_id: 198 },
  { id: '4302', name: 'Phachusar', user_id: User.first.id, extension_id: 198 },
  { id: '4303', name: 'Phaksitokhar', user_id: User.first.id, extension_id: 198 },
  { id: '4304', name: 'Phakteykhar', user_id: User.first.id, extension_id: 198 },
  { id: '4305', name: 'Phuntshogang', user_id: User.first.id, extension_id: 198 },
  { id: '4306', name: 'Rinchenling', user_id: User.first.id, extension_id: 198 },
  { id: '4307', name: 'Sershongnang', user_id: User.first.id, extension_id: 198 },
  { id: '4308', name: 'Shacheykhar', user_id: User.first.id, extension_id: 198 },
  { id: '4309', name: 'Sharchu', user_id: User.first.id, extension_id: 198 },
  { id: '4310', name: 'Shokeylog', user_id: User.first.id, extension_id: 198 },
  { id: '4311', name: 'Sisidakar', user_id: User.first.id, extension_id: 198 },
  { id: '4312', name: 'Somchugang', user_id: User.first.id, extension_id: 198 },
  { id: '4313', name: 'Songteykhar', user_id: User.first.id, extension_id: 198 },
  { id: '4314', name: 'Takakhar', user_id: User.first.id, extension_id: 198 },
  { id: '4315', name: 'Tarog', user_id: User.first.id, extension_id: 198 },
  { id: '4316', name: 'Tarshingtshawa', user_id: User.first.id, extension_id: 198 },
  { id: '4317', name: 'Tashi Lakha', user_id: User.first.id, extension_id: 198 },
  { id: '4318', name: 'Tashi Tokha', user_id: User.first.id, extension_id: 198 },
  { id: '4319', name: 'Thingpakhar', user_id: User.first.id, extension_id: 198 },
  { id: '4320', name: 'Toekhar', user_id: User.first.id, extension_id: 198 },
  { id: '4321', name: 'Toekikhar', user_id: User.first.id, extension_id: 198 },
  { id: '4322', name: 'Toekizingkha', user_id: User.first.id, extension_id: 198 },
  { id: '4323', name: 'Tongchenang', user_id: User.first.id, extension_id: 198 },
  { id: '4324', name: 'Tshangcheykhar', user_id: User.first.id, extension_id: 198 },
  { id: '4325', name: 'Tshedalo', user_id: User.first.id, extension_id: 198 },
  { id: '4326', name: 'Tsheripangchu', user_id: User.first.id, extension_id: 198 },
  { id: '4327', name: 'Tshikongnang', user_id: User.first.id, extension_id: 198 },
  { id: '4328', name: 'Wachey', user_id: User.first.id, extension_id: 198 },
  { id: '4329', name: 'Wakhar', user_id: User.first.id, extension_id: 198 },
  { id: '4330', name: 'Yuchu', user_id: User.first.id, extension_id: 198 },
  { id: '4331', name: 'Yusakha', user_id: User.first.id, extension_id: 198 },
  { id: '4332', name: 'Zangteykhar', user_id: User.first.id, extension_id: 198 },
  { id: '4333', name: 'Jangrinang', user_id: User.first.id, extension_id: 198 },
  { id: '4334', name: 'Gangkakha', user_id: User.first.id, extension_id: 198 },

  # Darkar
  { id: '4336', name: 'Gebakha', user_id: User.first.id, extension_id: 199 },
  { id: '4337', name: 'Kamina', user_id: User.first.id, extension_id: 199 },
  { id: '4338', name: 'Silli', user_id: User.first.id, extension_id: 199 },
  { id: '4339', name: 'Taksha', user_id: User.first.id, extension_id: 199 },
  { id: '4340', name: 'Tsara', user_id: User.first.id, extension_id: 199 },
  { id: '4341', name: 'Uma Khamey', user_id: User.first.id, extension_id: 199 },
  { id: '4342', name: 'Uma Khatey', user_id: User.first.id, extension_id: 199 },
  { id: '4343', name: 'Yogay', user_id: User.first.id, extension_id: 199 },

  # Dangchhu
  { id: '4345', name: 'Bammey', user_id: User.first.id, extension_id: 200 },
  { id: '4346', name: 'Chubarwogma', user_id: User.first.id, extension_id: 200 },
  { id: '4347', name: 'Chuburtam', user_id: User.first.id, extension_id: 200 },
  { id: '4348', name: 'Dencholing', user_id: User.first.id, extension_id: 200 },
  { id: '4349', name: 'Dongsinang', user_id: User.first.id, extension_id: 200 },
  { id: '4350', name: 'Godangoenpa', user_id: User.first.id, extension_id: 200 },
  { id: '4351', name: 'Godrang', user_id: User.first.id, extension_id: 200 },
  { id: '4352', name: 'Longmey', user_id: User.first.id, extension_id: 200 },
  { id: '4353', name: 'Lumju', user_id: User.first.id, extension_id: 200 },
  { id: '4354', name: 'Nempang', user_id: User.first.id, extension_id: 200 },
  { id: '4355', name: 'Norbuding', user_id: User.first.id, extension_id: 200 },
  { id: '4356', name: 'Penjorling', user_id: User.first.id, extension_id: 200 },
  { id: '4357', name: 'Phuntshogang', user_id: User.first.id, extension_id: 200 },
  { id: '4358', name: 'Reegoan', user_id: User.first.id, extension_id: 200 },
  { id: '4359', name: 'Ridagoenpa', user_id: User.first.id, extension_id: 200 },
  { id: '4360', name: 'Rithangwog', user_id: User.first.id, extension_id: 200 },
  { id: '4361', name: 'Selgonang', user_id: User.first.id, extension_id: 200 },
  { id: '4362', name: 'Taksar', user_id: User.first.id, extension_id: 200 },
  { id: '4363', name: 'Tashidingkha', user_id: User.first.id, extension_id: 200 },
  { id: '4364', name: 'Tashigang', user_id: User.first.id, extension_id: 200 },
  { id: '4365', name: 'Tokaling', user_id: User.first.id, extension_id: 200 },
  { id: '4366', name: 'Tomla', user_id: User.first.id, extension_id: 200 },
  { id: '4367', name: 'Yusagang', user_id: User.first.id, extension_id: 200 },
  { id: '4368', name: 'Zime', user_id: User.first.id, extension_id: 200 }
].each do |v|
  Village.find_or_create_by!(v)
end
